; mul_u32_u32_u64_turbo — exact executable source mirror for v4_reu_16m
; Legacy API: MATH_REU_UMUL32 at $3900
; GENERATED by tools/publish_standalone_sources.py. Do not hand-edit.
; Shipped image: v4_reu_16m/resident/math_v4_reu_16m_game_math.prg
; Canonical integrated/relocatable source: relocatable_source/v4_reu_16m/math_relocatable.asm
; This file contains every executable instruction statically reachable from the public entry after MATH_INIT.
; Shared immutable lookup/data tables and REU payload data are intentionally not duplicated here.
; The address/byte annotations make this a mechanically auditable source view of the shipped executable.
; Reachable instructions: 167.
!cpu 6510

; ---- executable island $001A ----
* = $001A
L001A:
    clc                                ; @001A 18
    adc ($61),y                        ; @001B 71 61
    sta $0D,x                          ; @001D 95 0D
    lda #$01                           ; @001F A9 01
    adc ($66),y                        ; @0021 71 66
    adc ($69),y                        ; @0023 71 69
    adc ($6C),y                        ; @0025 71 6C
    bcc L0070                          ; @0027 90 47
L0029:
    clc                                ; @0029 18
    adc ($71),y                        ; @002A 71 71
    sta $11,x                          ; @002C 95 11
    lda #$01                           ; @002E A9 01
    adc ($76),y                        ; @0030 71 76
    adc ($79),y                        ; @0032 71 79
    adc ($7C),y                        ; @0034 71 7C
    bcc L0080                          ; @0036 90 48
L0038:
    clc                                ; @0038 18
    adc ($81),y                        ; @0039 71 81
    sta $15,x                          ; @003B 95 15
    lda #$01                           ; @003D A9 01
    adc ($86),y                        ; @003F 71 86
    adc ($89),y                        ; @0041 71 89
    dex                                ; @0043 CA
    beq L008E                          ; @0044 F0 48
L0046:
    sta $C00C,x                        ; @0046 9D 0C C0
    ldy $C003,x                        ; @0049 BC 03 C0
L004C:
    lda $7000,y                        ; @004C B9 00 70
    adc $7400,y                        ; @004F 79 00 74
    sta $C007,x                        ; @0052 9D 07 C0
    lda $7200,y                        ; @0055 B9 00 72
    adc $7600,y                        ; @0058 79 00 76
    adc $7000,y                        ; @005B 79 00 70
    bcs L001A                          ; @005E B0 BA
    adc $7400,y                        ; @0060 79 00 74
    sta $0D,x                          ; @0063 95 0D
    lda $7200,y                        ; @0065 B9 00 72
    adc $7600,y                        ; @0068 79 00 76
    adc $7000,y                        ; @006B 79 00 70
    bcs L0029                          ; @006E B0 B9
L0070:
    adc $7400,y                        ; @0070 79 00 74
    sta $11,x                          ; @0073 95 11
    lda $7200,y                        ; @0075 B9 00 72
    adc $7600,y                        ; @0078 79 00 76
    adc $7000,y                        ; @007B 79 00 70
    bcs L0038                          ; @007E B0 B8
L0080:
    adc $7400,y                        ; @0080 79 00 74
    sta $15,x                          ; @0083 95 15
    lda $7200,y                        ; @0085 B9 00 72
    adc $7600,y                        ; @0088 79 00 76
    dex                                ; @008B CA
    bne L0046                          ; @008C D0 B8
L008E:
    jmp L1100                          ; @008E 4C 00 11
; ---- executable island $1002 ----
* = $1002
L1002:
    sta $56                            ; @1002 85 56
    eor #$FF                           ; @1004 49 FF
    sta $50                            ; @1006 85 50
    sta $59                            ; @1008 85 59
    lda $5C                            ; @100A A5 5C
    sta $66                            ; @100C 85 66
    eor #$FF                           ; @100E 49 FF
    sta $61                            ; @1010 85 61
    sta $69                            ; @1012 85 69
    lda $6C                            ; @1014 A5 6C
    sta $76                            ; @1016 85 76
    eor #$FF                           ; @1018 49 FF
    sta $71                            ; @101A 85 71
    sta $79                            ; @101C 85 79
    lda $7C                            ; @101E A5 7C
    sta $86                            ; @1020 85 86
    eor #$FF                           ; @1022 49 FF
    sta $81                            ; @1024 85 81
    sta $89                            ; @1026 85 89
    ldx #$04                           ; @1028 A2 04
    sec                                ; @102A 38
    jmp L004C                          ; @102B 4C 4C 00
L102E:
    inc $15                            ; @102E E6 15
    bne L1039                          ; @1030 D0 07
    inc $19                            ; @1032 E6 19
    bne L1039                          ; @1034 D0 03
    inc $C00F                          ; @1036 EE 0F C0
L1039:
    clc                                ; @1039 18
    jmp L1135                          ; @103A 4C 35 11
L103D:
    inc $19                            ; @103D E6 19
    bne L1044                          ; @103F D0 03
    inc $C00F                          ; @1041 EE 0F C0
L1044:
    jmp L1149                          ; @1044 4C 49 11
; ---- executable island $1100 ----
* = $1100
L1100:
    tay                                ; @1100 A8
    clc                                ; @1101 18
    lda $0E                            ; @1102 A5 0E
    adc $C009                          ; @1104 6D 09 C0
    sta $C009                          ; @1107 8D 09 C0
    lda $C00A                          ; @110A AD 0A C0
    adc $0F                            ; @110D 65 0F
    bcc L1113                          ; @110F 90 02
    inx                                ; @1111 E8
    clc                                ; @1112 18
L1113:
    adc $12                            ; @1113 65 12
    sta $C00A                          ; @1115 8D 0A C0
    lda $16                            ; @1118 A5 16
    adc $13                            ; @111A 65 13
    bcc L112D                          ; @111C 90 0F
    iny                                ; @111E C8
    cpx #$01                           ; @111F E0 01
    adc $C00B                          ; @1121 6D 0B C0
    bcc L1135                          ; @1124 90 0F
    clc                                ; @1126 18
    iny                                ; @1127 C8
    bne L1135                          ; @1128 D0 0B
    jmp L102E                          ; @112A 4C 2E 10
L112D:
    adc $C00B                          ; @112D 6D 0B C0
    bcc L1133                          ; @1130 90 01
    iny                                ; @1132 C8
L1133:
    cpx #$01                           ; @1133 E0 01
L1135:
    adc $10                            ; @1135 65 10
    sta $C00B                          ; @1137 8D 0B C0
    tya                                ; @113A 98
    ldx $C00D                          ; @113B AE 0D C0
    adc $17                            ; @113E 65 17
    bcs L117B                          ; @1140 B0 39
    adc $11                            ; @1142 65 11
    bcc L114A                          ; @1144 90 04
    inx                                ; @1146 E8
    beq L1184                          ; @1147 F0 3B
L1149:
    clc                                ; @1149 18
L114A:
    adc $14                            ; @114A 65 14
    sta $C00C                          ; @114C 8D 0C C0
    txa                                ; @114F 8A
    adc $15                            ; @1150 65 15
    bcs L1169                          ; @1152 B0 15
    adc $18                            ; @1154 65 18
    tax                                ; @1156 AA
    lda $C00E                          ; @1157 AD 0E C0
    adc $19                            ; @115A 65 19
    bcs L1163                          ; @115C B0 05
    jmp L391A                          ; @115E 4C 1A 39
L1161:
    adc #$00                           ; @1161 69 00
L1163:
    inc $C00F                          ; @1163 EE 0F C0
    jmp L391A                          ; @1166 4C 1A 39
L1169:
    clc                                ; @1169 18
    adc $18                            ; @116A 65 18
    tax                                ; @116C AA
    lda $C00E                          ; @116D AD 0E C0
    adc $19                            ; @1170 65 19
    bcs L1161                          ; @1172 B0 ED
    adc #$01                           ; @1174 69 01
    bcs L1163                          ; @1176 B0 EB
    jmp L391A                          ; @1178 4C 1A 39
L117B:
    inx                                ; @117B E8
    clc                                ; @117C 18
    adc $11                            ; @117D 65 11
    bcc L114A                          ; @117F 90 C9
    inx                                ; @1181 E8
    bne L1149                          ; @1182 D0 C5
L1184:
    jmp L103D                          ; @1184 4C 3D 10
; ---- executable island $3900 ----
* = $3900
mul_u32_u32_u64_turbo:
MATH_REU_UMUL32:
    lda $C001                          ; @3900 AD 01 C0
    sta $5C                            ; @3903 85 5C
    lda $C002                          ; @3905 AD 02 C0
    sta $6C                            ; @3908 85 6C
    lda $C003                          ; @390A AD 03 C0
    sta $7C                            ; @390D 85 7C
    ldy $C007                          ; @390F AC 07 C0
    lda $C000                          ; @3912 AD 00 C0
    sta $4D                            ; @3915 85 4D
    jmp L1002                          ; @3917 4C 02 10
L391A:
    sta $C00E                          ; @391A 8D 0E C0
    stx $C00D                          ; @391D 8E 0D C0
    clc                                ; @3920 18
    rts                                ; @3921 60
