; seek_u16_u8_step_int — exact executable source mirror for v4_reu_16m
; Legacy API: MATH_SEEK16_STEP_INT at $5E4E
; GENERATED by tools/publish_standalone_sources.py. Do not hand-edit.
; Shipped image: v4_reu_16m/resident/math_v4_reu_16m_game_math.prg
; Canonical integrated/relocatable source: relocatable_source/v4_reu_16m/math_relocatable.asm
; This file contains every executable instruction statically reachable from the public entry after MATH_INIT.
; Shared immutable lookup/data tables and REU payload data are intentionally not duplicated here.
; The address/byte annotations make this a mechanically auditable source view of the shipped executable.
; Reachable instructions: 59.
!cpu 6510

; ---- executable island $400C ----
* = $400C
L400C:
    lda $9100,x                        ; @400C BD 00 91
    sta $90E8,x                        ; @400F 9D E8 90
    lda $9108,x                        ; @4012 BD 08 91
    sta $90F0,x                        ; @4015 9D F0 90
    lda $9110,x                        ; @4018 BD 10 91
    sta $90F8,x                        ; @401B 9D F8 90
    lda #$00                           ; @401E A9 00
    sta $9120,x                        ; @4020 9D 20 91
    sta $9128,x                        ; @4023 9D 28 91
    lda #$01                           ; @4026 A9 01
    sta $9158,x                        ; @4028 9D 58 91
    sec                                ; @402B 38
    rts                                ; @402C 60
L402D:
    dec $9128,x                        ; @402D DE 28 91
    bmi L400C                          ; @4030 30 DA
    sec                                ; @4032 38
    jmp L404E                          ; @4033 4C 4E 40
; ---- executable island $4042 ----
* = $4042
L4042:
    sec                                ; @4042 38
    lda $9120,x                        ; @4043 BD 20 91
    sbc $9158,x                        ; @4046 FD 58 91
    sta $9120,x                        ; @4049 9D 20 91
    bcc L402D                          ; @404C 90 DF
L404E:
    lda $9130,x                        ; @404E BD 30 91
    sbc $9160,x                        ; @4051 FD 60 91
    sta $9130,x                        ; @4054 9D 30 91
    lda $9138,x                        ; @4057 BD 38 91
    sbc $9170,x                        ; @405A FD 70 91
    bcc L407F                          ; @405D 90 20
    sta $9138,x                        ; @405F 9D 38 91
    lda $90E8,x                        ; @4062 BD E8 90
    adc $9180,x                        ; @4065 7D 80 91
    sta $90E8,x                        ; @4068 9D E8 90
    lda $90F0,x                        ; @406B BD F0 90
    adc $91A0,x                        ; @406E 7D A0 91
    sta $90F0,x                        ; @4071 9D F0 90
    lda $90F8,x                        ; @4074 BD F8 90
    adc $91C0,x                        ; @4077 7D C0 91
    sta $90F8,x                        ; @407A 9D F8 90
    clc                                ; @407D 18
    rts                                ; @407E 60
L407F:
    tay                                ; @407F A8
    lda $9130,x                        ; @4080 BD 30 91
    adc $9140,x                        ; @4083 7D 40 91
    sta $9130,x                        ; @4086 9D 30 91
    tya                                ; @4089 98
    adc $9148,x                        ; @408A 7D 48 91
    sta $9138,x                        ; @408D 9D 38 91
    lda $90E8,x                        ; @4090 BD E8 90
    adc $9190,x                        ; @4093 7D 90 91
    sta $90E8,x                        ; @4096 9D E8 90
    lda $90F0,x                        ; @4099 BD F0 90
    adc $91B0,x                        ; @409C 7D B0 91
    sta $90F0,x                        ; @409F 9D F0 90
    lda $90F8,x                        ; @40A2 BD F8 90
    adc $91D0,x                        ; @40A5 7D D0 91
    sta $90F8,x                        ; @40A8 9D F8 90
    clc                                ; @40AB 18
    rts                                ; @40AC 60
; ---- executable island $5E4E ----
* = $5E4E
seek_u16_u8_step_int:
MATH_SEEK16_STEP_INT:
    jmp L4042                          ; @5E4E 4C 42 40
