; MATH_SMUL16_SHR8 — exact native-signed executable source mirror for v1_balanced
; GENERATED by tools/publish_native_signed_sources.py. Do not hand-edit.
; Canonical integrated build source remains relocatable_source/v1_balanced/math_relocatable.asm
; This mirror contains every executable instruction reachable from this signed API after MATH_INIT.
; Immutable lookup/data tables are intentionally not duplicated here.
; Corresponding unsigned API: MATH_UMUL16_SHR8. Executable overlap: 0 instructions.
; Public entry: $5E0F. Reachable signed instructions: 137.
; Each instruction has an @ADDR byte annotation used by the publication validator.
!cpu 6510

; ---- executable island $3BB0 ----
* = $3BB0
L3BB0:
    lda #$84                           ; @3BB0 A9 84
    sta $0A                            ; @3BB2 85 0A
    sta $12                            ; @3BB4 85 12
    lda #$88                           ; @3BB6 A9 88
    sta $0C                            ; @3BB8 85 0C
    sta $14                            ; @3BBA 85 14
    lda #$86                           ; @3BBC A9 86
    sta $0E                            ; @3BBE 85 0E
    sta $16                            ; @3BC0 85 16
    lda #$8A                           ; @3BC2 A9 8A
    sta $10                            ; @3BC4 85 10
    sta $18                            ; @3BC6 85 18
    ldx $C005                          ; @3BC8 AE 05 C0
    stx $CF17                          ; @3BCB 8E 17 CF
    lda $C000                          ; @3BCE AD 00 C0
    sta $09                            ; @3BD1 85 09
    ldy $C004                          ; @3BD3 AC 04 C0
    lda $C001                          ; @3BD6 AD 01 C0
    sta $11                            ; @3BD9 85 11
    jsr LCE02                          ; @3BDB 20 02 CE
    sta $C00A                          ; @3BDE 8D 0A C0
    stx $C009                          ; @3BE1 8E 09 C0
    sty $C00B                          ; @3BE4 8C 0B C0
    lda $19                            ; @3BE7 A5 19
    sta $C008                          ; @3BE9 8D 08 C0
    clc                                ; @3BEC 18
    rts                                ; @3BED 60
; ---- executable island $5E0F ----
* = $5E0F
L5E0F:
    jmp LCF80                          ; @5E0F 4C 80 CF
; ---- executable island $CE02 ----
* = $CE02
LCE02:
    bmi LCE0B                          ; @CE02 30 07
    cpx #$00                           ; @CE04 E0 00
    bmi LCE20                          ; @CE06 30 18
    jmp LCEEC                          ; @CE08 4C EC CE
LCE0B:
    cpx #$00                           ; @CE0B E0 00
    bmi LCE2F                          ; @CE0D 30 20
    jsr LCEEC                          ; @CE0F 20 EC CE
    sec                                ; @CE12 38
    sbc $C004                          ; @CE13 ED 04 C0
    sta $0D                            ; @CE16 85 0D
    tya                                ; @CE18 98
    sbc $CF17                          ; @CE19 ED 17 CF
    tay                                ; @CE1C A8
    lda $0D                            ; @CE1D A5 0D
    rts                                ; @CE1F 60
LCE20:
    jsr LCEEC                          ; @CE20 20 EC CE
    sec                                ; @CE23 38
    sbc $09                            ; @CE24 E5 09
    sta $0D                            ; @CE26 85 0D
    tya                                ; @CE28 98
    sbc $11                            ; @CE29 E5 11
    tay                                ; @CE2B A8
    lda $0D                            ; @CE2C A5 0D
    rts                                ; @CE2E 60
LCE2F:
    lda #$00                           ; @CE2F A9 00
    sbc $C004                          ; @CE31 ED 04 C0
    tay                                ; @CE34 A8
    lda #$00                           ; @CE35 A9 00
    sbc $CF17                          ; @CE37 ED 17 CF
    sta $CF17                          ; @CE3A 8D 17 CF
    lda #$01                           ; @CE3D A9 01
    sbc $09                            ; @CE3F E5 09
    sta $09                            ; @CE41 85 09
    sta $0D                            ; @CE43 85 0D
    eor #$FF                           ; @CE45 49 FF
    sta $0B                            ; @CE47 85 0B
    sta $0F                            ; @CE49 85 0F
    lda #$00                           ; @CE4B A9 00
    sbc $11                            ; @CE4D E5 11
    sta $11                            ; @CE4F 85 11
    sta $15                            ; @CE51 85 15
    eor #$FF                           ; @CE53 49 FF
    sta $13                            ; @CE55 85 13
    sta $17                            ; @CE57 85 17
    sec                                ; @CE59 38
    jmp LCEFE                          ; @CE5A 4C FE CE
; ---- executable island $CEEC ----
* = $CEEC
LCEEC:
    sta $15                            ; @CEEC 85 15
    eor #$FF                           ; @CEEE 49 FF
    sta $13                            ; @CEF0 85 13
    sta $17                            ; @CEF2 85 17
    lda $09                            ; @CEF4 A5 09
    sta $0D                            ; @CEF6 85 0D
    eor #$FF                           ; @CEF8 49 FF
    sta $0B                            ; @CEFA 85 0B
    sta $0F                            ; @CEFC 85 0F
LCEFE:
    lda ($09),y                        ; @CEFE B1 09
    adc ($0B),y                        ; @CF00 71 0B
    sta $19                            ; @CF02 85 19
    lda ($0D),y                        ; @CF04 B1 0D
    adc ($0F),y                        ; @CF06 71 0F
    adc ($11),y                        ; @CF08 71 11
    bcs LCF3F                          ; @CF0A B0 33
    adc ($13),y                        ; @CF0C 71 13
    tax                                ; @CF0E AA
    lda ($15),y                        ; @CF0F B1 15
LCF11:
    adc ($17),y                        ; @CF11 71 17
    sta $CF37                          ; @CF13 8D 37 CF
    ldy #$00                           ; @CF16 A0 00
    lda ($09),y                        ; @CF18 B1 09
    adc ($0B),y                        ; @CF1A 71 0B
    sta $CF34                          ; @CF1C 8D 34 CF
    lda ($0D),y                        ; @CF1F B1 0D
    adc ($0F),y                        ; @CF21 71 0F
    adc ($11),y                        ; @CF23 71 11
    bcs LCF49                          ; @CF25 B0 22
    adc ($13),y                        ; @CF27 71 13
    sta $CF39                          ; @CF29 8D 39 CF
    lda ($15),y                        ; @CF2C B1 15
LCF2E:
    adc ($17),y                        ; @CF2E 71 17
    tay                                ; @CF30 A8
    clc                                ; @CF31 18
    txa                                ; @CF32 8A
    adc #$00                           ; @CF33 69 00
    tax                                ; @CF35 AA
    lda #$00                           ; @CF36 A9 00
    adc #$00                           ; @CF38 69 00
    bcs LCF3D                          ; @CF3A B0 01
    rts                                ; @CF3C 60
LCF3D:
    iny                                ; @CF3D C8
    rts                                ; @CF3E 60
LCF3F:
    clc                                ; @CF3F 18
    adc ($13),y                        ; @CF40 71 13
    tax                                ; @CF42 AA
    lda #$01                           ; @CF43 A9 01
    adc ($15),y                        ; @CF45 71 15
    bcc LCF11                          ; @CF47 90 C8
LCF49:
    clc                                ; @CF49 18
    adc ($13),y                        ; @CF4A 71 13
    sta $CF39                          ; @CF4C 8D 39 CF
    lda #$01                           ; @CF4F A9 01
    adc ($15),y                        ; @CF51 71 15
    bcc LCF2E                          ; @CF53 90 D9
    brk                                ; @CF55 00
; ---- executable island $CF80 ----
* = $CF80
LCF80:
    jsr L3BB0                          ; @CF80 20 B0 3B
    stx $C008                          ; @CF83 8E 08 C0
    lda $C00A                          ; @CF86 AD 0A C0
    sta $C009                          ; @CF89 8D 09 C0
    sty $C00A                          ; @CF8C 8C 0A C0
    rts                                ; @CF8F 60
