; MATH_SDIV32_16 — exact native-signed executable source mirror for v5_hybrid_lowzp
; GENERATED by tools/publish_native_signed_sources.py. Do not hand-edit.
; Canonical integrated build source remains relocatable_source/v1_balanced/math_relocatable.asm + tools/build_hybrid.py
; This mirror contains every executable instruction reachable from this signed API after MATH_INIT.
; Immutable lookup/data tables are intentionally not duplicated here.
; Corresponding unsigned API: MATH_UDIV32_16. Executable overlap: 0 instructions.
; Public entry: $3EE0. Reachable signed instructions: 285.
; Each instruction has an @ADDR byte annotation used by the publication validator.
!cpu 6510

; ---- executable island $2590 ----
* = $2590
L2590:
    lda $C010                          ; @2590 AD 10 C0
    sta $0E                            ; @2593 85 0E
    lda $C011                          ; @2595 AD 11 C0
    sta $0F                            ; @2598 85 0F
    lda $C012                          ; @259A AD 12 C0
    sta $10                            ; @259D 85 10
    lda $C013                          ; @259F AD 13 C0
    sta $11                            ; @25A2 85 11
    lda $C014                          ; @25A4 AD 14 C0
    sta $12                            ; @25A7 85 12
    lda $C015                          ; @25A9 AD 15 C0
    sta $13                            ; @25AC 85 13
    jsr L5C00                          ; @25AE 20 00 5C
    lda $1E                            ; @25B1 A5 1E
    sta $C018                          ; @25B3 8D 18 C0
    lda $1F                            ; @25B6 A5 1F
    sta $C019                          ; @25B8 8D 19 C0
    lda $18                            ; @25BB A5 18
    sta $C01A                          ; @25BD 8D 1A C0
    lda $19                            ; @25C0 A5 19
    sta $C01B                          ; @25C2 8D 1B C0
    lda $1A                            ; @25C5 A5 1A
    sta $C01C                          ; @25C7 8D 1C C0
    lda $1B                            ; @25CA A5 1B
    sta $C01D                          ; @25CC 8D 1D C0
    rts                                ; @25CF 60
; ---- executable island $3EE0 ----
* = $3EE0
L3EE0:
    jmp L2590                          ; @3EE0 4C 90 25
; ---- executable island $5A00 ----
* = $5A00
L5A00:
    !byte $A7, $15    ; LAX zp         ; @5A00 A7 15
    cmp $17                            ; @5A02 C5 17
    bcc L5A6F                          ; @5A04 90 69
    lda $17                            ; @5A06 A5 17
    beq L5A35                          ; @5A08 F0 2B
    cmp #$05                           ; @5A0A C9 05
    bcc L5A42                          ; @5A0C 90 34
    lda $14                            ; @5A0E A5 14
    sbc $16                            ; @5A10 E5 16
    tay                                ; @5A12 A8
    txa                                ; @5A13 8A
    sbc $17                            ; @5A14 E5 17
    bcc L5A6F                          ; @5A16 90 57
    ldx #$00                           ; @5A18 A2 00
L5A1A:
    sta $1B                            ; @5A1A 85 1B
    sty $1A                            ; @5A1C 84 1A
    inx                                ; @5A1E E8
    cmp $17                            ; @5A1F C5 17
    bcc L5A2E                          ; @5A21 90 0B
    lda $1A                            ; @5A23 A5 1A
    sbc $16                            ; @5A25 E5 16
    tay                                ; @5A27 A8
    lda $1B                            ; @5A28 A5 1B
    sbc $17                            ; @5A2A E5 17
    bcs L5A1A                          ; @5A2C B0 EC
L5A2E:
    stx $18                            ; @5A2E 86 18
    lda #$00                           ; @5A30 A9 00
    sta $19                            ; @5A32 85 19
    rts                                ; @5A34 60
L5A35:
    lda $16                            ; @5A35 A5 16
    bne L5A42                          ; @5A37 D0 09
    ldx #$03                           ; @5A39 A2 03
L5A3B:
    sta $18,x                          ; @5A3B 95 18
    dex                                ; @5A3D CA
    bpl L5A3B                          ; @5A3E 10 FB
    sec                                ; @5A40 38
    rts                                ; @5A41 60
L5A42:
    lda $14                            ; @5A42 A5 14
    sta $18                            ; @5A44 85 18
    stx $19                            ; @5A46 86 19
    lda #$00                           ; @5A48 A9 00
    sta $1A                            ; @5A4A 85 1A
    sta $1B                            ; @5A4C 85 1B
    ldx #$10                           ; @5A4E A2 10
L5A50:
    asl $18                            ; @5A50 06 18
    rol $19                            ; @5A52 26 19
    rol $1A                            ; @5A54 26 1A
    rol $1B                            ; @5A56 26 1B
    sec                                ; @5A58 38
    lda $1A                            ; @5A59 A5 1A
    sbc $16                            ; @5A5B E5 16
    tay                                ; @5A5D A8
    lda $1B                            ; @5A5E A5 1B
    sbc $17                            ; @5A60 E5 17
    bcc L5A6A                          ; @5A62 90 06
    sta $1B                            ; @5A64 85 1B
    sty $1A                            ; @5A66 84 1A
    inc $18                            ; @5A68 E6 18
L5A6A:
    dex                                ; @5A6A CA
    bne L5A50                          ; @5A6B D0 E3
    clc                                ; @5A6D 18
    rts                                ; @5A6E 60
L5A6F:
    stx $1B                            ; @5A6F 86 1B
    lda $14                            ; @5A71 A5 14
    sta $1A                            ; @5A73 85 1A
    lda #$00                           ; @5A75 A9 00
    sta $18                            ; @5A77 85 18
    sta $19                            ; @5A79 85 19
    rts                                ; @5A7B 60
; ---- executable island $5B00 ----
* = $5B00
L5B00:
    jsr L5A00                          ; @5B00 20 00 5A
    bcc L5B0C                          ; @5B03 90 07
    lda #$00                           ; @5B05 A9 00
    sta $1E                            ; @5B07 85 1E
    sta $1F                            ; @5B09 85 1F
    rts                                ; @5B0B 60
L5B0C:
    lda $1C                            ; @5B0C A5 1C
    sta $1E                            ; @5B0E 85 1E
    lda $1D                            ; @5B10 A5 1D
    sta $1F                            ; @5B12 85 1F
    lda $1B                            ; @5B14 A5 1B
    rol $1E                            ; @5B16 26 1E
    rol $1F                            ; @5B18 26 1F
    rol $1A                            ; @5B1A 26 1A
    rol a                              ; @5B1C 2A
    bcs L5B37                          ; @5B1D B0 18
    cmp $17                            ; @5B1F C5 17
    bcc L5B42                          ; @5B21 90 1F
    bne L5B2B                          ; @5B23 D0 06
    ldy $1A                            ; @5B25 A4 1A
    cpy $16                            ; @5B27 C4 16
    bcc L5B42                          ; @5B29 90 17
L5B2B:
    tay                                ; @5B2B A8
    lda $1A                            ; @5B2C A5 1A
    sbc $16                            ; @5B2E E5 16
    sta $1A                            ; @5B30 85 1A
    tya                                ; @5B32 98
    sbc $17                            ; @5B33 E5 17
    bcs L5B42                          ; @5B35 B0 0B
L5B37:
    tay                                ; @5B37 A8
    lda $1A                            ; @5B38 A5 1A
    sbc $16                            ; @5B3A E5 16
    sta $1A                            ; @5B3C 85 1A
    tya                                ; @5B3E 98
    sbc $17                            ; @5B3F E5 17
    sec                                ; @5B41 38
L5B42:
    ldx #$0F                           ; @5B42 A2 0F
L5B44:
    rol $1E                            ; @5B44 26 1E
    rol $1F                            ; @5B46 26 1F
    rol $1A                            ; @5B48 26 1A
    rol a                              ; @5B4A 2A
    bcs L5B65                          ; @5B4B B0 18
    cmp $17                            ; @5B4D C5 17
    bcc L5B70                          ; @5B4F 90 1F
    bne L5B59                          ; @5B51 D0 06
    ldy $1A                            ; @5B53 A4 1A
    cpy $16                            ; @5B55 C4 16
    bcc L5B70                          ; @5B57 90 17
L5B59:
    tay                                ; @5B59 A8
    lda $1A                            ; @5B5A A5 1A
    sbc $16                            ; @5B5C E5 16
    sta $1A                            ; @5B5E 85 1A
    tya                                ; @5B60 98
    sbc $17                            ; @5B61 E5 17
    bcs L5B70                          ; @5B63 B0 0B
L5B65:
    tay                                ; @5B65 A8
    lda $1A                            ; @5B66 A5 1A
    sbc $16                            ; @5B68 E5 16
    sta $1A                            ; @5B6A 85 1A
    tya                                ; @5B6C 98
    sbc $17                            ; @5B6D E5 17
    sec                                ; @5B6F 38
L5B70:
    dex                                ; @5B70 CA
    bne L5B44                          ; @5B71 D0 D1
    rol $1E                            ; @5B73 26 1E
    rol $1F                            ; @5B75 26 1F
    sta $1B                            ; @5B77 85 1B
    clc                                ; @5B79 18
    rts                                ; @5B7A 60
; ---- executable island $5C00 ----
* = $5C00
L5C00:
    lda $13                            ; @5C00 A5 13
    bmi L5C78                          ; @5C02 30 74
    bne L5C16                          ; @5C04 D0 10
    lda $12                            ; @5C06 A5 12
    bne L5C0D                          ; @5C08 D0 03
    jmp L5CE2                          ; @5C0A 4C E2 5C
L5C0D:
    sta $16                            ; @5C0D 85 16
    lda #$00                           ; @5C0F A9 00
    sta $17                            ; @5C11 85 17
    jmp L5C1C                          ; @5C13 4C 1C 5C
L5C16:
    sta $17                            ; @5C16 85 17
    lda $12                            ; @5C18 A5 12
    sta $16                            ; @5C1A 85 16
L5C1C:
    lda $11                            ; @5C1C A5 11
    bmi L5C34                          ; @5C1E 30 14
    lda $0E                            ; @5C20 A5 0E
    sta $1C                            ; @5C22 85 1C
    lda $0F                            ; @5C24 A5 0F
    sta $1D                            ; @5C26 85 1D
    lda $10                            ; @5C28 A5 10
    sta $14                            ; @5C2A 85 14
    lda $11                            ; @5C2C A5 11
    sta $15                            ; @5C2E 85 15
    jsr L5B00                          ; @5C30 20 00 5B
    rts                                ; @5C33 60
L5C34:
    lda #$00                           ; @5C34 A9 00
    sec                                ; @5C36 38
    sbc $0E                            ; @5C37 E5 0E
    sta $1C                            ; @5C39 85 1C
    lda #$00                           ; @5C3B A9 00
    sbc $0F                            ; @5C3D E5 0F
    sta $1D                            ; @5C3F 85 1D
    lda #$00                           ; @5C41 A9 00
    sbc $10                            ; @5C43 E5 10
    sta $14                            ; @5C45 85 14
    lda #$00                           ; @5C47 A9 00
    sbc $11                            ; @5C49 E5 11
    sta $15                            ; @5C4B 85 15
    jsr L5B00                          ; @5C4D 20 00 5B
    lda #$00                           ; @5C50 A9 00
    sec                                ; @5C52 38
    sbc $1A                            ; @5C53 E5 1A
    sta $1A                            ; @5C55 85 1A
    lda #$00                           ; @5C57 A9 00
    sbc $1B                            ; @5C59 E5 1B
    sta $1B                            ; @5C5B 85 1B
    lda #$00                           ; @5C5D A9 00
    sec                                ; @5C5F 38
    sbc $1E                            ; @5C60 E5 1E
    sta $1E                            ; @5C62 85 1E
    lda #$00                           ; @5C64 A9 00
    sbc $1F                            ; @5C66 E5 1F
    sta $1F                            ; @5C68 85 1F
    lda #$00                           ; @5C6A A9 00
    sbc $18                            ; @5C6C E5 18
    sta $18                            ; @5C6E 85 18
    lda #$00                           ; @5C70 A9 00
    sbc $19                            ; @5C72 E5 19
    sta $19                            ; @5C74 85 19
    clc                                ; @5C76 18
    rts                                ; @5C77 60
L5C78:
    lda #$00                           ; @5C78 A9 00
    sec                                ; @5C7A 38
    sbc $12                            ; @5C7B E5 12
    sta $16                            ; @5C7D 85 16
    lda #$00                           ; @5C7F A9 00
    sbc $13                            ; @5C81 E5 13
    sta $17                            ; @5C83 85 17
    lda $11                            ; @5C85 A5 11
    bmi L5CB7                          ; @5C87 30 2E
    lda $0E                            ; @5C89 A5 0E
    sta $1C                            ; @5C8B 85 1C
    lda $0F                            ; @5C8D A5 0F
    sta $1D                            ; @5C8F 85 1D
    lda $10                            ; @5C91 A5 10
    sta $14                            ; @5C93 85 14
    lda $11                            ; @5C95 A5 11
    sta $15                            ; @5C97 85 15
    jsr L5B00                          ; @5C99 20 00 5B
    lda #$00                           ; @5C9C A9 00
    sec                                ; @5C9E 38
    sbc $1E                            ; @5C9F E5 1E
    sta $1E                            ; @5CA1 85 1E
    lda #$00                           ; @5CA3 A9 00
    sbc $1F                            ; @5CA5 E5 1F
    sta $1F                            ; @5CA7 85 1F
    lda #$00                           ; @5CA9 A9 00
    sbc $18                            ; @5CAB E5 18
    sta $18                            ; @5CAD 85 18
    lda #$00                           ; @5CAF A9 00
    sbc $19                            ; @5CB1 E5 19
    sta $19                            ; @5CB3 85 19
    clc                                ; @5CB5 18
    rts                                ; @5CB6 60
L5CB7:
    lda #$00                           ; @5CB7 A9 00
    sec                                ; @5CB9 38
    sbc $0E                            ; @5CBA E5 0E
    sta $1C                            ; @5CBC 85 1C
    lda #$00                           ; @5CBE A9 00
    sbc $0F                            ; @5CC0 E5 0F
    sta $1D                            ; @5CC2 85 1D
    lda #$00                           ; @5CC4 A9 00
    sbc $10                            ; @5CC6 E5 10
    sta $14                            ; @5CC8 85 14
    lda #$00                           ; @5CCA A9 00
    sbc $11                            ; @5CCC E5 11
    sta $15                            ; @5CCE 85 15
    jsr L5B00                          ; @5CD0 20 00 5B
    lda #$00                           ; @5CD3 A9 00
    sec                                ; @5CD5 38
    sbc $1A                            ; @5CD6 E5 1A
    sta $1A                            ; @5CD8 85 1A
    lda #$00                           ; @5CDA A9 00
    sbc $1B                            ; @5CDC E5 1B
    sta $1B                            ; @5CDE 85 1B
    clc                                ; @5CE0 18
    rts                                ; @5CE1 60
L5CE2:
    sta $16                            ; @5CE2 85 16
    sta $17                            ; @5CE4 85 17
    jmp L5B00                          ; @5CE6 4C 00 5B
