; mul_s24_s24_s48 — exact executable source mirror for v1_balanced
; Legacy API: MATH_SMUL24 at $3BF0
; GENERATED by tools/publish_standalone_sources.py. Do not hand-edit.
; Shipped image: v1_balanced/resident/math_v1_balanced_game_math.prg
; Canonical integrated/relocatable source: relocatable_source/v1_balanced/math_relocatable.asm
; This file contains every executable instruction statically reachable from the public entry after MATH_INIT.
; Shared immutable lookup/data tables and REU payload data are intentionally not duplicated here.
; The address/byte annotations make this a mechanically auditable source view of the shipped executable.
; Reachable instructions: 241.
!cpu 6510

; ---- executable island $3BF0 ----
* = $3BF0
mul_s24_s24_s48:
MATH_SMUL24:
    jmp LCD9C                          ; @3BF0 4C 9C CD
; ---- executable island $CC00 ----
* = $CC00
LCC00:
    clc                                ; @CC00 18
    adc ($13),y                        ; @CC01 71 13
    sta $CCEE                          ; @CC03 8D EE CC
    lda #$01                           ; @CC06 A9 01
    adc ($15),y                        ; @CC08 71 15
    adc ($17),y                        ; @CC0A 71 17
    adc ($19),y                        ; @CC0C 71 19
    bcc LCC73                          ; @CC0E 90 63
LCC10:
    clc                                ; @CC10 18
    adc ($1B),y                        ; @CC11 71 1B
    sta $CCF3                          ; @CC13 8D F3 CC
    lda #$01                           ; @CC16 A9 01
    adc ($1D),y                        ; @CC18 71 1D
    bcc LCC7A                          ; @CC1A 90 5E
LCC1C:
    clc                                ; @CC1C 18
    adc ($13),y                        ; @CC1D 71 13
    sta $CCDA                          ; @CC1F 8D DA CC
    lda #$01                           ; @CC22 A9 01
    adc ($15),y                        ; @CC24 71 15
    adc ($17),y                        ; @CC26 71 17
    adc ($19),y                        ; @CC28 71 19
    bcc LCC9B                          ; @CC2A 90 6F
LCC2C:
    clc                                ; @CC2C 18
    adc ($1B),y                        ; @CC2D 71 1B
    sta $CCE6                          ; @CC2F 8D E6 CC
    lda #$01                           ; @CC32 A9 01
    adc ($1D),y                        ; @CC34 71 1D
    bcc LCCA2                          ; @CC36 90 6A
LCC38:
    lda $09                            ; @CC38 A5 09
    sta $0D                            ; @CC3A 85 0D
    eor #$FF                           ; @CC3C 49 FF
    sta $0B                            ; @CC3E 85 0B
    sta $0F                            ; @CC40 85 0F
    lda $11                            ; @CC42 A5 11
    sta $15                            ; @CC44 85 15
    eor #$FF                           ; @CC46 49 FF
    sta $13                            ; @CC48 85 13
    sta $17                            ; @CC4A 85 17
    lda $19                            ; @CC4C A5 19
    sta $1D                            ; @CC4E 85 1D
    eor #$FF                           ; @CC50 49 FF
    sta $1B                            ; @CC52 85 1B
    sta $1F                            ; @CC54 85 1F
LCC56:
    sec                                ; @CC56 38
    lda ($09),y                        ; @CC57 B1 09
    adc ($0B),y                        ; @CC59 71 0B
    sta $CCE0                          ; @CC5B 8D E0 CC
    lda ($0D),y                        ; @CC5E B1 0D
    adc ($0F),y                        ; @CC60 71 0F
    adc ($11),y                        ; @CC62 71 11
    bcs LCC00                          ; @CC64 B0 9A
    adc ($13),y                        ; @CC66 71 13
    sta $CCEE                          ; @CC68 8D EE CC
    lda ($15),y                        ; @CC6B B1 15
    adc ($17),y                        ; @CC6D 71 17
    adc ($19),y                        ; @CC6F 71 19
    bcs LCC10                          ; @CC71 B0 9D
LCC73:
    adc ($1B),y                        ; @CC73 71 1B
    sta $CCF3                          ; @CC75 8D F3 CC
    lda ($1D),y                        ; @CC78 B1 1D
LCC7A:
    adc ($1F),y                        ; @CC7A 71 1F
    tax                                ; @CC7C AA
    ldy #$00                           ; @CC7D A0 00
    lda ($09),y                        ; @CC7F B1 09
    adc ($0B),y                        ; @CC81 71 0B
    sta $CCD3                          ; @CC83 8D D3 CC
    lda ($0D),y                        ; @CC86 B1 0D
    adc ($0F),y                        ; @CC88 71 0F
    adc ($11),y                        ; @CC8A 71 11
    bcs LCC1C                          ; @CC8C B0 8E
    adc ($13),y                        ; @CC8E 71 13
    sta $CCDA                          ; @CC90 8D DA CC
    lda ($15),y                        ; @CC93 B1 15
    adc ($17),y                        ; @CC95 71 17
    adc ($19),y                        ; @CC97 71 19
    bcs LCC2C                          ; @CC99 B0 91
LCC9B:
    adc ($1B),y                        ; @CC9B 71 1B
    sta $CCE6                          ; @CC9D 8D E6 CC
    lda ($1D),y                        ; @CCA0 B1 1D
LCCA2:
    adc ($1F),y                        ; @CCA2 71 1F
    sta $CCF1                          ; @CCA4 8D F1 CC
    ldy #$00                           ; @CCA7 A0 00
    lda ($09),y                        ; @CCA9 B1 09
    adc ($0B),y                        ; @CCAB 71 0B
    sta $C008                          ; @CCAD 8D 08 C0
    lda ($0D),y                        ; @CCB0 B1 0D
    adc ($0F),y                        ; @CCB2 71 0F
    adc ($11),y                        ; @CCB4 71 11
    bcs LCCF9                          ; @CCB6 B0 41
    adc ($13),y                        ; @CCB8 71 13
    sta $CCD1                          ; @CCBA 8D D1 CC
    lda ($15),y                        ; @CCBD B1 15
    adc ($17),y                        ; @CCBF 71 17
    adc ($19),y                        ; @CCC1 71 19
    bcs LCD09                          ; @CCC3 B0 44
LCCC5:
    adc ($1B),y                        ; @CCC5 71 1B
    sta $CCD8                          ; @CCC7 8D D8 CC
    lda ($1D),y                        ; @CCCA B1 1D
LCCCC:
    adc ($1F),y                        ; @CCCC 71 1F
    tay                                ; @CCCE A8
    clc                                ; @CCCF 18
    lda #$00                           ; @CCD0 A9 00
    adc #$00                           ; @CCD2 69 00
    sta $C009                          ; @CCD4 8D 09 C0
    lda #$00                           ; @CCD7 A9 00
    adc #$00                           ; @CCD9 69 00
    bcc LCCDF                          ; @CCDB 90 02
    iny                                ; @CCDD C8
    clc                                ; @CCDE 18
LCCDF:
    adc #$00                           ; @CCDF 69 00
    sta $C00A                          ; @CCE1 8D 0A C0
    tya                                ; @CCE4 98
    adc #$00                           ; @CCE5 69 00
    bcc LCCED                          ; @CCE7 90 04
    clc                                ; @CCE9 18
    inc $CCF1                          ; @CCEA EE F1 CC
LCCED:
    adc #$00                           ; @CCED 69 00
    tay                                ; @CCEF A8
    lda #$00                           ; @CCF0 A9 00
    adc #$00                           ; @CCF2 69 00
    bcs LCCF7                          ; @CCF4 B0 01
    rts                                ; @CCF6 60
LCCF7:
    inx                                ; @CCF7 E8
    rts                                ; @CCF8 60
LCCF9:
    clc                                ; @CCF9 18
    adc ($13),y                        ; @CCFA 71 13
    sta $CCD1                          ; @CCFC 8D D1 CC
    lda #$01                           ; @CCFF A9 01
    adc ($15),y                        ; @CD01 71 15
    adc ($17),y                        ; @CD03 71 17
    adc ($19),y                        ; @CD05 71 19
    bcc LCCC5                          ; @CD07 90 BC
LCD09:
    clc                                ; @CD09 18
    adc ($1B),y                        ; @CD0A 71 1B
    sta $CCD8                          ; @CD0C 8D D8 CC
    lda #$01                           ; @CD0F A9 01
    adc ($1D),y                        ; @CD11 71 1D
    bcc LCCCC                          ; @CD13 90 B7
LCD15:
    lda $19                            ; @CD15 A5 19
    bmi LCD1F                          ; @CD17 30 06
    tya                                ; @CD19 98
    bmi LCD3E                          ; @CD1A 30 22
    jmp LCC38                          ; @CD1C 4C 38 CC
LCD1F:
    tya                                ; @CD1F 98
    bmi LCD57                          ; @CD20 30 35
    jsr LCC38                          ; @CD22 20 38 CC
    sta $CD2F                          ; @CD25 8D 2F CD
    tya                                ; @CD28 98
    sec                                ; @CD29 38
    sbc $CCA8                          ; @CD2A ED A8 CC
    tay                                ; @CD2D A8
    lda #$00                           ; @CD2E A9 00
    sbc $CC7E                          ; @CD30 ED 7E CC
    sta $CD3C                          ; @CD33 8D 3C CD
    txa                                ; @CD36 8A
    sbc $C006                          ; @CD37 ED 06 C0
    tax                                ; @CD3A AA
    lda #$00                           ; @CD3B A9 00
    rts                                ; @CD3D 60
LCD3E:
    jsr LCC38                          ; @CD3E 20 38 CC
    sta $CD4A                          ; @CD41 8D 4A CD
    tya                                ; @CD44 98
    sec                                ; @CD45 38
    sbc $09                            ; @CD46 E5 09
    tay                                ; @CD48 A8
    lda #$00                           ; @CD49 A9 00
    sbc $11                            ; @CD4B E5 11
    sta $CD55                          ; @CD4D 8D 55 CD
    txa                                ; @CD50 8A
    sbc $19                            ; @CD51 E5 19
    tax                                ; @CD53 AA
    lda #$00                           ; @CD54 A9 00
    rts                                ; @CD56 60
LCD57:
    sec                                ; @CD57 38
    lda #$00                           ; @CD58 A9 00
    sbc $CCA8                          ; @CD5A ED A8 CC
    sta $CCA8                          ; @CD5D 8D A8 CC
    lda #$00                           ; @CD60 A9 00
    sbc $CC7E                          ; @CD62 ED 7E CC
    sta $CC7E                          ; @CD65 8D 7E CC
    tya                                ; @CD68 98
    eor #$FF                           ; @CD69 49 FF
    adc #$00                           ; @CD6B 69 00
    tay                                ; @CD6D A8
    sec                                ; @CD6E 38
    lda #$00                           ; @CD6F A9 00
    sbc $09                            ; @CD71 E5 09
    sta $09                            ; @CD73 85 09
    sta $0D                            ; @CD75 85 0D
    eor #$FF                           ; @CD77 49 FF
    sta $0B                            ; @CD79 85 0B
    sta $0F                            ; @CD7B 85 0F
    lda #$00                           ; @CD7D A9 00
    sbc $11                            ; @CD7F E5 11
    sta $11                            ; @CD81 85 11
    sta $15                            ; @CD83 85 15
    eor #$FF                           ; @CD85 49 FF
    sta $13                            ; @CD87 85 13
    sta $17                            ; @CD89 85 17
    lda #$00                           ; @CD8B A9 00
    sbc $19                            ; @CD8D E5 19
    sta $19                            ; @CD8F 85 19
    sta $1D                            ; @CD91 85 1D
    eor #$FF                           ; @CD93 49 FF
    sta $1B                            ; @CD95 85 1B
    sta $1F                            ; @CD97 85 1F
    jmp LCC56                          ; @CD99 4C 56 CC
LCD9C:
    lda #$84                           ; @CD9C A9 84
    sta $0A                            ; @CD9E 85 0A
    sta $12                            ; @CDA0 85 12
    sta $1A                            ; @CDA2 85 1A
    lda #$88                           ; @CDA4 A9 88
    sta $0C                            ; @CDA6 85 0C
    sta $14                            ; @CDA8 85 14
    sta $1C                            ; @CDAA 85 1C
    lda #$86                           ; @CDAC A9 86
    sta $0E                            ; @CDAE 85 0E
    sta $16                            ; @CDB0 85 16
    sta $1E                            ; @CDB2 85 1E
    lda #$8A                           ; @CDB4 A9 8A
    sta $10                            ; @CDB6 85 10
    sta $18                            ; @CDB8 85 18
    sta $20                            ; @CDBA 85 20
    lda $C000                          ; @CDBC AD 00 C0
    sta $09                            ; @CDBF 85 09
    lda $C001                          ; @CDC1 AD 01 C0
    sta $11                            ; @CDC4 85 11
    lda $C002                          ; @CDC6 AD 02 C0
    sta $19                            ; @CDC9 85 19
    lda $C004                          ; @CDCB AD 04 C0
    sta $CCA8                          ; @CDCE 8D A8 CC
    lda $C005                          ; @CDD1 AD 05 C0
    sta $CC7E                          ; @CDD4 8D 7E CC
    ldy $C006                          ; @CDD7 AC 06 C0
    jsr LCD15                          ; @CDDA 20 15 CD
    sta $C00C                          ; @CDDD 8D 0C C0
    stx $C00D                          ; @CDE0 8E 0D C0
    sty $C00B                          ; @CDE3 8C 0B C0
    clc                                ; @CDE6 18
    rts                                ; @CDE7 60
