; MATH_SMUL32 — exact native-signed executable source mirror for v2_pareto_fast
; GENERATED by tools/publish_native_signed_sources.py. Do not hand-edit.
; Canonical integrated build source remains relocatable_source/v2_pareto_fast/math_relocatable.asm
; This mirror contains every executable instruction reachable from this signed API after MATH_INIT.
; Immutable lookup/data tables are intentionally not duplicated here.
; Corresponding unsigned API: MATH_UMUL32. Executable overlap: 0 instructions.
; Public entry: $3C40. Reachable signed instructions: 633.
; Each instruction has an @ADDR byte annotation used by the publication validator.
!cpu 6510

; ---- executable island $2300 ----
* = $2300
L2300:
    sta $68                            ; @2300 85 68
    sta $5556                          ; @2302 8D 56 55
    eor #$FF                           ; @2305 49 FF
    sta $51                            ; @2307 85 51
    sta $5561                          ; @2309 8D 61 55
    lda $C000                          ; @230C AD 00 C0
    sta $552C                          ; @230F 8D 2C 55
    sta $5534                          ; @2312 8D 34 55
    eor #$FF                           ; @2315 49 FF
    sta $552F                          ; @2317 8D 2F 55
    sta $5537                          ; @231A 8D 37 55
    lda $C001                          ; @231D AD 01 C0
    sta $3F                            ; @2320 85 3F
    sta $553A                          ; @2322 8D 3A 55
    eor #$FF                           ; @2325 49 FF
    sta $3D                            ; @2327 85 3D
    sta $5545                          ; @2329 8D 45 55
    lda $C002                          ; @232C AD 02 C0
    sta $4F                            ; @232F 85 4F
    sta $5548                          ; @2331 8D 48 55
    eor #$FF                           ; @2334 49 FF
    sta $41                            ; @2336 85 41
    sta $5553                          ; @2338 8D 53 55
    ldx #$03                           ; @233B A2 03
    sec                                ; @233D 38
    jmp L552B                          ; @233E 4C 2B 55
L2341:
    lda #$00                           ; @2341 A9 00
    sbc $C001                          ; @2343 ED 01 C0
    sta $3F                            ; @2346 85 3F
    sta $CA6B                          ; @2348 8D 6B CA
    eor #$FF                           ; @234B 49 FF
    sta $3D                            ; @234D 85 3D
    sta $CA76                          ; @234F 8D 76 CA
    lda #$00                           ; @2352 A9 00
    sbc $C002                          ; @2354 ED 02 C0
    sta $4F                            ; @2357 85 4F
    sta $CA79                          ; @2359 8D 79 CA
    eor #$FF                           ; @235C 49 FF
    sta $41                            ; @235E 85 41
    sta $CA84                          ; @2360 8D 84 CA
    lda #$00                           ; @2363 A9 00
    sbc $C003                          ; @2365 ED 03 C0
    sta $68                            ; @2368 85 68
    sta $CA87                          ; @236A 8D 87 CA
    eor #$FF                           ; @236D 49 FF
    sta $51                            ; @236F 85 51
    sta $CA92                          ; @2371 8D 92 CA
    jmp L3CE9                          ; @2374 4C E9 3C
; ---- executable island $3505 ----
* = $3505
L3505:
    clc                                ; @3505 18
    adc ($3D),y                        ; @3506 71 3D
    sta $1D,x                          ; @3508 95 1D
    lda #$01                           ; @350A A9 01
    adc ($3F),y                        ; @350C 71 3F
    bcc L3544                          ; @350E 90 34
L3510:
    clc                                ; @3510 18
    adc ($41),y                        ; @3511 71 41
    sta $12,x                          ; @3513 95 12
    lda #$01                           ; @3515 A9 01
    adc ($4F),y                        ; @3517 71 4F
    bcc L3552                          ; @3519 90 37
L351B:
    clc                                ; @351B 18
    adc ($51),y                        ; @351C 71 51
    sta $16,x                          ; @351E 95 16
    lda #$01                           ; @3520 A9 01
    adc ($68),y                        ; @3522 71 68
    bcc L3560                          ; @3524 90 3A
L3526:
    sta $1A,x                          ; @3526 95 1A
    ldy $C004,x                        ; @3528 BC 04 C0
L352B:
    lda $7000,y                        ; @352B B9 00 70
    adc $7400,y                        ; @352E 79 00 74
    sta $0E,x                          ; @3531 95 0E
    lda $7200,y                        ; @3533 B9 00 72
    adc $7600,y                        ; @3536 79 00 76
    adc $7000,y                        ; @3539 79 00 70
    bcs L3505                          ; @353C B0 C7
    adc ($3D),y                        ; @353E 71 3D
    sta $1D,x                          ; @3540 95 1D
    lda ($3F),y                        ; @3542 B1 3F
L3544:
    adc $7600,y                        ; @3544 79 00 76
    adc $7000,y                        ; @3547 79 00 70
    bcs L3510                          ; @354A B0 C4
    adc ($41),y                        ; @354C 71 41
    sta $12,x                          ; @354E 95 12
    lda ($4F),y                        ; @3550 B1 4F
L3552:
    adc $7600,y                        ; @3552 79 00 76
    adc $7000,y                        ; @3555 79 00 70
    bcs L351B                          ; @3558 B0 C1
    adc ($51),y                        ; @355A 71 51
    sta $16,x                          ; @355C 95 16
    lda ($68),y                        ; @355E B1 68
L3560:
    adc $7600,y                        ; @3560 79 00 76
    dex                                ; @3563 CA
    bpl L3526                          ; @3564 10 C0
    tax                                ; @3566 AA
    ldy $1A                            ; @3567 A4 1A
    clc                                ; @3569 18
    lda $1D                            ; @356A A5 1D
    adc $0F                            ; @356C 65 0F
    sta $C009                          ; @356E 8D 09 C0
    lda $1E                            ; @3571 A5 1E
    adc $10                            ; @3573 65 10
    bcc L357C                          ; @3575 90 05
    inc $11                            ; @3577 E6 11
    beq L35CD                          ; @3579 F0 52
    clc                                ; @357B 18
L357C:
    adc $12                            ; @357C 65 12
    sta $C00A                          ; @357E 8D 0A C0
    lda $13                            ; @3581 A5 13
    adc $16                            ; @3583 65 16
    bcc L3589                          ; @3585 90 02
    inx                                ; @3587 E8
    clc                                ; @3588 18
L3589:
    adc $11                            ; @3589 65 11
    bcc L358F                          ; @358B 90 02
    inx                                ; @358D E8
    clc                                ; @358E 18
L358F:
    adc $1F                            ; @358F 65 1F
    sta $C00B                          ; @3591 8D 0B C0
    txa                                ; @3594 8A
    adc $17                            ; @3595 65 17
    bcs L35C2                          ; @3597 B0 29
L3599:
    adc $20                            ; @3599 65 20
    bcc L359F                          ; @359B 90 02
    iny                                ; @359D C8
    clc                                ; @359E 18
L359F:
    adc $14                            ; @359F 65 14
    sta $C00C                          ; @35A1 8D 0C C0
    tya                                ; @35A4 98
    adc $15                            ; @35A5 65 15
    bcs L35C7                          ; @35A7 B0 1E
L35A9:
    adc $18                            ; @35A9 65 18
    sta $C00D                          ; @35AB 8D 0D C0
    lda $19                            ; @35AE A5 19
    adc $1B                            ; @35B0 65 1B
    sta $C00E                          ; @35B2 8D 0E C0
    lda $1C                            ; @35B5 A5 1C
    adc #$00                           ; @35B7 69 00
    sta $C00F                          ; @35B9 8D 0F C0
    lda $0E                            ; @35BC A5 0E
    sta $C008                          ; @35BE 8D 08 C0
    rts                                ; @35C1 60
L35C2:
    iny                                ; @35C2 C8
    clc                                ; @35C3 18
    jmp L3599                          ; @35C4 4C 99 35
L35C7:
    inc $1B                            ; @35C7 E6 1B
    clc                                ; @35C9 18
    jmp L35A9                          ; @35CA 4C A9 35
L35CD:
    jmp L35D3                          ; @35CD 4C D3 35
; ---- executable island $35D3 ----
* = $35D3
L35D3:
    inc $20                            ; @35D3 E6 20
    bne L35E1                          ; @35D5 D0 0A
    inc $15                            ; @35D7 E6 15
    bne L35E1                          ; @35D9 D0 06
    inc $19                            ; @35DB E6 19
    bne L35E1                          ; @35DD D0 02
    inc $1C                            ; @35DF E6 1C
L35E1:
    clc                                ; @35E1 18
    jmp L357C                          ; @35E2 4C 7C 35
; ---- executable island $3981 ----
* = $3981
L3981:
    clc                                ; @3981 18
    adc ($3D),y                        ; @3982 71 3D
    sta $1D,x                          ; @3984 95 1D
    lda #$01                           ; @3986 A9 01
    adc ($3F),y                        ; @3988 71 3F
    bcc L39C0                          ; @398A 90 34
L398C:
    clc                                ; @398C 18
    adc ($41),y                        ; @398D 71 41
    sta $12,x                          ; @398F 95 12
    lda #$01                           ; @3991 A9 01
    adc ($4F),y                        ; @3993 71 4F
    bcc L39CE                          ; @3995 90 37
L3997:
    clc                                ; @3997 18
    adc ($51),y                        ; @3998 71 51
    sta $16,x                          ; @399A 95 16
    lda #$01                           ; @399C A9 01
    adc ($68),y                        ; @399E 71 68
    bcc L39DC                          ; @39A0 90 3A
L39A2:
    sta $1A,x                          ; @39A2 95 1A
    ldy $C004,x                        ; @39A4 BC 04 C0
L39A7:
    lda $7000,y                        ; @39A7 B9 00 70
    adc $7400,y                        ; @39AA 79 00 74
    sta $0E,x                          ; @39AD 95 0E
    lda $7200,y                        ; @39AF B9 00 72
    adc $7600,y                        ; @39B2 79 00 76
    adc $7000,y                        ; @39B5 79 00 70
    bcs L3981                          ; @39B8 B0 C7
    adc ($3D),y                        ; @39BA 71 3D
    sta $1D,x                          ; @39BC 95 1D
    lda ($3F),y                        ; @39BE B1 3F
L39C0:
    adc $7600,y                        ; @39C0 79 00 76
    adc $7000,y                        ; @39C3 79 00 70
    bcs L398C                          ; @39C6 B0 C4
    adc ($41),y                        ; @39C8 71 41
    sta $12,x                          ; @39CA 95 12
    lda ($4F),y                        ; @39CC B1 4F
L39CE:
    adc $7600,y                        ; @39CE 79 00 76
    adc $7000,y                        ; @39D1 79 00 70
    bcs L3997                          ; @39D4 B0 C1
    adc ($51),y                        ; @39D6 71 51
    sta $16,x                          ; @39D8 95 16
    lda ($68),y                        ; @39DA B1 68
L39DC:
    adc $7600,y                        ; @39DC 79 00 76
    dex                                ; @39DF CA
    bpl L39A2                          ; @39E0 10 C0
    tax                                ; @39E2 AA
    ldy $1A                            ; @39E3 A4 1A
    clc                                ; @39E5 18
    lda $1D                            ; @39E6 A5 1D
    adc $0F                            ; @39E8 65 0F
    sta $C009                          ; @39EA 8D 09 C0
    lda $1E                            ; @39ED A5 1E
    adc $10                            ; @39EF 65 10
    bcc L39F8                          ; @39F1 90 05
    inc $11                            ; @39F3 E6 11
    beq L3A61                          ; @39F5 F0 6A
    clc                                ; @39F7 18
L39F8:
    adc $12                            ; @39F8 65 12
    sta $C00A                          ; @39FA 8D 0A C0
    lda $13                            ; @39FD A5 13
    adc $16                            ; @39FF 65 16
    bcc L3A05                          ; @3A01 90 02
    inx                                ; @3A03 E8
    clc                                ; @3A04 18
L3A05:
    adc $11                            ; @3A05 65 11
    bcc L3A0B                          ; @3A07 90 02
    inx                                ; @3A09 E8
    clc                                ; @3A0A 18
L3A0B:
    adc $1F                            ; @3A0B 65 1F
    sta $C00B                          ; @3A0D 8D 0B C0
    txa                                ; @3A10 8A
    adc $17                            ; @3A11 65 17
    bcs L3A51                          ; @3A13 B0 3C
L3A15:
    adc $20                            ; @3A15 65 20
    bcc L3A1B                          ; @3A17 90 02
    iny                                ; @3A19 C8
    clc                                ; @3A1A 18
L3A1B:
    adc $14                            ; @3A1B 65 14
    tax                                ; @3A1D AA
    tya                                ; @3A1E 98
    adc $15                            ; @3A1F 65 15
    bcs L3A56                          ; @3A21 B0 33
L3A23:
    adc $18                            ; @3A23 65 18
    tay                                ; @3A25 A8
    lda $19                            ; @3A26 A5 19
    adc $1B                            ; @3A28 65 1B
    bcs L3A5C                          ; @3A2A B0 30
L3A2C:
    sta $19                            ; @3A2C 85 19
    txa                                ; @3A2E 8A
    sec                                ; @3A2F 38
    sbc $C000                          ; @3A30 ED 00 C0
    sta $C00C                          ; @3A33 8D 0C C0
    tya                                ; @3A36 98
    sbc $3F                            ; @3A37 E5 3F
    sta $C00D                          ; @3A39 8D 0D C0
    lda $19                            ; @3A3C A5 19
    sbc $4F                            ; @3A3E E5 4F
    sta $C00E                          ; @3A40 8D 0E C0
    lda $1C                            ; @3A43 A5 1C
    sbc $68                            ; @3A45 E5 68
    sta $C00F                          ; @3A47 8D 0F C0
    lda $0E                            ; @3A4A A5 0E
    sta $C008                          ; @3A4C 8D 08 C0
    clc                                ; @3A4F 18
    rts                                ; @3A50 60
L3A51:
    iny                                ; @3A51 C8
    clc                                ; @3A52 18
    jmp L3A15                          ; @3A53 4C 15 3A
L3A56:
    inc $1B                            ; @3A56 E6 1B
    clc                                ; @3A58 18
    jmp L3A23                          ; @3A59 4C 23 3A
L3A5C:
    inc $1C                            ; @3A5C E6 1C
    jmp L3A2C                          ; @3A5E 4C 2C 3A
L3A61:
    jmp L3A67                          ; @3A61 4C 67 3A
; ---- executable island $3A67 ----
* = $3A67
L3A67:
    inc $20                            ; @3A67 E6 20
    bne L3A75                          ; @3A69 D0 0A
    inc $15                            ; @3A6B E6 15
    bne L3A75                          ; @3A6D D0 06
    inc $19                            ; @3A6F E6 19
    bne L3A75                          ; @3A71 D0 02
    inc $1C                            ; @3A73 E6 1C
L3A75:
    clc                                ; @3A75 18
    jmp L39F8                          ; @3A76 4C F8 39
; ---- executable island $3C00 ----
* = $3C00
L3C00:
    sta $68                            ; @3C00 85 68
    sta $39D2                          ; @3C02 8D D2 39
    eor #$FF                           ; @3C05 49 FF
    sta $51                            ; @3C07 85 51
    sta $39DD                          ; @3C09 8D DD 39
    lda $C000                          ; @3C0C AD 00 C0
    sta $39A8                          ; @3C0F 8D A8 39
    sta $39B0                          ; @3C12 8D B0 39
    eor #$FF                           ; @3C15 49 FF
    sta $39AB                          ; @3C17 8D AB 39
    sta $39B3                          ; @3C1A 8D B3 39
    lda $C001                          ; @3C1D AD 01 C0
    sta $3F                            ; @3C20 85 3F
    sta $39B6                          ; @3C22 8D B6 39
    eor #$FF                           ; @3C25 49 FF
    sta $3D                            ; @3C27 85 3D
    sta $39C1                          ; @3C29 8D C1 39
    lda $C002                          ; @3C2C AD 02 C0
    sta $4F                            ; @3C2F 85 4F
    sta $39C4                          ; @3C31 8D C4 39
    eor #$FF                           ; @3C34 49 FF
    sta $41                            ; @3C36 85 41
    sta $39CF                          ; @3C38 8D CF 39
    jmp L39A7                          ; @3C3B 4C A7 39
; ---- executable island $3C40 ----
* = $3C40
L3C40:
    lda $C003                          ; @3C40 AD 03 C0
    bpl L3C4D                          ; @3C43 10 08
    ldy $C007                          ; @3C45 AC 07 C0
    bmi L3CA6                          ; @3C48 30 5C
    jmp L2300                          ; @3C4A 4C 00 23
L3C4D:
    ldx #$03                           ; @3C4D A2 03
    sec                                ; @3C4F 38
    ldy $C007                          ; @3C50 AC 07 C0
    bmi L3C00                          ; @3C53 30 AB
    sta $68                            ; @3C55 85 68
    sta $3556                          ; @3C57 8D 56 35
    eor #$FF                           ; @3C5A 49 FF
    sta $51                            ; @3C5C 85 51
    sta $3561                          ; @3C5E 8D 61 35
    lda $C000                          ; @3C61 AD 00 C0
    sta $352C                          ; @3C64 8D 2C 35
    sta $3534                          ; @3C67 8D 34 35
    eor #$FF                           ; @3C6A 49 FF
    sta $352F                          ; @3C6C 8D 2F 35
    sta $3537                          ; @3C6F 8D 37 35
    lda $C001                          ; @3C72 AD 01 C0
    sta $3F                            ; @3C75 85 3F
    sta $353A                          ; @3C77 8D 3A 35
    eor #$FF                           ; @3C7A 49 FF
    sta $3D                            ; @3C7C 85 3D
    sta $3545                          ; @3C7E 8D 45 35
    lda $C002                          ; @3C81 AD 02 C0
    sta $4F                            ; @3C84 85 4F
    sta $3548                          ; @3C86 8D 48 35
    eor #$FF                           ; @3C89 49 FF
    sta $41                            ; @3C8B 85 41
    sta $3553                          ; @3C8D 8D 53 35
    jmp L352B                          ; @3C90 4C 2B 35
; ---- executable island $3CA3 ----
* = $3CA3
L3CA3:
    jmp L2341                          ; @3CA3 4C 41 23
L3CA6:
    sec                                ; @3CA6 38
    lda #$00                           ; @3CA7 A9 00
    sbc $C000                          ; @3CA9 ED 00 C0
    sta $CA5D                          ; @3CAC 8D 5D CA
    sta $CA65                          ; @3CAF 8D 65 CA
    eor #$FF                           ; @3CB2 49 FF
    sta $CA60                          ; @3CB4 8D 60 CA
    sta $CA68                          ; @3CB7 8D 68 CA
    bcs L3CA3                          ; @3CBA B0 E7
    lda $C001                          ; @3CBC AD 01 C0
    sta $3D                            ; @3CBF 85 3D
    sta $CA76                          ; @3CC1 8D 76 CA
    eor #$FF                           ; @3CC4 49 FF
    sta $3F                            ; @3CC6 85 3F
    sta $CA6B                          ; @3CC8 8D 6B CA
    lda $C002                          ; @3CCB AD 02 C0
    sta $41                            ; @3CCE 85 41
    sta $CA84                          ; @3CD0 8D 84 CA
    eor #$FF                           ; @3CD3 49 FF
    sta $4F                            ; @3CD5 85 4F
    sta $CA79                          ; @3CD7 8D 79 CA
    lda $C003                          ; @3CDA AD 03 C0
    sta $51                            ; @3CDD 85 51
    sta $CA92                          ; @3CDF 8D 92 CA
    eor #$FF                           ; @3CE2 49 FF
    sta $68                            ; @3CE4 85 68
    sta $CA87                          ; @3CE6 8D 87 CA
L3CE9:
    sec                                ; @3CE9 38
    lda #$00                           ; @3CEA A9 00
    sbc $C004                          ; @3CEC ED 04 C0
    sta $0E                            ; @3CEF 85 0E
    lda #$00                           ; @3CF1 A9 00
    sbc $C005                          ; @3CF3 ED 05 C0
    sta $0F                            ; @3CF6 85 0F
    lda #$00                           ; @3CF8 A9 00
    sbc $C006                          ; @3CFA ED 06 C0
    sta $10                            ; @3CFD 85 10
    lda #$00                           ; @3CFF A9 00
    sbc $C007                          ; @3D01 ED 07 C0
    tay                                ; @3D04 A8
    ldx #$03                           ; @3D05 A2 03
    sec                                ; @3D07 38
    jmp LCA5C                          ; @3D08 4C 5C CA
; ---- executable island $5505 ----
* = $5505
L5505:
    clc                                ; @5505 18
    adc ($3D),y                        ; @5506 71 3D
    sta $1D,x                          ; @5508 95 1D
    lda #$01                           ; @550A A9 01
    adc ($3F),y                        ; @550C 71 3F
    bcc L5544                          ; @550E 90 34
L5510:
    clc                                ; @5510 18
    adc ($41),y                        ; @5511 71 41
    sta $12,x                          ; @5513 95 12
    lda #$01                           ; @5515 A9 01
    adc ($4F),y                        ; @5517 71 4F
    bcc L5552                          ; @5519 90 37
L551B:
    clc                                ; @551B 18
    adc ($51),y                        ; @551C 71 51
    sta $16,x                          ; @551E 95 16
    lda #$01                           ; @5520 A9 01
    adc ($68),y                        ; @5522 71 68
    bcc L5560                          ; @5524 90 3A
L5526:
    sta $1A,x                          ; @5526 95 1A
    ldy $C004,x                        ; @5528 BC 04 C0
L552B:
    lda $7000,y                        ; @552B B9 00 70
    adc $7400,y                        ; @552E 79 00 74
    sta $0E,x                          ; @5531 95 0E
    lda $7200,y                        ; @5533 B9 00 72
    adc $7600,y                        ; @5536 79 00 76
    adc $7000,y                        ; @5539 79 00 70
    bcs L5505                          ; @553C B0 C7
    adc ($3D),y                        ; @553E 71 3D
    sta $1D,x                          ; @5540 95 1D
    lda ($3F),y                        ; @5542 B1 3F
L5544:
    adc $7600,y                        ; @5544 79 00 76
    adc $7000,y                        ; @5547 79 00 70
    bcs L5510                          ; @554A B0 C4
    adc ($41),y                        ; @554C 71 41
    sta $12,x                          ; @554E 95 12
    lda ($4F),y                        ; @5550 B1 4F
L5552:
    adc $7600,y                        ; @5552 79 00 76
    adc $7000,y                        ; @5555 79 00 70
    bcs L551B                          ; @5558 B0 C1
    adc ($51),y                        ; @555A 71 51
    sta $16,x                          ; @555C 95 16
    lda ($68),y                        ; @555E B1 68
L5560:
    adc $7600,y                        ; @5560 79 00 76
    dex                                ; @5563 CA
    bpl L5526                          ; @5564 10 C0
    inx                                ; @5566 E8
    tay                                ; @5567 A8
    clc                                ; @5568 18
    lda $1D                            ; @5569 A5 1D
    adc $0F                            ; @556B 65 0F
    sta $C009                          ; @556D 8D 09 C0
    lda $10                            ; @5570 A5 10
    adc $1E                            ; @5572 65 1E
    bcc L5578                          ; @5574 90 02
    inx                                ; @5576 E8
    clc                                ; @5577 18
L5578:
    adc $12                            ; @5578 65 12
    sta $C00A                          ; @557A 8D 0A C0
    lda $16                            ; @557D A5 16
    adc $13                            ; @557F 65 13
    bcc L5591                          ; @5581 90 0E
    iny                                ; @5583 C8
    cpx #$01                           ; @5584 E0 01
    adc $11                            ; @5586 65 11
    bcc L5598                          ; @5588 90 0E
    clc                                ; @558A 18
    iny                                ; @558B C8
    bne L5598                          ; @558C D0 0A
    jmp L5616                          ; @558E 4C 16 56
L5591:
    adc $11                            ; @5591 65 11
    bcc L5596                          ; @5593 90 01
    iny                                ; @5595 C8
L5596:
    cpx #$01                           ; @5596 E0 01
L5598:
    adc $1F                            ; @5598 65 1F
    sta $C00B                          ; @559A 8D 0B C0
    tya                                ; @559D 98
    adc $14                            ; @559E 65 14
    bcs L55F8                          ; @55A0 B0 56
    adc $20                            ; @55A2 65 20
    bcs L55FF                          ; @55A4 B0 59
    adc $17                            ; @55A6 65 17
    tay                                ; @55A8 A8
    lda $1A                            ; @55A9 A5 1A
    adc $15                            ; @55AB 65 15
    bcs L55E2                          ; @55AD B0 33
    adc $18                            ; @55AF 65 18
    tax                                ; @55B1 AA
    lda $1B                            ; @55B2 A5 1B
    adc $19                            ; @55B4 65 19
    bcc L55BA                          ; @55B6 90 02
L55B8:
    inc $1C                            ; @55B8 E6 1C
L55BA:
    sta $19                            ; @55BA 85 19
    tya                                ; @55BC 98
    sec                                ; @55BD 38
    sbc $C004                          ; @55BE ED 04 C0
    sta $C00C                          ; @55C1 8D 0C C0
    txa                                ; @55C4 8A
    sbc $C005                          ; @55C5 ED 05 C0
    sta $C00D                          ; @55C8 8D 0D C0
    lda $19                            ; @55CB A5 19
    sbc $C006                          ; @55CD ED 06 C0
    sta $C00E                          ; @55D0 8D 0E C0
    lda $1C                            ; @55D3 A5 1C
    sbc $C007                          ; @55D5 ED 07 C0
    sta $C00F                          ; @55D8 8D 0F C0
    lda $0E                            ; @55DB A5 0E
    sta $C008                          ; @55DD 8D 08 C0
    clc                                ; @55E0 18
    rts                                ; @55E1 60
L55E2:
    clc                                ; @55E2 18
L55E3:
    adc $18                            ; @55E3 65 18
    tax                                ; @55E5 AA
    lda $1B                            ; @55E6 A5 1B
    adc $19                            ; @55E8 65 19
    bcs L55F3                          ; @55EA B0 07
    adc #$01                           ; @55EC 69 01
    bcs L55B8                          ; @55EE B0 C8
    jmp L55BA                          ; @55F0 4C BA 55
L55F3:
    adc #$00                           ; @55F3 69 00
    jmp L55B8                          ; @55F5 4C B8 55
L55F8:
    clc                                ; @55F8 18
    adc $20                            ; @55F9 65 20
    bcc L5600                          ; @55FB 90 03
    inc $1A                            ; @55FD E6 1A
L55FF:
    clc                                ; @55FF 18
L5600:
    adc $17                            ; @5600 65 17
    tay                                ; @5602 A8
    lda $1A                            ; @5603 A5 1A
    adc $15                            ; @5605 65 15
    bcs L55E3                          ; @5607 B0 DA
    sec                                ; @5609 38
    adc $18                            ; @560A 65 18
    tax                                ; @560C AA
    lda $1B                            ; @560D A5 1B
    adc $19                            ; @560F 65 19
    bcs L55B8                          ; @5611 B0 A5
    jmp L55BA                          ; @5613 4C BA 55
L5616:
    inc $15                            ; @5616 E6 15
    bne L5620                          ; @5618 D0 06
    inc $19                            ; @561A E6 19
    bne L5620                          ; @561C D0 02
    inc $1C                            ; @561E E6 1C
L5620:
    clc                                ; @5620 18
    jmp L5598                          ; @5621 4C 98 55
; ---- executable island $CA37 ----
* = $CA37
LCA37:
    clc                                ; @CA37 18
    adc ($3D),y                        ; @CA38 71 3D
    sta $1D,x                          ; @CA3A 95 1D
    lda #$01                           ; @CA3C A9 01
    adc ($3F),y                        ; @CA3E 71 3F
    bcc LCA75                          ; @CA40 90 33
LCA42:
    clc                                ; @CA42 18
    adc ($41),y                        ; @CA43 71 41
    sta $12,x                          ; @CA45 95 12
    lda #$01                           ; @CA47 A9 01
    adc ($4F),y                        ; @CA49 71 4F
    bcc LCA83                          ; @CA4B 90 36
LCA4D:
    clc                                ; @CA4D 18
    adc ($51),y                        ; @CA4E 71 51
    sta $16,x                          ; @CA50 95 16
    lda #$01                           ; @CA52 A9 01
    adc ($68),y                        ; @CA54 71 68
    bcc LCA91                          ; @CA56 90 39
LCA58:
    sta $1A,x                          ; @CA58 95 1A
    ldy $0E,x                          ; @CA5A B4 0E
LCA5C:
    lda $7000,y                        ; @CA5C B9 00 70
    adc $7400,y                        ; @CA5F 79 00 74
    sta $0E,x                          ; @CA62 95 0E
    lda $7200,y                        ; @CA64 B9 00 72
    adc $7600,y                        ; @CA67 79 00 76
    adc $7000,y                        ; @CA6A 79 00 70
    bcs LCA37                          ; @CA6D B0 C8
    adc ($3D),y                        ; @CA6F 71 3D
    sta $1D,x                          ; @CA71 95 1D
    lda ($3F),y                        ; @CA73 B1 3F
LCA75:
    adc $7600,y                        ; @CA75 79 00 76
    adc $7000,y                        ; @CA78 79 00 70
    bcs LCA42                          ; @CA7B B0 C5
    adc ($41),y                        ; @CA7D 71 41
    sta $12,x                          ; @CA7F 95 12
    lda ($4F),y                        ; @CA81 B1 4F
LCA83:
    adc $7600,y                        ; @CA83 79 00 76
    adc $7000,y                        ; @CA86 79 00 70
    bcs LCA4D                          ; @CA89 B0 C2
    adc ($51),y                        ; @CA8B 71 51
    sta $16,x                          ; @CA8D 95 16
    lda ($68),y                        ; @CA8F B1 68
LCA91:
    adc $7600,y                        ; @CA91 79 00 76
    dex                                ; @CA94 CA
    bpl LCA58                          ; @CA95 10 C1
    tax                                ; @CA97 AA
    ldy $1A                            ; @CA98 A4 1A
    clc                                ; @CA9A 18
    lda $1D                            ; @CA9B A5 1D
    adc $0F                            ; @CA9D 65 0F
    sta $C009                          ; @CA9F 8D 09 C0
    lda $1E                            ; @CAA2 A5 1E
    adc $10                            ; @CAA4 65 10
    bcc LCAAD                          ; @CAA6 90 05
    inc $11                            ; @CAA8 E6 11
    beq LCAFE                          ; @CAAA F0 52
    clc                                ; @CAAC 18
LCAAD:
    adc $12                            ; @CAAD 65 12
    sta $C00A                          ; @CAAF 8D 0A C0
    lda $13                            ; @CAB2 A5 13
    adc $16                            ; @CAB4 65 16
    bcc LCABA                          ; @CAB6 90 02
    inx                                ; @CAB8 E8
    clc                                ; @CAB9 18
LCABA:
    adc $11                            ; @CABA 65 11
    bcc LCAC0                          ; @CABC 90 02
    inx                                ; @CABE E8
    clc                                ; @CABF 18
LCAC0:
    adc $1F                            ; @CAC0 65 1F
    sta $C00B                          ; @CAC2 8D 0B C0
    txa                                ; @CAC5 8A
    adc $17                            ; @CAC6 65 17
    bcs LCAF3                          ; @CAC8 B0 29
LCACA:
    adc $20                            ; @CACA 65 20
    bcc LCAD0                          ; @CACC 90 02
    iny                                ; @CACE C8
    clc                                ; @CACF 18
LCAD0:
    adc $14                            ; @CAD0 65 14
    sta $C00C                          ; @CAD2 8D 0C C0
    tya                                ; @CAD5 98
    adc $15                            ; @CAD6 65 15
    bcs LCAF8                          ; @CAD8 B0 1E
LCADA:
    adc $18                            ; @CADA 65 18
    sta $C00D                          ; @CADC 8D 0D C0
    lda $19                            ; @CADF A5 19
    adc $1B                            ; @CAE1 65 1B
    sta $C00E                          ; @CAE3 8D 0E C0
    lda $1C                            ; @CAE6 A5 1C
    adc #$00                           ; @CAE8 69 00
    sta $C00F                          ; @CAEA 8D 0F C0
    lda $0E                            ; @CAED A5 0E
    sta $C008                          ; @CAEF 8D 08 C0
    rts                                ; @CAF2 60
LCAF3:
    iny                                ; @CAF3 C8
    clc                                ; @CAF4 18
    jmp LCACA                          ; @CAF5 4C CA CA
LCAF8:
    inc $1B                            ; @CAF8 E6 1B
    clc                                ; @CAFA 18
    jmp LCADA                          ; @CAFB 4C DA CA
LCAFE:
    inc $20                            ; @CAFE E6 20
    bne LCB0C                          ; @CB00 D0 0A
    inc $15                            ; @CB02 E6 15
    bne LCB0C                          ; @CB04 D0 06
    inc $19                            ; @CB06 E6 19
    bne LCB0C                          ; @CB08 D0 02
    inc $1C                            ; @CB0A E6 1C
LCB0C:
    clc                                ; @CB0C 18
    jmp LCAAD                          ; @CB0D 4C AD CA
