; MATH_SMUL24 — exact native-signed executable source mirror for v5_hybrid_lowzp
; GENERATED by tools/publish_native_signed_sources.py. Do not hand-edit.
; Canonical integrated build source remains relocatable_source/v1_balanced/math_relocatable.asm + tools/build_hybrid.py
; This mirror contains every executable instruction reachable from this signed API after MATH_INIT.
; Immutable lookup/data tables are intentionally not duplicated here.
; Corresponding unsigned API: MATH_UMUL24. Executable overlap: 0 instructions.
; Public entry: $3BF0. Reachable signed instructions: 238.
; Each instruction has an @ADDR byte annotation used by the publication validator.
!cpu 6510

; ---- executable island $3BF0 ----
* = $3BF0
L3BF0:
    jmp LCD96                          ; @3BF0 4C 96 CD
; ---- executable island $CC00 ----
* = $CC00
LCC00:
    clc                                ; @CC00 18
    adc ($13),y                        ; @CC01 71 13
    sta $CCEB                          ; @CC03 8D EB CC
    lda #$01                           ; @CC06 A9 01
    adc ($15),y                        ; @CC08 71 15
    adc ($17),y                        ; @CC0A 71 17
    adc ($19),y                        ; @CC0C 71 19
    bcc LCC70                          ; @CC0E 90 60
LCC10:
    clc                                ; @CC10 18
    adc ($1B),y                        ; @CC11 71 1B
    sta $CCF0                          ; @CC13 8D F0 CC
    lda #$01                           ; @CC16 A9 01
    adc ($1D),y                        ; @CC18 71 1D
    bcc LCC77                          ; @CC1A 90 5B
LCC1C:
    clc                                ; @CC1C 18
    adc ($13),y                        ; @CC1D 71 13
    sta $CCD7                          ; @CC1F 8D D7 CC
    lda #$01                           ; @CC22 A9 01
    adc ($15),y                        ; @CC24 71 15
    adc ($17),y                        ; @CC26 71 17
    adc ($19),y                        ; @CC28 71 19
    bcc LCC98                          ; @CC2A 90 6C
LCC2C:
    clc                                ; @CC2C 18
    adc ($1B),y                        ; @CC2D 71 1B
    sta $CCE3                          ; @CC2F 8D E3 CC
    lda #$01                           ; @CC32 A9 01
    adc ($1D),y                        ; @CC34 71 1D
    bcc LCC9F                          ; @CC36 90 67
LCC38:
    sta $1D                            ; @CC38 85 1D
    eor #$FF                           ; @CC3A 49 FF
    sta $1B                            ; @CC3C 85 1B
    sta $1F                            ; @CC3E 85 1F
    lda $09                            ; @CC40 A5 09
    sta $0D                            ; @CC42 85 0D
    eor #$FF                           ; @CC44 49 FF
    sta $0B                            ; @CC46 85 0B
    sta $0F                            ; @CC48 85 0F
    lda $11                            ; @CC4A A5 11
    sta $15                            ; @CC4C 85 15
    eor #$FF                           ; @CC4E 49 FF
    sta $13                            ; @CC50 85 13
    sta $17                            ; @CC52 85 17
LCC54:
    lda ($09),y                        ; @CC54 B1 09
    adc ($0B),y                        ; @CC56 71 0B
    sta $CCDD                          ; @CC58 8D DD CC
    lda ($0D),y                        ; @CC5B B1 0D
    adc ($0F),y                        ; @CC5D 71 0F
    adc ($11),y                        ; @CC5F 71 11
    bcs LCC00                          ; @CC61 B0 9D
    adc ($13),y                        ; @CC63 71 13
    sta $CCEB                          ; @CC65 8D EB CC
    lda ($15),y                        ; @CC68 B1 15
    adc ($17),y                        ; @CC6A 71 17
    adc ($19),y                        ; @CC6C 71 19
    bcs LCC10                          ; @CC6E B0 A0
LCC70:
    adc ($1B),y                        ; @CC70 71 1B
    sta $CCF0                          ; @CC72 8D F0 CC
    lda ($1D),y                        ; @CC75 B1 1D
LCC77:
    adc ($1F),y                        ; @CC77 71 1F
    tax                                ; @CC79 AA
    ldy #$00                           ; @CC7A A0 00
    lda ($09),y                        ; @CC7C B1 09
    adc ($0B),y                        ; @CC7E 71 0B
    sta $CCD0                          ; @CC80 8D D0 CC
    lda ($0D),y                        ; @CC83 B1 0D
    adc ($0F),y                        ; @CC85 71 0F
    adc ($11),y                        ; @CC87 71 11
    bcs LCC1C                          ; @CC89 B0 91
    adc ($13),y                        ; @CC8B 71 13
    sta $CCD7                          ; @CC8D 8D D7 CC
    lda ($15),y                        ; @CC90 B1 15
    adc ($17),y                        ; @CC92 71 17
    adc ($19),y                        ; @CC94 71 19
    bcs LCC2C                          ; @CC96 B0 94
LCC98:
    adc ($1B),y                        ; @CC98 71 1B
    sta $CCE3                          ; @CC9A 8D E3 CC
    lda ($1D),y                        ; @CC9D B1 1D
LCC9F:
    adc ($1F),y                        ; @CC9F 71 1F
    sta $CCEE                          ; @CCA1 8D EE CC
    ldy #$00                           ; @CCA4 A0 00
    lda ($09),y                        ; @CCA6 B1 09
    adc ($0B),y                        ; @CCA8 71 0B
    sta $C008                          ; @CCAA 8D 08 C0
    lda ($0D),y                        ; @CCAD B1 0D
    adc ($0F),y                        ; @CCAF 71 0F
    adc ($11),y                        ; @CCB1 71 11
    bcs LCCF6                          ; @CCB3 B0 41
    adc ($13),y                        ; @CCB5 71 13
    sta $CCCE                          ; @CCB7 8D CE CC
    lda ($15),y                        ; @CCBA B1 15
    adc ($17),y                        ; @CCBC 71 17
    adc ($19),y                        ; @CCBE 71 19
    bcs LCD06                          ; @CCC0 B0 44
LCCC2:
    adc ($1B),y                        ; @CCC2 71 1B
    sta $CCD5                          ; @CCC4 8D D5 CC
    lda ($1D),y                        ; @CCC7 B1 1D
LCCC9:
    adc ($1F),y                        ; @CCC9 71 1F
    tay                                ; @CCCB A8
    clc                                ; @CCCC 18
    lda #$00                           ; @CCCD A9 00
    adc #$00                           ; @CCCF 69 00
    sta $C009                          ; @CCD1 8D 09 C0
    lda #$00                           ; @CCD4 A9 00
    adc #$00                           ; @CCD6 69 00
    bcc LCCDC                          ; @CCD8 90 02
    iny                                ; @CCDA C8
    clc                                ; @CCDB 18
LCCDC:
    adc #$00                           ; @CCDC 69 00
    sta $C00A                          ; @CCDE 8D 0A C0
    tya                                ; @CCE1 98
    adc #$00                           ; @CCE2 69 00
    bcc LCCEA                          ; @CCE4 90 04
    clc                                ; @CCE6 18
    inc $CCEE                          ; @CCE7 EE EE CC
LCCEA:
    adc #$00                           ; @CCEA 69 00
    tay                                ; @CCEC A8
    lda #$00                           ; @CCED A9 00
    adc #$00                           ; @CCEF 69 00
    bcs LCCF4                          ; @CCF1 B0 01
    rts                                ; @CCF3 60
LCCF4:
    inx                                ; @CCF4 E8
    rts                                ; @CCF5 60
LCCF6:
    clc                                ; @CCF6 18
    adc ($13),y                        ; @CCF7 71 13
    sta $CCCE                          ; @CCF9 8D CE CC
    lda #$01                           ; @CCFC A9 01
    adc ($15),y                        ; @CCFE 71 15
    adc ($17),y                        ; @CD00 71 17
    adc ($19),y                        ; @CD02 71 19
    bcc LCCC2                          ; @CD04 90 BC
LCD06:
    clc                                ; @CD06 18
    adc ($1B),y                        ; @CD07 71 1B
    sta $CCD5                          ; @CD09 8D D5 CC
    lda #$01                           ; @CD0C A9 01
    adc ($1D),y                        ; @CD0E 71 1D
    bcc LCCC9                          ; @CD10 90 B7
LCD12:
    cpy #$00                           ; @CD12 C0 00
    bmi LCD37                          ; @CD14 30 21
    lda $19                            ; @CD16 A5 19
    bmi LCD1D                          ; @CD18 30 03
    jmp LCC38                          ; @CD1A 4C 38 CC
LCD1D:
    jsr LCC38                          ; @CD1D 20 38 CC
    sta $0D                            ; @CD20 85 0D
    tya                                ; @CD22 98
    sec                                ; @CD23 38
    sbc $CCA5                          ; @CD24 ED A5 CC
    tay                                ; @CD27 A8
    lda $0D                            ; @CD28 A5 0D
    sbc $CC7B                          ; @CD2A ED 7B CC
    sta $0D                            ; @CD2D 85 0D
    txa                                ; @CD2F 8A
    sbc $C006                          ; @CD30 ED 06 C0
    tax                                ; @CD33 AA
    lda $0D                            ; @CD34 A5 0D
    rts                                ; @CD36 60
LCD37:
    lda $19                            ; @CD37 A5 19
    bmi LCD52                          ; @CD39 30 17
    jsr LCC38                          ; @CD3B 20 38 CC
    sta $0D                            ; @CD3E 85 0D
    tya                                ; @CD40 98
    sec                                ; @CD41 38
    sbc $09                            ; @CD42 E5 09
    tay                                ; @CD44 A8
    lda $0D                            ; @CD45 A5 0D
    sbc $11                            ; @CD47 E5 11
    sta $0D                            ; @CD49 85 0D
    txa                                ; @CD4B 8A
    sbc $19                            ; @CD4C E5 19
    tax                                ; @CD4E AA
    lda $0D                            ; @CD4F A5 0D
    rts                                ; @CD51 60
LCD52:
    lda #$00                           ; @CD52 A9 00
    sbc $CCA5                          ; @CD54 ED A5 CC
    sta $CCA5                          ; @CD57 8D A5 CC
    lda #$00                           ; @CD5A A9 00
    sbc $CC7B                          ; @CD5C ED 7B CC
    sta $CC7B                          ; @CD5F 8D 7B CC
    tya                                ; @CD62 98
    eor #$FF                           ; @CD63 49 FF
    adc #$00                           ; @CD65 69 00
    tay                                ; @CD67 A8
    lda #$01                           ; @CD68 A9 01
    sbc $09                            ; @CD6A E5 09
    sta $09                            ; @CD6C 85 09
    sta $0D                            ; @CD6E 85 0D
    eor #$FF                           ; @CD70 49 FF
    sta $0B                            ; @CD72 85 0B
    sta $0F                            ; @CD74 85 0F
    lda #$00                           ; @CD76 A9 00
    sbc $11                            ; @CD78 E5 11
    sta $11                            ; @CD7A 85 11
    sta $15                            ; @CD7C 85 15
    eor #$FF                           ; @CD7E 49 FF
    sta $13                            ; @CD80 85 13
    sta $17                            ; @CD82 85 17
    lda #$00                           ; @CD84 A9 00
    sbc $19                            ; @CD86 E5 19
    sta $19                            ; @CD88 85 19
    sta $1D                            ; @CD8A 85 1D
    eor #$FF                           ; @CD8C 49 FF
    sta $1B                            ; @CD8E 85 1B
    sta $1F                            ; @CD90 85 1F
    sec                                ; @CD92 38
    jmp LCC54                          ; @CD93 4C 54 CC
LCD96:
    lda #$84                           ; @CD96 A9 84
    sta $0A                            ; @CD98 85 0A
    sta $12                            ; @CD9A 85 12
    sta $1A                            ; @CD9C 85 1A
    lda #$88                           ; @CD9E A9 88
    sta $0C                            ; @CDA0 85 0C
    sta $14                            ; @CDA2 85 14
    sta $1C                            ; @CDA4 85 1C
    lda #$86                           ; @CDA6 A9 86
    sta $0E                            ; @CDA8 85 0E
    sta $16                            ; @CDAA 85 16
    sta $1E                            ; @CDAC 85 1E
    lda #$8A                           ; @CDAE A9 8A
    sta $10                            ; @CDB0 85 10
    sta $18                            ; @CDB2 85 18
    sta $20                            ; @CDB4 85 20
    lda $C000                          ; @CDB6 AD 00 C0
    sta $09                            ; @CDB9 85 09
    lda $C001                          ; @CDBB AD 01 C0
    sta $11                            ; @CDBE 85 11
    lda $C002                          ; @CDC0 AD 02 C0
    sta $19                            ; @CDC3 85 19
    lda $C004                          ; @CDC5 AD 04 C0
    sta $CCA5                          ; @CDC8 8D A5 CC
    lda $C005                          ; @CDCB AD 05 C0
    sta $CC7B                          ; @CDCE 8D 7B CC
    ldy $C006                          ; @CDD1 AC 06 C0
    jsr LCD12                          ; @CDD4 20 12 CD
    sta $C00C                          ; @CDD7 8D 0C C0
    stx $C00D                          ; @CDDA 8E 0D C0
    sty $C00B                          ; @CDDD 8C 0B C0
    clc                                ; @CDE0 18
    rts                                ; @CDE1 60
