; div_u32_u16_u32_16 — exact executable source mirror for v3_reu_512k
; Legacy API: MATH_UDIV32_16 at $31B0
; GENERATED by tools/publish_standalone_sources.py. Do not hand-edit.
; Shipped image: v3_reu_512k/resident/math_v3_reu_512k_game_math.prg
; Canonical integrated/relocatable source: relocatable_source/v3_reu_512k/math_relocatable.asm
; This file contains every executable instruction statically reachable from the public entry after MATH_INIT.
; Shared immutable lookup/data tables and REU payload data are intentionally not duplicated here.
; The address/byte annotations make this a mechanically auditable source view of the shipped executable.
; Reachable instructions: 1043.
!cpu 6510

; ---- executable island $31B0 ----
* = $31B0
div_u32_u16_u32_16:
MATH_UDIV32_16:
    lda $C010                          ; @31B0 AD 10 C0
    sta $18                            ; @31B3 85 18
    lda $C011                          ; @31B5 AD 11 C0
    sta $19                            ; @31B8 85 19
    lda $C012                          ; @31BA AD 12 C0
    sta $10                            ; @31BD 85 10
    lda $C013                          ; @31BF AD 13 C0
    sta $11                            ; @31C2 85 11
    lda $C014                          ; @31C4 AD 14 C0
    sta $12                            ; @31C7 85 12
    lda $C015                          ; @31C9 AD 15 C0
    sta $13                            ; @31CC 85 13
    jsr L4E00                          ; @31CE 20 00 4E
    lda $1A                            ; @31D1 A5 1A
    sta $C018                          ; @31D3 8D 18 C0
    lda $1B                            ; @31D6 A5 1B
    sta $C019                          ; @31D8 8D 19 C0
    lda $14                            ; @31DB A5 14
    sta $C01A                          ; @31DD 8D 1A C0
    lda $15                            ; @31E0 A5 15
    sta $C01B                          ; @31E2 8D 1B C0
    lda $16                            ; @31E5 A5 16
    sta $C01C                          ; @31E7 8D 1C C0
    lda $17                            ; @31EA A5 17
    sta $C01D                          ; @31EC 8D 1D C0
    rts                                ; @31EF 60
; ---- executable island $420C ----
* = $420C
L420C:
    !byte $A7, $11    ; LAX zp         ; @420C A7 11
    cmp $13                            ; @420E C5 13
    bcs L4239                          ; @4210 B0 27
L4212:
    lda #$00                           ; @4212 A9 00
    sta $14                            ; @4214 85 14
    sta $15                            ; @4216 85 15
    lda $10                            ; @4218 A5 10
    sta $16                            ; @421A 85 16
    stx $17                            ; @421C 86 17
    rts                                ; @421E 60
L421F:
    lda $10                            ; @421F A5 10
    sbc $12                            ; @4221 E5 12
    bcc L4212                          ; @4223 90 ED
    cpx #$01                           ; @4225 E0 01
    bcc L4236                          ; @4227 90 0D
    sta $16                            ; @4229 85 16
    !byte $0B, $00    ; ANC #imm       ; @422B 0B 00
    sta $17                            ; @422D 85 17
    sta $15                            ; @422F 85 15
    lda #$01                           ; @4231 A9 01
    sta $14                            ; @4233 85 14
    rts                                ; @4235 60
L4236:
    jmp L460E                          ; @4236 4C 0E 46
L4239:
    beq L421F                          ; @4239 F0 E4
    lda $10                            ; @423B A5 10
    sbc $12                            ; @423D E5 12
    sta $16                            ; @423F 85 16
    txa                                ; @4241 8A
    sbc $13                            ; @4242 E5 13
    cmp $13                            ; @4244 C5 13
    bcs L42BB                          ; @4246 B0 73
    sta $17                            ; @4248 85 17
    lda #$00                           ; @424A A9 00
    sta $15                            ; @424C 85 15
    lda #$01                           ; @424E A9 01
    sta $14                            ; @4250 85 14
    rts                                ; @4252 60
L4253:
    cmp $464D,x                        ; @4253 DD 4D 46
    bcc L425B                          ; @4256 90 03
    jmp L44FA                          ; @4258 4C FA 44
L425B:
    sec                                ; @425B 38
    bcs L42C3                          ; @425C B0 65
L425E:
    lda $16                            ; @425E A5 16
    sbc $12                            ; @4260 E5 12
    bcs L426C                          ; @4262 B0 08
    txa                                ; @4264 8A
L4265:
    sta $17                            ; @4265 85 17
    lda #$02                           ; @4267 A9 02
    sta $14                            ; @4269 85 14
    rts                                ; @426B 60
L426C:
    sta $16                            ; @426C 85 16
    !byte $0B, $00    ; ANC #imm       ; @426E 0B 00
    bcc L4279                          ; @4270 90 07
L4272:
    lda $16                            ; @4272 A5 16
    sbc $12                            ; @4274 E5 12
    bcs L4280                          ; @4276 B0 08
    txa                                ; @4278 8A
L4279:
    sta $17                            ; @4279 85 17
    lda #$03                           ; @427B A9 03
    sta $14                            ; @427D 85 14
    rts                                ; @427F 60
L4280:
    sta $16                            ; @4280 85 16
    !byte $0B, $00    ; ANC #imm       ; @4282 0B 00
    bcc L428D                          ; @4284 90 07
L4286:
    lda $16                            ; @4286 A5 16
    sbc $12                            ; @4288 E5 12
    bcs L4294                          ; @428A B0 08
    txa                                ; @428C 8A
L428D:
    sta $17                            ; @428D 85 17
    lda #$04                           ; @428F A9 04
    sta $14                            ; @4291 85 14
    rts                                ; @4293 60
L4294:
    sta $16                            ; @4294 85 16
    !byte $0B, $00    ; ANC #imm       ; @4296 0B 00
    jmp L437B                          ; @4298 4C 7B 43
L429B:
    tax                                ; @429B AA
    lda $16                            ; @429C A5 16
    sbc $12                            ; @429E E5 12
    bcs L42AD                          ; @42A0 B0 0B
    stx $17                            ; @42A2 86 17
    lda #$00                           ; @42A4 A9 00
    sta $15                            ; @42A6 85 15
    lda #$01                           ; @42A8 A9 01
    sta $14                            ; @42AA 85 14
    rts                                ; @42AC 60
L42AD:
    dex                                ; @42AD CA
    bpl L42B3                          ; @42AE 10 03
    jmp L460E                          ; @42B0 4C 0E 46
L42B3:
    sta $16                            ; @42B3 85 16
    !byte $0B, $00    ; ANC #imm       ; @42B5 0B 00
    sta $15                            ; @42B7 85 15
    bcc L4265                          ; @42B9 90 AA
L42BB:
    beq L429B                          ; @42BB F0 DE
    ldx $13                            ; @42BD A6 13
    cpx #$0F                           ; @42BF E0 0F
    bcc L4253                          ; @42C1 90 90
L42C3:
    ldy #$00                           ; @42C3 A0 00
    sty $15                            ; @42C5 84 15
    tay                                ; @42C7 A8
    lda $16                            ; @42C8 A5 16
    sbc $12                            ; @42CA E5 12
    sta $16                            ; @42CC 85 16
    tya                                ; @42CE 98
    sbc $13                            ; @42CF E5 13
    cmp $13                            ; @42D1 C5 13
    bcc L4265                          ; @42D3 90 90
    beq L425E                          ; @42D5 F0 87
    tay                                ; @42D7 A8
    lda $16                            ; @42D8 A5 16
    sbc $12                            ; @42DA E5 12
    sta $16                            ; @42DC 85 16
    tya                                ; @42DE 98
    sbc $13                            ; @42DF E5 13
    cmp $13                            ; @42E1 C5 13
    bcc L4279                          ; @42E3 90 94
    beq L4272                          ; @42E5 F0 8B
    tay                                ; @42E7 A8
    lda $16                            ; @42E8 A5 16
    sbc $12                            ; @42EA E5 12
    sta $16                            ; @42EC 85 16
    tya                                ; @42EE 98
    sbc $13                            ; @42EF E5 13
    cmp $13                            ; @42F1 C5 13
    bcc L428D                          ; @42F3 90 98
    beq L4286                          ; @42F5 F0 8F
    tay                                ; @42F7 A8
    lda $16                            ; @42F8 A5 16
    sbc $12                            ; @42FA E5 12
    sta $16                            ; @42FC 85 16
    tya                                ; @42FE 98
    sbc $13                            ; @42FF E5 13
    cmp $13                            ; @4301 C5 13
    bcc L437B                          ; @4303 90 76
    beq L4374                          ; @4305 F0 6D
    tay                                ; @4307 A8
    lda $16                            ; @4308 A5 16
    sbc $12                            ; @430A E5 12
    sta $16                            ; @430C 85 16
    tya                                ; @430E 98
    sbc $13                            ; @430F E5 13
    cmp $13                            ; @4311 C5 13
    bcc L4389                          ; @4313 90 74
    beq L4382                          ; @4315 F0 6B
    tay                                ; @4317 A8
    lda $16                            ; @4318 A5 16
    sbc $12                            ; @431A E5 12
    sta $16                            ; @431C 85 16
    tya                                ; @431E 98
    sbc $13                            ; @431F E5 13
    cmp $13                            ; @4321 C5 13
    bcc L4397                          ; @4323 90 72
    beq L4390                          ; @4325 F0 69
    tay                                ; @4327 A8
    lda $16                            ; @4328 A5 16
    sbc $12                            ; @432A E5 12
    sta $16                            ; @432C 85 16
    tya                                ; @432E 98
    sbc $13                            ; @432F E5 13
    cmp $13                            ; @4331 C5 13
    bcc L43A5                          ; @4333 90 70
    beq L439E                          ; @4335 F0 67
    tay                                ; @4337 A8
    lda $16                            ; @4338 A5 16
    sbc $12                            ; @433A E5 12
    sta $16                            ; @433C 85 16
    tya                                ; @433E 98
    sbc $13                            ; @433F E5 13
    cmp $13                            ; @4341 C5 13
    bcc L43B3                          ; @4343 90 6E
    beq L43AC                          ; @4345 F0 65
    tay                                ; @4347 A8
    lda $16                            ; @4348 A5 16
    sbc $12                            ; @434A E5 12
    sta $16                            ; @434C 85 16
    tya                                ; @434E 98
    sbc $13                            ; @434F E5 13
    cmp $13                            ; @4351 C5 13
    bcc L43C1                          ; @4353 90 6C
    beq L43BA                          ; @4355 F0 63
    tay                                ; @4357 A8
    lda $16                            ; @4358 A5 16
    sbc $12                            ; @435A E5 12
    sta $16                            ; @435C 85 16
    tya                                ; @435E 98
    sbc $13                            ; @435F E5 13
    cmp $13                            ; @4361 C5 13
    bcc L43CF                          ; @4363 90 6A
    beq L43C8                          ; @4365 F0 61
    tay                                ; @4367 A8
    lda $16                            ; @4368 A5 16
    sbc $12                            ; @436A E5 12
    sta $16                            ; @436C 85 16
    tya                                ; @436E 98
    sbc $13                            ; @436F E5 13
    jmp L4400                          ; @4371 4C 00 44
L4374:
    lda $16                            ; @4374 A5 16
    sbc $12                            ; @4376 E5 12
    bcs L43D6                          ; @4378 B0 5C
    txa                                ; @437A 8A
L437B:
    sta $17                            ; @437B 85 17
    lda #$05                           ; @437D A9 05
    sta $14                            ; @437F 85 14
    rts                                ; @4381 60
L4382:
    lda $16                            ; @4382 A5 16
    sbc $12                            ; @4384 E5 12
    bcs L43DC                          ; @4386 B0 54
    txa                                ; @4388 8A
L4389:
    sta $17                            ; @4389 85 17
    lda #$06                           ; @438B A9 06
    sta $14                            ; @438D 85 14
    rts                                ; @438F 60
L4390:
    lda $16                            ; @4390 A5 16
    sbc $12                            ; @4392 E5 12
    bcs L43E2                          ; @4394 B0 4C
    txa                                ; @4396 8A
L4397:
    sta $17                            ; @4397 85 17
    lda #$07                           ; @4399 A9 07
    sta $14                            ; @439B 85 14
    rts                                ; @439D 60
L439E:
    lda $16                            ; @439E A5 16
    sbc $12                            ; @43A0 E5 12
    bcs L43E8                          ; @43A2 B0 44
    txa                                ; @43A4 8A
L43A5:
    sta $17                            ; @43A5 85 17
    lda #$08                           ; @43A7 A9 08
    sta $14                            ; @43A9 85 14
    rts                                ; @43AB 60
L43AC:
    lda $16                            ; @43AC A5 16
    sbc $12                            ; @43AE E5 12
    bcs L43EE                          ; @43B0 B0 3C
    txa                                ; @43B2 8A
L43B3:
    sta $17                            ; @43B3 85 17
    lda #$09                           ; @43B5 A9 09
    sta $14                            ; @43B7 85 14
    rts                                ; @43B9 60
L43BA:
    lda $16                            ; @43BA A5 16
    sbc $12                            ; @43BC E5 12
    bcs L43F4                          ; @43BE B0 34
    txa                                ; @43C0 8A
L43C1:
    sta $17                            ; @43C1 85 17
    lda #$0A                           ; @43C3 A9 0A
    sta $14                            ; @43C5 85 14
    rts                                ; @43C7 60
L43C8:
    lda $16                            ; @43C8 A5 16
    sbc $12                            ; @43CA E5 12
    bcs L43FA                          ; @43CC B0 2C
    txa                                ; @43CE 8A
L43CF:
    sta $17                            ; @43CF 85 17
    lda #$0B                           ; @43D1 A9 0B
    sta $14                            ; @43D3 85 14
    rts                                ; @43D5 60
L43D6:
    sta $16                            ; @43D6 85 16
    !byte $0B, $00    ; ANC #imm       ; @43D8 0B 00
    bcc L4389                          ; @43DA 90 AD
L43DC:
    sta $16                            ; @43DC 85 16
    !byte $0B, $00    ; ANC #imm       ; @43DE 0B 00
    bcc L4397                          ; @43E0 90 B5
L43E2:
    sta $16                            ; @43E2 85 16
    !byte $0B, $00    ; ANC #imm       ; @43E4 0B 00
    bcc L43A5                          ; @43E6 90 BD
L43E8:
    sta $16                            ; @43E8 85 16
    !byte $0B, $00    ; ANC #imm       ; @43EA 0B 00
    bcc L43B3                          ; @43EC 90 C5
L43EE:
    sta $16                            ; @43EE 85 16
    !byte $0B, $00    ; ANC #imm       ; @43F0 0B 00
    bcc L43C1                          ; @43F2 90 CD
L43F4:
    sta $16                            ; @43F4 85 16
    !byte $0B, $00    ; ANC #imm       ; @43F6 0B 00
    bcc L43CF                          ; @43F8 90 D5
L43FA:
    sta $16                            ; @43FA 85 16
    !byte $0B, $00    ; ANC #imm       ; @43FC 0B 00
    bcc L4457                          ; @43FE 90 57
L4400:
    cmp $13                            ; @4400 C5 13
    bcc L4457                          ; @4402 90 53
    beq L4450                          ; @4404 F0 4A
    tay                                ; @4406 A8
    lda $16                            ; @4407 A5 16
    sbc $12                            ; @4409 E5 12
    sta $16                            ; @440B 85 16
    tya                                ; @440D 98
    sbc $13                            ; @440E E5 13
    cmp $13                            ; @4410 C5 13
    bcc L446B                          ; @4412 90 57
    beq L4464                          ; @4414 F0 4E
    tay                                ; @4416 A8
    lda $16                            ; @4417 A5 16
    sbc $12                            ; @4419 E5 12
    sta $16                            ; @441B 85 16
    tya                                ; @441D 98
    sbc $13                            ; @441E E5 13
    cmp $13                            ; @4420 C5 13
    bcc L447F                          ; @4422 90 5B
    beq L4478                          ; @4424 F0 52
    tay                                ; @4426 A8
    lda $16                            ; @4427 A5 16
    sbc $12                            ; @4429 E5 12
    sta $16                            ; @442B 85 16
    tya                                ; @442D 98
    sbc $13                            ; @442E E5 13
    cmp $13                            ; @4430 C5 13
    bcc L4493                          ; @4432 90 5F
    beq L448C                          ; @4434 F0 56
    tay                                ; @4436 A8
    lda $16                            ; @4437 A5 16
    sbc $12                            ; @4439 E5 12
    sta $16                            ; @443B 85 16
    tya                                ; @443D 98
    sbc $13                            ; @443E E5 13
    cmp $13                            ; @4440 C5 13
    bcc L44A7                          ; @4442 90 63
    beq L44A0                          ; @4444 F0 5A
    tay                                ; @4446 A8
    lda $16                            ; @4447 A5 16
    sbc $12                            ; @4449 E5 12
    sta $16                            ; @444B 85 16
    tya                                ; @444D 98
    sbc $13                            ; @444E E5 13
L4450:
    lda $16                            ; @4450 A5 16
    sbc $12                            ; @4452 E5 12
    bcs L445E                          ; @4454 B0 08
    txa                                ; @4456 8A
L4457:
    sta $17                            ; @4457 85 17
    lda #$0C                           ; @4459 A9 0C
    sta $14                            ; @445B 85 14
    rts                                ; @445D 60
L445E:
    sta $16                            ; @445E 85 16
    !byte $0B, $00    ; ANC #imm       ; @4460 0B 00
    bcc L446B                          ; @4462 90 07
L4464:
    lda $16                            ; @4464 A5 16
    sbc $12                            ; @4466 E5 12
    bcs L4472                          ; @4468 B0 08
    txa                                ; @446A 8A
L446B:
    sta $17                            ; @446B 85 17
    lda #$0D                           ; @446D A9 0D
    sta $14                            ; @446F 85 14
    rts                                ; @4471 60
L4472:
    sta $16                            ; @4472 85 16
    !byte $0B, $00    ; ANC #imm       ; @4474 0B 00
    bcc L447F                          ; @4476 90 07
L4478:
    lda $16                            ; @4478 A5 16
    sbc $12                            ; @447A E5 12
    bcs L4486                          ; @447C B0 08
    txa                                ; @447E 8A
L447F:
    sta $17                            ; @447F 85 17
    lda #$0E                           ; @4481 A9 0E
    sta $14                            ; @4483 85 14
    rts                                ; @4485 60
L4486:
    sta $16                            ; @4486 85 16
    !byte $0B, $00    ; ANC #imm       ; @4488 0B 00
    bcc L4493                          ; @448A 90 07
L448C:
    lda $16                            ; @448C A5 16
    sbc $12                            ; @448E E5 12
    bcs L449A                          ; @4490 B0 08
    txa                                ; @4492 8A
L4493:
    sta $17                            ; @4493 85 17
    lda #$0F                           ; @4495 A9 0F
    sta $14                            ; @4497 85 14
    rts                                ; @4499 60
L449A:
    sta $16                            ; @449A 85 16
    !byte $0B, $00    ; ANC #imm       ; @449C 0B 00
    bcc L44A7                          ; @449E 90 07
L44A0:
    lda $16                            ; @44A0 A5 16
    sbc $12                            ; @44A2 E5 12
    bcs L44AE                          ; @44A4 B0 08
    txa                                ; @44A6 8A
L44A7:
    sta $17                            ; @44A7 85 17
    lda #$10                           ; @44A9 A9 10
    sta $14                            ; @44AB 85 14
    rts                                ; @44AD 60
L44AE:
    sta $16                            ; @44AE 85 16
    !byte $0B, $00    ; ANC #imm       ; @44B0 0B 00
    sta $17                            ; @44B2 85 17
    lda #$11                           ; @44B4 A9 11
    sta $14                            ; @44B6 85 14
    rts                                ; @44B8 60
L44B9:
    jmp L4612                          ; @44B9 4C 12 46
L44BC:
    jmp L460E                          ; @44BC 4C 0E 46
L44BF:
    cpx #$01                           ; @44BF E0 01
    bcc L44BC                          ; @44C1 90 F9
    beq L44B9                          ; @44C3 F0 F4
    lda $10                            ; @44C5 A5 10
    asl a                              ; @44C7 0A
    sta $14                            ; @44C8 85 14
    lda $11                            ; @44CA A5 11
    rol a                              ; @44CC 2A
    sta $16                            ; @44CD 85 16
    lda #$00                           ; @44CF A9 00
    sta $15                            ; @44D1 85 15
    rol a                              ; @44D3 2A
    rol $14                            ; @44D4 26 14
    rol $16                            ; @44D6 26 16
    rol a                              ; @44D8 2A
    cmp $13                            ; @44D9 C5 13
    bcc L4516                          ; @44DB 90 39
    beq L44EB                          ; @44DD F0 0C
    tay                                ; @44DF A8
    lda $16                            ; @44E0 A5 16
    sbc $12                            ; @44E2 E5 12
    sta $16                            ; @44E4 85 16
    tya                                ; @44E6 98
    sbc $13                            ; @44E7 E5 13
    bcs L4516                          ; @44E9 B0 2B
L44EB:
    lda $16                            ; @44EB A5 16
    sbc $12                            ; @44ED E5 12
    bcc L44F7                          ; @44EF 90 06
    sta $16                            ; @44F1 85 16
    lda #$00                           ; @44F3 A9 00
    bcs L4516                          ; @44F5 B0 1F
L44F7:
    txa                                ; @44F7 8A
    bcc L4516                          ; @44F8 90 1C
L44FA:
    cpx #$04                           ; @44FA E0 04
    bcc L44BF                          ; @44FC 90 C1
    cpx #$08                           ; @44FE E0 08
    bcs L454B                          ; @4500 B0 49
    lda $10                            ; @4502 A5 10
    asl a                              ; @4504 0A
    sta $14                            ; @4505 85 14
    lda $11                            ; @4507 A5 11
    rol a                              ; @4509 2A
    sta $16                            ; @450A 85 16
    lda #$00                           ; @450C A9 00
    sta $15                            ; @450E 85 15
    rol a                              ; @4510 2A
    asl $14                            ; @4511 06 14
    rol $16                            ; @4513 26 16
    rol a                              ; @4515 2A
L4516:
    rol $14                            ; @4516 26 14
    rol $16                            ; @4518 26 16
    rol a                              ; @451A 2A
    cmp $13                            ; @451B C5 13
    bcc L4564                          ; @451D 90 45
    beq L452D                          ; @451F F0 0C
    tay                                ; @4521 A8
    lda $16                            ; @4522 A5 16
    sbc $12                            ; @4524 E5 12
    sta $16                            ; @4526 85 16
    tya                                ; @4528 98
    sbc $13                            ; @4529 E5 13
    bcs L4564                          ; @452B B0 37
L452D:
    lda $16                            ; @452D A5 16
    sbc $12                            ; @452F E5 12
    bcc L4539                          ; @4531 90 06
    sta $16                            ; @4533 85 16
    lda #$00                           ; @4535 A9 00
    bcs L4564                          ; @4537 B0 2B
L4539:
    txa                                ; @4539 8A
    bcc L4564                          ; @453A 90 28
L453C:
    lda $16                            ; @453C A5 16
    sbc $12                            ; @453E E5 12
    bcc L4548                          ; @4540 90 06
    sta $16                            ; @4542 85 16
    lda #$00                           ; @4544 A9 00
    bcs L4579                          ; @4546 B0 31
L4548:
    txa                                ; @4548 8A
    bcc L4579                          ; @4549 90 2E
L454B:
    lda $10                            ; @454B A5 10
    asl a                              ; @454D 0A
    sta $14                            ; @454E 85 14
    lda $11                            ; @4550 A5 11
    rol a                              ; @4552 2A
    sta $16                            ; @4553 85 16
    lda #$00                           ; @4555 A9 00
    sta $15                            ; @4557 85 15
    rol a                              ; @4559 2A
    asl $14                            ; @455A 06 14
    rol $16                            ; @455C 26 16
    rol a                              ; @455E 2A
    asl $14                            ; @455F 06 14
    rol $16                            ; @4561 26 16
    rol a                              ; @4563 2A
L4564:
    rol $14                            ; @4564 26 14
    rol $16                            ; @4566 26 16
    rol a                              ; @4568 2A
    cmp $13                            ; @4569 C5 13
    bcc L4579                          ; @456B 90 0C
    beq L453C                          ; @456D F0 CD
    tay                                ; @456F A8
    lda $16                            ; @4570 A5 16
    sbc $12                            ; @4572 E5 12
    sta $16                            ; @4574 85 16
    tya                                ; @4576 98
    sbc $13                            ; @4577 E5 13
L4579:
    rol $14                            ; @4579 26 14
    rol $16                            ; @457B 26 16
    rol a                              ; @457D 2A
    cmp $13                            ; @457E C5 13
    bcc L458E                          ; @4580 90 0C
    beq L45D2                          ; @4582 F0 4E
    tay                                ; @4584 A8
    lda $16                            ; @4585 A5 16
    sbc $12                            ; @4587 E5 12
    sta $16                            ; @4589 85 16
    tya                                ; @458B 98
    sbc $13                            ; @458C E5 13
L458E:
    rol $14                            ; @458E 26 14
    rol $16                            ; @4590 26 16
    rol a                              ; @4592 2A
    cmp $13                            ; @4593 C5 13
    bcc L45A3                          ; @4595 90 0C
    beq L45E1                          ; @4597 F0 48
    tay                                ; @4599 A8
    lda $16                            ; @459A A5 16
    sbc $12                            ; @459C E5 12
    sta $16                            ; @459E 85 16
    tya                                ; @45A0 98
    sbc $13                            ; @45A1 E5 13
L45A3:
    rol $14                            ; @45A3 26 14
    rol $16                            ; @45A5 26 16
    rol a                              ; @45A7 2A
    cmp $13                            ; @45A8 C5 13
    bcc L45B8                          ; @45AA 90 0C
    beq L45F0                          ; @45AC F0 42
    tay                                ; @45AE A8
    lda $16                            ; @45AF A5 16
    sbc $12                            ; @45B1 E5 12
    sta $16                            ; @45B3 85 16
    tya                                ; @45B5 98
    sbc $13                            ; @45B6 E5 13
L45B8:
    rol $14                            ; @45B8 26 14
    rol $16                            ; @45BA 26 16
    rol a                              ; @45BC 2A
    cmp $13                            ; @45BD C5 13
    bcc L45CD                          ; @45BF 90 0C
    beq L45FF                          ; @45C1 F0 3C
    tay                                ; @45C3 A8
    lda $16                            ; @45C4 A5 16
    sbc $12                            ; @45C6 E5 12
    sta $16                            ; @45C8 85 16
    tya                                ; @45CA 98
    sbc $13                            ; @45CB E5 13
L45CD:
    rol $14                            ; @45CD 26 14
    sta $17                            ; @45CF 85 17
    rts                                ; @45D1 60
L45D2:
    lda $16                            ; @45D2 A5 16
    sbc $12                            ; @45D4 E5 12
    bcc L45DE                          ; @45D6 90 06
    sta $16                            ; @45D8 85 16
    lda #$00                           ; @45DA A9 00
    bcs L458E                          ; @45DC B0 B0
L45DE:
    txa                                ; @45DE 8A
    bcc L458E                          ; @45DF 90 AD
L45E1:
    lda $16                            ; @45E1 A5 16
    sbc $12                            ; @45E3 E5 12
    bcc L45ED                          ; @45E5 90 06
    sta $16                            ; @45E7 85 16
    lda #$00                           ; @45E9 A9 00
    bcs L45A3                          ; @45EB B0 B6
L45ED:
    txa                                ; @45ED 8A
    bcc L45A3                          ; @45EE 90 B3
L45F0:
    lda $16                            ; @45F0 A5 16
    sbc $12                            ; @45F2 E5 12
    bcc L45FC                          ; @45F4 90 06
    sta $16                            ; @45F6 85 16
    lda #$00                           ; @45F8 A9 00
    bcs L45B8                          ; @45FA B0 BC
L45FC:
    txa                                ; @45FC 8A
    bcc L45B8                          ; @45FD 90 B9
L45FF:
    lda $16                            ; @45FF A5 16
    sbc $12                            ; @4601 E5 12
    bcc L460B                          ; @4603 90 06
    sta $16                            ; @4605 85 16
    lda #$00                           ; @4607 A9 00
    bcs L45CD                          ; @4609 B0 C2
L460B:
    txa                                ; @460B 8A
    bcc L45CD                          ; @460C 90 BF
L460E:
    lda $12                            ; @460E A5 12
    beq L4643                          ; @4610 F0 31
L4612:
    lda $10                            ; @4612 A5 10
    sta $14                            ; @4614 85 14
    lda $11                            ; @4616 A5 11
    sta $15                            ; @4618 85 15
    lda #$00                           ; @461A A9 00
    lsr a                              ; @461C 4A
    sta $16                            ; @461D 85 16
    sta $17                            ; @461F 85 17
    ldy #$10                           ; @4621 A0 10
L4623:
    rol $14                            ; @4623 26 14
    rol $15                            ; @4625 26 15
    rol $16                            ; @4627 26 16
    rol $17                            ; @4629 26 17
    sec                                ; @462B 38
    lda $16                            ; @462C A5 16
    sbc $12                            ; @462E E5 12
    tax                                ; @4630 AA
    lda $17                            ; @4631 A5 17
    sbc $13                            ; @4633 E5 13
    bcc L463B                          ; @4635 90 04
    sta $17                            ; @4637 85 17
    stx $16                            ; @4639 86 16
L463B:
    dey                                ; @463B 88
    bne L4623                          ; @463C D0 E5
    rol $14                            ; @463E 26 14
    rol $15                            ; @4640 26 15
    rts                                ; @4642 60
L4643:
    sta $14                            ; @4643 85 14
    sta $15                            ; @4645 85 15
    sta $16                            ; @4647 85 16
    sta $17                            ; @4649 85 17
    sec                                ; @464B 38
    rts                                ; @464C 60
; ---- executable island $4E00 ----
* = $4E00
L4E00:
    jsr L420C                          ; @4E00 20 0C 42
    bcc L4E08                          ; @4E03 90 03
    jmp L50DA                          ; @4E05 4C DA 50
L4E08:
    lda $18                            ; @4E08 A5 18
    sta $1A                            ; @4E0A 85 1A
    lda $19                            ; @4E0C A5 19
    sta $1B                            ; @4E0E 85 1B
    lda $17                            ; @4E10 A5 17
    rol $1A                            ; @4E12 26 1A
    rol $1B                            ; @4E14 26 1B
    rol $16                            ; @4E16 26 16
    rol a                              ; @4E18 2A
    bcs L4E33                          ; @4E19 B0 18
    cmp $13                            ; @4E1B C5 13
    bcc L4E3E                          ; @4E1D 90 1F
    bne L4E27                          ; @4E1F D0 06
    ldx $16                            ; @4E21 A6 16
    cpx $12                            ; @4E23 E4 12
    bcc L4E3E                          ; @4E25 90 17
L4E27:
    tax                                ; @4E27 AA
    lda $16                            ; @4E28 A5 16
    sbc $12                            ; @4E2A E5 12
    sta $16                            ; @4E2C 85 16
    txa                                ; @4E2E 8A
    sbc $13                            ; @4E2F E5 13
    bcs L4E3E                          ; @4E31 B0 0B
L4E33:
    tax                                ; @4E33 AA
    lda $16                            ; @4E34 A5 16
    sbc $12                            ; @4E36 E5 12
    sta $16                            ; @4E38 85 16
    txa                                ; @4E3A 8A
    sbc $13                            ; @4E3B E5 13
    sec                                ; @4E3D 38
L4E3E:
    rol $1A                            ; @4E3E 26 1A
    rol $1B                            ; @4E40 26 1B
    rol $16                            ; @4E42 26 16
    rol a                              ; @4E44 2A
    bcs L4E5F                          ; @4E45 B0 18
    cmp $13                            ; @4E47 C5 13
    bcc L4E6A                          ; @4E49 90 1F
    bne L4E53                          ; @4E4B D0 06
    ldx $16                            ; @4E4D A6 16
    cpx $12                            ; @4E4F E4 12
    bcc L4E6A                          ; @4E51 90 17
L4E53:
    tax                                ; @4E53 AA
    lda $16                            ; @4E54 A5 16
    sbc $12                            ; @4E56 E5 12
    sta $16                            ; @4E58 85 16
    txa                                ; @4E5A 8A
    sbc $13                            ; @4E5B E5 13
    bcs L4E6A                          ; @4E5D B0 0B
L4E5F:
    tax                                ; @4E5F AA
    lda $16                            ; @4E60 A5 16
    sbc $12                            ; @4E62 E5 12
    sta $16                            ; @4E64 85 16
    txa                                ; @4E66 8A
    sbc $13                            ; @4E67 E5 13
    sec                                ; @4E69 38
L4E6A:
    rol $1A                            ; @4E6A 26 1A
    rol $1B                            ; @4E6C 26 1B
    rol $16                            ; @4E6E 26 16
    rol a                              ; @4E70 2A
    bcs L4E8B                          ; @4E71 B0 18
    cmp $13                            ; @4E73 C5 13
    bcc L4E96                          ; @4E75 90 1F
    bne L4E7F                          ; @4E77 D0 06
    ldx $16                            ; @4E79 A6 16
    cpx $12                            ; @4E7B E4 12
    bcc L4E96                          ; @4E7D 90 17
L4E7F:
    tax                                ; @4E7F AA
    lda $16                            ; @4E80 A5 16
    sbc $12                            ; @4E82 E5 12
    sta $16                            ; @4E84 85 16
    txa                                ; @4E86 8A
    sbc $13                            ; @4E87 E5 13
    bcs L4E96                          ; @4E89 B0 0B
L4E8B:
    tax                                ; @4E8B AA
    lda $16                            ; @4E8C A5 16
    sbc $12                            ; @4E8E E5 12
    sta $16                            ; @4E90 85 16
    txa                                ; @4E92 8A
    sbc $13                            ; @4E93 E5 13
    sec                                ; @4E95 38
L4E96:
    rol $1A                            ; @4E96 26 1A
    rol $1B                            ; @4E98 26 1B
    rol $16                            ; @4E9A 26 16
    rol a                              ; @4E9C 2A
    bcs L4EB7                          ; @4E9D B0 18
    cmp $13                            ; @4E9F C5 13
    bcc L4EC2                          ; @4EA1 90 1F
    bne L4EAB                          ; @4EA3 D0 06
    ldx $16                            ; @4EA5 A6 16
    cpx $12                            ; @4EA7 E4 12
    bcc L4EC2                          ; @4EA9 90 17
L4EAB:
    tax                                ; @4EAB AA
    lda $16                            ; @4EAC A5 16
    sbc $12                            ; @4EAE E5 12
    sta $16                            ; @4EB0 85 16
    txa                                ; @4EB2 8A
    sbc $13                            ; @4EB3 E5 13
    bcs L4EC2                          ; @4EB5 B0 0B
L4EB7:
    tax                                ; @4EB7 AA
    lda $16                            ; @4EB8 A5 16
    sbc $12                            ; @4EBA E5 12
    sta $16                            ; @4EBC 85 16
    txa                                ; @4EBE 8A
    sbc $13                            ; @4EBF E5 13
    sec                                ; @4EC1 38
L4EC2:
    rol $1A                            ; @4EC2 26 1A
    rol $1B                            ; @4EC4 26 1B
    rol $16                            ; @4EC6 26 16
    rol a                              ; @4EC8 2A
    bcs L4EE3                          ; @4EC9 B0 18
    cmp $13                            ; @4ECB C5 13
    bcc L4EEE                          ; @4ECD 90 1F
    bne L4ED7                          ; @4ECF D0 06
    ldx $16                            ; @4ED1 A6 16
    cpx $12                            ; @4ED3 E4 12
    bcc L4EEE                          ; @4ED5 90 17
L4ED7:
    tax                                ; @4ED7 AA
    lda $16                            ; @4ED8 A5 16
    sbc $12                            ; @4EDA E5 12
    sta $16                            ; @4EDC 85 16
    txa                                ; @4EDE 8A
    sbc $13                            ; @4EDF E5 13
    bcs L4EEE                          ; @4EE1 B0 0B
L4EE3:
    tax                                ; @4EE3 AA
    lda $16                            ; @4EE4 A5 16
    sbc $12                            ; @4EE6 E5 12
    sta $16                            ; @4EE8 85 16
    txa                                ; @4EEA 8A
    sbc $13                            ; @4EEB E5 13
    sec                                ; @4EED 38
L4EEE:
    rol $1A                            ; @4EEE 26 1A
    rol $1B                            ; @4EF0 26 1B
    rol $16                            ; @4EF2 26 16
    rol a                              ; @4EF4 2A
    bcs L4F0F                          ; @4EF5 B0 18
    cmp $13                            ; @4EF7 C5 13
    bcc L4F1A                          ; @4EF9 90 1F
    bne L4F03                          ; @4EFB D0 06
    ldx $16                            ; @4EFD A6 16
    cpx $12                            ; @4EFF E4 12
    bcc L4F1A                          ; @4F01 90 17
L4F03:
    tax                                ; @4F03 AA
    lda $16                            ; @4F04 A5 16
    sbc $12                            ; @4F06 E5 12
    sta $16                            ; @4F08 85 16
    txa                                ; @4F0A 8A
    sbc $13                            ; @4F0B E5 13
    bcs L4F1A                          ; @4F0D B0 0B
L4F0F:
    tax                                ; @4F0F AA
    lda $16                            ; @4F10 A5 16
    sbc $12                            ; @4F12 E5 12
    sta $16                            ; @4F14 85 16
    txa                                ; @4F16 8A
    sbc $13                            ; @4F17 E5 13
    sec                                ; @4F19 38
L4F1A:
    rol $1A                            ; @4F1A 26 1A
    rol $1B                            ; @4F1C 26 1B
    rol $16                            ; @4F1E 26 16
    rol a                              ; @4F20 2A
    bcs L4F3B                          ; @4F21 B0 18
    cmp $13                            ; @4F23 C5 13
    bcc L4F46                          ; @4F25 90 1F
    bne L4F2F                          ; @4F27 D0 06
    ldx $16                            ; @4F29 A6 16
    cpx $12                            ; @4F2B E4 12
    bcc L4F46                          ; @4F2D 90 17
L4F2F:
    tax                                ; @4F2F AA
    lda $16                            ; @4F30 A5 16
    sbc $12                            ; @4F32 E5 12
    sta $16                            ; @4F34 85 16
    txa                                ; @4F36 8A
    sbc $13                            ; @4F37 E5 13
    bcs L4F46                          ; @4F39 B0 0B
L4F3B:
    tax                                ; @4F3B AA
    lda $16                            ; @4F3C A5 16
    sbc $12                            ; @4F3E E5 12
    sta $16                            ; @4F40 85 16
    txa                                ; @4F42 8A
    sbc $13                            ; @4F43 E5 13
    sec                                ; @4F45 38
L4F46:
    rol $1A                            ; @4F46 26 1A
    rol $1B                            ; @4F48 26 1B
    rol $16                            ; @4F4A 26 16
    rol a                              ; @4F4C 2A
    bcs L4F67                          ; @4F4D B0 18
    cmp $13                            ; @4F4F C5 13
    bcc L4F72                          ; @4F51 90 1F
    bne L4F5B                          ; @4F53 D0 06
    ldx $16                            ; @4F55 A6 16
    cpx $12                            ; @4F57 E4 12
    bcc L4F72                          ; @4F59 90 17
L4F5B:
    tax                                ; @4F5B AA
    lda $16                            ; @4F5C A5 16
    sbc $12                            ; @4F5E E5 12
    sta $16                            ; @4F60 85 16
    txa                                ; @4F62 8A
    sbc $13                            ; @4F63 E5 13
    bcs L4F72                          ; @4F65 B0 0B
L4F67:
    tax                                ; @4F67 AA
    lda $16                            ; @4F68 A5 16
    sbc $12                            ; @4F6A E5 12
    sta $16                            ; @4F6C 85 16
    txa                                ; @4F6E 8A
    sbc $13                            ; @4F6F E5 13
    sec                                ; @4F71 38
L4F72:
    rol $1A                            ; @4F72 26 1A
    rol $1B                            ; @4F74 26 1B
    rol $16                            ; @4F76 26 16
    rol a                              ; @4F78 2A
    bcs L4F93                          ; @4F79 B0 18
    cmp $13                            ; @4F7B C5 13
    bcc L4F9E                          ; @4F7D 90 1F
    bne L4F87                          ; @4F7F D0 06
    ldx $16                            ; @4F81 A6 16
    cpx $12                            ; @4F83 E4 12
    bcc L4F9E                          ; @4F85 90 17
L4F87:
    tax                                ; @4F87 AA
    lda $16                            ; @4F88 A5 16
    sbc $12                            ; @4F8A E5 12
    sta $16                            ; @4F8C 85 16
    txa                                ; @4F8E 8A
    sbc $13                            ; @4F8F E5 13
    bcs L4F9E                          ; @4F91 B0 0B
L4F93:
    tax                                ; @4F93 AA
    lda $16                            ; @4F94 A5 16
    sbc $12                            ; @4F96 E5 12
    sta $16                            ; @4F98 85 16
    txa                                ; @4F9A 8A
    sbc $13                            ; @4F9B E5 13
    sec                                ; @4F9D 38
L4F9E:
    rol $1A                            ; @4F9E 26 1A
    rol $1B                            ; @4FA0 26 1B
    rol $16                            ; @4FA2 26 16
    rol a                              ; @4FA4 2A
    bcs L4FBF                          ; @4FA5 B0 18
    cmp $13                            ; @4FA7 C5 13
    bcc L4FCA                          ; @4FA9 90 1F
    bne L4FB3                          ; @4FAB D0 06
    ldx $16                            ; @4FAD A6 16
    cpx $12                            ; @4FAF E4 12
    bcc L4FCA                          ; @4FB1 90 17
L4FB3:
    tax                                ; @4FB3 AA
    lda $16                            ; @4FB4 A5 16
    sbc $12                            ; @4FB6 E5 12
    sta $16                            ; @4FB8 85 16
    txa                                ; @4FBA 8A
    sbc $13                            ; @4FBB E5 13
    bcs L4FCA                          ; @4FBD B0 0B
L4FBF:
    tax                                ; @4FBF AA
    lda $16                            ; @4FC0 A5 16
    sbc $12                            ; @4FC2 E5 12
    sta $16                            ; @4FC4 85 16
    txa                                ; @4FC6 8A
    sbc $13                            ; @4FC7 E5 13
    sec                                ; @4FC9 38
L4FCA:
    rol $1A                            ; @4FCA 26 1A
    rol $1B                            ; @4FCC 26 1B
    rol $16                            ; @4FCE 26 16
    rol a                              ; @4FD0 2A
    bcs L4FEB                          ; @4FD1 B0 18
    cmp $13                            ; @4FD3 C5 13
    bcc L4FF6                          ; @4FD5 90 1F
    bne L4FDF                          ; @4FD7 D0 06
    ldx $16                            ; @4FD9 A6 16
    cpx $12                            ; @4FDB E4 12
    bcc L4FF6                          ; @4FDD 90 17
L4FDF:
    tax                                ; @4FDF AA
    lda $16                            ; @4FE0 A5 16
    sbc $12                            ; @4FE2 E5 12
    sta $16                            ; @4FE4 85 16
    txa                                ; @4FE6 8A
    sbc $13                            ; @4FE7 E5 13
    bcs L4FF6                          ; @4FE9 B0 0B
L4FEB:
    tax                                ; @4FEB AA
    lda $16                            ; @4FEC A5 16
    sbc $12                            ; @4FEE E5 12
    sta $16                            ; @4FF0 85 16
    txa                                ; @4FF2 8A
    sbc $13                            ; @4FF3 E5 13
    sec                                ; @4FF5 38
L4FF6:
    rol $1A                            ; @4FF6 26 1A
    rol $1B                            ; @4FF8 26 1B
    rol $16                            ; @4FFA 26 16
    rol a                              ; @4FFC 2A
    bcs L5017                          ; @4FFD B0 18
    cmp $13                            ; @4FFF C5 13
    bcc L5022                          ; @5001 90 1F
    bne L500B                          ; @5003 D0 06
    ldx $16                            ; @5005 A6 16
    cpx $12                            ; @5007 E4 12
    bcc L5022                          ; @5009 90 17
L500B:
    tax                                ; @500B AA
    lda $16                            ; @500C A5 16
    sbc $12                            ; @500E E5 12
    sta $16                            ; @5010 85 16
    txa                                ; @5012 8A
    sbc $13                            ; @5013 E5 13
    bcs L5022                          ; @5015 B0 0B
L5017:
    tax                                ; @5017 AA
    lda $16                            ; @5018 A5 16
    sbc $12                            ; @501A E5 12
    sta $16                            ; @501C 85 16
    txa                                ; @501E 8A
    sbc $13                            ; @501F E5 13
    sec                                ; @5021 38
L5022:
    rol $1A                            ; @5022 26 1A
    rol $1B                            ; @5024 26 1B
    rol $16                            ; @5026 26 16
    rol a                              ; @5028 2A
    bcs L5043                          ; @5029 B0 18
    cmp $13                            ; @502B C5 13
    bcc L504E                          ; @502D 90 1F
    bne L5037                          ; @502F D0 06
    ldx $16                            ; @5031 A6 16
    cpx $12                            ; @5033 E4 12
    bcc L504E                          ; @5035 90 17
L5037:
    tax                                ; @5037 AA
    lda $16                            ; @5038 A5 16
    sbc $12                            ; @503A E5 12
    sta $16                            ; @503C 85 16
    txa                                ; @503E 8A
    sbc $13                            ; @503F E5 13
    bcs L504E                          ; @5041 B0 0B
L5043:
    tax                                ; @5043 AA
    lda $16                            ; @5044 A5 16
    sbc $12                            ; @5046 E5 12
    sta $16                            ; @5048 85 16
    txa                                ; @504A 8A
    sbc $13                            ; @504B E5 13
    sec                                ; @504D 38
L504E:
    rol $1A                            ; @504E 26 1A
    rol $1B                            ; @5050 26 1B
    rol $16                            ; @5052 26 16
    rol a                              ; @5054 2A
    bcs L506F                          ; @5055 B0 18
    cmp $13                            ; @5057 C5 13
    bcc L507A                          ; @5059 90 1F
    bne L5063                          ; @505B D0 06
    ldx $16                            ; @505D A6 16
    cpx $12                            ; @505F E4 12
    bcc L507A                          ; @5061 90 17
L5063:
    tax                                ; @5063 AA
    lda $16                            ; @5064 A5 16
    sbc $12                            ; @5066 E5 12
    sta $16                            ; @5068 85 16
    txa                                ; @506A 8A
    sbc $13                            ; @506B E5 13
    bcs L507A                          ; @506D B0 0B
L506F:
    tax                                ; @506F AA
    lda $16                            ; @5070 A5 16
    sbc $12                            ; @5072 E5 12
    sta $16                            ; @5074 85 16
    txa                                ; @5076 8A
    sbc $13                            ; @5077 E5 13
    sec                                ; @5079 38
L507A:
    rol $1A                            ; @507A 26 1A
    rol $1B                            ; @507C 26 1B
    rol $16                            ; @507E 26 16
    rol a                              ; @5080 2A
    bcs L509B                          ; @5081 B0 18
    cmp $13                            ; @5083 C5 13
    bcc L50A6                          ; @5085 90 1F
    bne L508F                          ; @5087 D0 06
    ldx $16                            ; @5089 A6 16
    cpx $12                            ; @508B E4 12
    bcc L50A6                          ; @508D 90 17
L508F:
    tax                                ; @508F AA
    lda $16                            ; @5090 A5 16
    sbc $12                            ; @5092 E5 12
    sta $16                            ; @5094 85 16
    txa                                ; @5096 8A
    sbc $13                            ; @5097 E5 13
    bcs L50A6                          ; @5099 B0 0B
L509B:
    tax                                ; @509B AA
    lda $16                            ; @509C A5 16
    sbc $12                            ; @509E E5 12
    sta $16                            ; @50A0 85 16
    txa                                ; @50A2 8A
    sbc $13                            ; @50A3 E5 13
    sec                                ; @50A5 38
L50A6:
    rol $1A                            ; @50A6 26 1A
    rol $1B                            ; @50A8 26 1B
    rol $16                            ; @50AA 26 16
    rol a                              ; @50AC 2A
    bcs L50C7                          ; @50AD B0 18
    cmp $13                            ; @50AF C5 13
    bcc L50D2                          ; @50B1 90 1F
    bne L50BB                          ; @50B3 D0 06
    ldx $16                            ; @50B5 A6 16
    cpx $12                            ; @50B7 E4 12
    bcc L50D2                          ; @50B9 90 17
L50BB:
    tax                                ; @50BB AA
    lda $16                            ; @50BC A5 16
    sbc $12                            ; @50BE E5 12
    sta $16                            ; @50C0 85 16
    txa                                ; @50C2 8A
    sbc $13                            ; @50C3 E5 13
    bcs L50D2                          ; @50C5 B0 0B
L50C7:
    tax                                ; @50C7 AA
    lda $16                            ; @50C8 A5 16
    sbc $12                            ; @50CA E5 12
    sta $16                            ; @50CC 85 16
    txa                                ; @50CE 8A
    sbc $13                            ; @50CF E5 13
    sec                                ; @50D1 38
L50D2:
    rol $1A                            ; @50D2 26 1A
    rol $1B                            ; @50D4 26 1B
    sta $17                            ; @50D6 85 17
    clc                                ; @50D8 18
    rts                                ; @50D9 60
L50DA:
    lda #$00                           ; @50DA A9 00
    sta $1A                            ; @50DC 85 1A
    sta $1B                            ; @50DE 85 1B
    rts                                ; @50E0 60
