; mul_u32_u32_u64 — exact executable source mirror for v3_reu_512k
; Legacy API: MATH_UMUL32 at $30B0
; GENERATED by tools/publish_standalone_sources.py. Do not hand-edit.
; Shipped image: v3_reu_512k/resident/math_v3_reu_512k_game_math.prg
; Canonical integrated/relocatable source: relocatable_source/v3_reu_512k/math_relocatable.asm
; This file contains every executable instruction statically reachable from the public entry after MATH_INIT.
; Shared immutable lookup/data tables and REU payload data are intentionally not duplicated here.
; The address/byte annotations make this a mechanically auditable source view of the shipped executable.
; Reachable instructions: 151.
!cpu 6510

; ---- executable island $30B0 ----
* = $30B0
mul_u32_u32_u64:
MATH_UMUL32:
    jmp L5903                          ; @30B0 4C 03 59
; ---- executable island $5805 ----
* = $5805
L5805:
    clc                                ; @5805 18
    adc ($3D),y                        ; @5806 71 3D
    sta $1D,x                          ; @5808 95 1D
    lda #$01                           ; @580A A9 01
    adc ($3F),y                        ; @580C 71 3F
    bcc L5844                          ; @580E 90 34
L5810:
    clc                                ; @5810 18
    adc ($41),y                        ; @5811 71 41
    sta $12,x                          ; @5813 95 12
    lda #$01                           ; @5815 A9 01
    adc ($4F),y                        ; @5817 71 4F
    bcc L5852                          ; @5819 90 37
L581B:
    clc                                ; @581B 18
    adc ($51),y                        ; @581C 71 51
    sta $16,x                          ; @581E 95 16
    lda #$01                           ; @5820 A9 01
    adc ($68),y                        ; @5822 71 68
    bcc L5860                          ; @5824 90 3A
L5826:
    sta $1A,x                          ; @5826 95 1A
    ldy $C004,x                        ; @5828 BC 04 C0
L582B:
    lda $7000,y                        ; @582B B9 00 70
    adc $7400,y                        ; @582E 79 00 74
    sta $0E,x                          ; @5831 95 0E
    lda $7200,y                        ; @5833 B9 00 72
    adc $7600,y                        ; @5836 79 00 76
    adc $7000,y                        ; @5839 79 00 70
    bcs L5805                          ; @583C B0 C7
    adc ($3D),y                        ; @583E 71 3D
    sta $1D,x                          ; @5840 95 1D
    lda ($3F),y                        ; @5842 B1 3F
L5844:
    adc $7600,y                        ; @5844 79 00 76
    adc $7000,y                        ; @5847 79 00 70
    bcs L5810                          ; @584A B0 C4
    adc ($41),y                        ; @584C 71 41
    sta $12,x                          ; @584E 95 12
    lda ($4F),y                        ; @5850 B1 4F
L5852:
    adc $7600,y                        ; @5852 79 00 76
    adc $7000,y                        ; @5855 79 00 70
    bcs L581B                          ; @5858 B0 C1
    adc ($51),y                        ; @585A 71 51
    sta $16,x                          ; @585C 95 16
    lda ($68),y                        ; @585E B1 68
L5860:
    adc $7600,y                        ; @5860 79 00 76
    dex                                ; @5863 CA
    bpl L5826                          ; @5864 10 C0
    tax                                ; @5866 AA
    ldy $1A                            ; @5867 A4 1A
    clc                                ; @5869 18
    lda $1D                            ; @586A A5 1D
    adc $0F                            ; @586C 65 0F
    sta $C009                          ; @586E 8D 09 C0
    lda $1E                            ; @5871 A5 1E
    adc $10                            ; @5873 65 10
    bcc L587C                          ; @5875 90 05
    inc $11                            ; @5877 E6 11
    beq L58CB                          ; @5879 F0 50
    clc                                ; @587B 18
L587C:
    adc $12                            ; @587C 65 12
    sta $C00A                          ; @587E 8D 0A C0
    lda $13                            ; @5881 A5 13
    adc $16                            ; @5883 65 16
    bcc L5889                          ; @5885 90 02
    inx                                ; @5887 E8
    clc                                ; @5888 18
L5889:
    adc $11                            ; @5889 65 11
    bcc L5891                          ; @588B 90 04
    inx                                ; @588D E8
    beq L58CE                          ; @588E F0 3E
    clc                                ; @5890 18
L5891:
    adc $1F                            ; @5891 65 1F
    sta $C00B                          ; @5893 8D 0B C0
    txa                                ; @5896 8A
    adc $17                            ; @5897 65 17
    bcc L589D                          ; @5899 90 02
    iny                                ; @589B C8
    clc                                ; @589C 18
L589D:
    adc $20                            ; @589D 65 20
    bcc L58A5                          ; @589F 90 04
    iny                                ; @58A1 C8
    beq L58F1                          ; @58A2 F0 4D
    clc                                ; @58A4 18
L58A5:
    adc $14                            ; @58A5 65 14
    sta $C00C                          ; @58A7 8D 0C C0
    tya                                ; @58AA 98
    adc $15                            ; @58AB 65 15
    bcc L58B2                          ; @58AD 90 03
    inc $1B                            ; @58AF E6 1B
    clc                                ; @58B1 18
L58B2:
    adc $18                            ; @58B2 65 18
    sta $C00D                          ; @58B4 8D 0D C0
    lda $19                            ; @58B7 A5 19
    adc $1B                            ; @58B9 65 1B
    sta $C00E                          ; @58BB 8D 0E C0
    lda $1C                            ; @58BE A5 1C
    adc #$00                           ; @58C0 69 00
    sta $C00F                          ; @58C2 8D 0F C0
    lda $0E                            ; @58C5 A5 0E
    sta $C008                          ; @58C7 8D 08 C0
    rts                                ; @58CA 60
L58CB:
    jmp L58D1                          ; @58CB 4C D1 58
L58CE:
    jmp L58E3                          ; @58CE 4C E3 58
L58D1:
    inc $20                            ; @58D1 E6 20
    bne L58DF                          ; @58D3 D0 0A
    inc $15                            ; @58D5 E6 15
    bne L58DF                          ; @58D7 D0 06
    inc $19                            ; @58D9 E6 19
    bne L58DF                          ; @58DB D0 02
    inc $1C                            ; @58DD E6 1C
L58DF:
    clc                                ; @58DF 18
    jmp L587C                          ; @58E0 4C 7C 58
L58E3:
    inc $15                            ; @58E3 E6 15
    bne L58ED                          ; @58E5 D0 06
    inc $19                            ; @58E7 E6 19
    bne L58ED                          ; @58E9 D0 02
    inc $1C                            ; @58EB E6 1C
L58ED:
    clc                                ; @58ED 18
    jmp L5891                          ; @58EE 4C 91 58
L58F1:
    inc $19                            ; @58F1 E6 19
    bne L58F7                          ; @58F3 D0 02
    inc $1C                            ; @58F5 E6 1C
L58F7:
    clc                                ; @58F7 18
    jmp L58A5                          ; @58F8 4C A5 58
; ---- executable island $5903 ----
* = $5903
L5903:
    lda $C003                          ; @5903 AD 03 C0
    ldx #$03                           ; @5906 A2 03
    sec                                ; @5908 38
    ldy $C007                          ; @5909 AC 07 C0
    sta $68                            ; @590C 85 68
    sta $5856                          ; @590E 8D 56 58
    eor #$FF                           ; @5911 49 FF
    sta $51                            ; @5913 85 51
    sta $5861                          ; @5915 8D 61 58
    lda $C000                          ; @5918 AD 00 C0
    sta $582C                          ; @591B 8D 2C 58
    sta $5834                          ; @591E 8D 34 58
    eor #$FF                           ; @5921 49 FF
    sta $582F                          ; @5923 8D 2F 58
    sta $5837                          ; @5926 8D 37 58
    lda $C001                          ; @5929 AD 01 C0
    sta $3F                            ; @592C 85 3F
    sta $583A                          ; @592E 8D 3A 58
    eor #$FF                           ; @5931 49 FF
    sta $3D                            ; @5933 85 3D
    sta $5845                          ; @5935 8D 45 58
    lda $C002                          ; @5938 AD 02 C0
    sta $4F                            ; @593B 85 4F
    sta $5848                          ; @593D 8D 48 58
    eor #$FF                           ; @5940 49 FF
    sta $41                            ; @5942 85 41
    sta $5853                          ; @5944 8D 53 58
    jmp L582B                          ; @5947 4C 2B 58
