; MATH_SMUL24 — exact native-signed executable source mirror for v4_reu_16m
; GENERATED by tools/publish_native_signed_sources.py. Do not hand-edit.
; Canonical integrated build source remains relocatable_source/v4_reu_16m/math_relocatable.asm
; This mirror contains every executable instruction reachable from this signed API after MATH_INIT.
; Immutable lookup/data tables are intentionally not duplicated here.
; Corresponding unsigned API: MATH_UMUL24. Executable overlap: 0 instructions.
; Public entry: $3BF0. Reachable signed instructions: 191.
; Each instruction has an @ADDR byte annotation used by the publication validator.
!cpu 6510

; ---- executable island $1400 ----
* = $1400
L1400:
    sta $35                            ; @1400 85 35
    eor #$FF                           ; @1402 49 FF
    sta $33                            ; @1404 85 33
    sta $37                            ; @1406 85 37
    txa                                ; @1408 8A
    sta $25                            ; @1409 85 25
    eor #$FF                           ; @140B 49 FF
    sta $23                            ; @140D 85 23
    sta $27                            ; @140F 85 27
    lda $29                            ; @1411 A5 29
    sta $2D                            ; @1413 85 2D
    eor #$FF                           ; @1415 49 FF
    sta $2B                            ; @1417 85 2B
    sta $2F                            ; @1419 85 2F
    sec                                ; @141B 38
    lda ($21),y                        ; @141C B1 21
    adc ($23),y                        ; @141E 71 23
    sta $151E                          ; @1420 8D 1E 15
    lda ($25),y                        ; @1423 B1 25
    adc ($27),y                        ; @1425 71 27
    adc ($29),y                        ; @1427 71 29
    bcs L1473                          ; @1429 B0 48
    adc ($2B),y                        ; @142B 71 2B
    sta $14F2                          ; @142D 8D F2 14
    lda ($2D),y                        ; @1430 B1 2D
    adc ($2F),y                        ; @1432 71 2F
    adc ($31),y                        ; @1434 71 31
    bcs L1483                          ; @1436 B0 4B
L1438:
    adc ($33),y                        ; @1438 71 33
    sta $14F8                          ; @143A 8D F8 14
    lda ($35),y                        ; @143D B1 35
L143F:
    adc ($37),y                        ; @143F 71 37
    sta $14FF                          ; @1441 8D FF 14
    ldy #$00                           ; @1444 A0 00
    lda ($21),y                        ; @1446 B1 21
    adc ($23),y                        ; @1448 71 23
    sta $14F4                          ; @144A 8D F4 14
    lda ($25),y                        ; @144D B1 25
    adc ($27),y                        ; @144F 71 27
    adc ($29),y                        ; @1451 71 29
    bcs L1490                          ; @1453 B0 3B
    adc ($2B),y                        ; @1455 71 2B
    sta $14FA                          ; @1457 8D FA 14
    lda ($2D),y                        ; @145A B1 2D
    adc ($2F),y                        ; @145C 71 2F
    adc ($31),y                        ; @145E 71 31
    bcs L14A0                          ; @1460 B0 3E
L1462:
    adc ($33),y                        ; @1462 71 33
    sta $1501                          ; @1464 8D 01 15
    lda ($35),y                        ; @1467 B1 35
L1469:
    adc ($37),y                        ; @1469 71 37
    sta $1515                          ; @146B 8D 15 15
    ldy #$00                           ; @146E A0 00
    jmp L14CA                          ; @1470 4C CA 14
L1473:
    clc                                ; @1473 18
    adc ($2B),y                        ; @1474 71 2B
    sta $14F2                          ; @1476 8D F2 14
    lda #$01                           ; @1479 A9 01
    adc ($2D),y                        ; @147B 71 2D
    adc ($2F),y                        ; @147D 71 2F
    adc ($31),y                        ; @147F 71 31
    bcc L1438                          ; @1481 90 B5
L1483:
    clc                                ; @1483 18
    adc ($33),y                        ; @1484 71 33
    sta $14F8                          ; @1486 8D F8 14
    lda #$01                           ; @1489 A9 01
    adc ($35),y                        ; @148B 71 35
    jmp L143F                          ; @148D 4C 3F 14
L1490:
    clc                                ; @1490 18
    adc ($2B),y                        ; @1491 71 2B
    sta $14FA                          ; @1493 8D FA 14
    lda #$01                           ; @1496 A9 01
    adc ($2D),y                        ; @1498 71 2D
    adc ($2F),y                        ; @149A 71 2F
    adc ($31),y                        ; @149C 71 31
    bcc L1462                          ; @149E 90 C2
L14A0:
    clc                                ; @14A0 18
    adc ($33),y                        ; @14A1 71 33
    sta $1501                          ; @14A3 8D 01 15
    lda #$01                           ; @14A6 A9 01
    adc ($35),y                        ; @14A8 71 35
    jmp L1469                          ; @14AA 4C 69 14
L14AD:
    clc                                ; @14AD 18
    adc ($2B),y                        ; @14AE 71 2B
    sta $1511                          ; @14B0 8D 11 15
    lda #$01                           ; @14B3 A9 01
    adc ($2D),y                        ; @14B5 71 2D
    adc ($2F),y                        ; @14B7 71 2F
    adc ($31),y                        ; @14B9 71 31
    bcc L14E6                          ; @14BB 90 29
L14BD:
    clc                                ; @14BD 18
    adc ($33),y                        ; @14BE 71 33
    sta $1517                          ; @14C0 8D 17 15
    lda #$01                           ; @14C3 A9 01
    adc ($35),y                        ; @14C5 71 35
    jmp L14ED                          ; @14C7 4C ED 14
L14CA:
    lda ($21),y                        ; @14CA B1 21
    adc ($23),y                        ; @14CC 71 23
    sta $150C                          ; @14CE 8D 0C 15
    lda ($25),y                        ; @14D1 B1 25
    adc ($27),y                        ; @14D3 71 27
    adc ($29),y                        ; @14D5 71 29
    bcs L14AD                          ; @14D7 B0 D4
    adc ($2B),y                        ; @14D9 71 2B
    sta $1511                          ; @14DB 8D 11 15
    lda ($2D),y                        ; @14DE B1 2D
    adc ($2F),y                        ; @14E0 71 2F
    adc ($31),y                        ; @14E2 71 31
    bcs L14BD                          ; @14E4 B0 D7
L14E6:
    adc ($33),y                        ; @14E6 71 33
    sta $1517                          ; @14E8 8D 17 15
    lda ($35),y                        ; @14EB B1 35
L14ED:
    adc ($37),y                        ; @14ED 71 37
    tax                                ; @14EF AA
    clc                                ; @14F0 18
    lda #$00                           ; @14F1 A9 00
    adc #$00                           ; @14F3 69 00
    sta $2B                            ; @14F5 85 2B
    lda #$00                           ; @14F7 A9 00
    adc #$00                           ; @14F9 69 00
    sta $150A                          ; @14FB 8D 0A 15
    lda #$00                           ; @14FE A9 00
    adc #$00                           ; @1500 69 00
    tay                                ; @1502 A8
    bcc L1509                          ; @1503 90 04
    clc                                ; @1505 18
    inc $1515                          ; @1506 EE 15 15
L1509:
    lda #$00                           ; @1509 A9 00
    adc #$00                           ; @150B 69 00
    sta $33                            ; @150D 85 33
    tya                                ; @150F 98
    adc #$00                           ; @1510 69 00
    sta $27                            ; @1512 85 27
    lda #$00                           ; @1514 A9 00
    adc #$00                           ; @1516 69 00
    sta $2F                            ; @1518 85 2F
    txa                                ; @151A 8A
    adc #$00                           ; @151B 69 00
    rts                                ; @151D 60
; ---- executable island $2200 ----
* = $2200
L2200:
    lda $C000                          ; @2200 AD 00 C0
    sta $21                            ; @2203 85 21
    lda $C001                          ; @2205 AD 01 C0
    sta $29                            ; @2208 85 29
    lda $C002                          ; @220A AD 02 C0
    sta $31                            ; @220D 85 31
    lda $C005                          ; @220F AD 05 C0
    sta $1445                          ; @2212 8D 45 14
    lda $C006                          ; @2215 AD 06 C0
    sta $146F                          ; @2218 8D 6F 14
    lda $C002                          ; @221B AD 02 C0
    ldx $C000                          ; @221E AE 00 C0
    ldy $C004                          ; @2221 AC 04 C0
    jsr L1400                          ; @2224 20 00 14
    sta $C00D                          ; @2227 8D 0D C0
    lda $151E                          ; @222A AD 1E 15
    sta $C008                          ; @222D 8D 08 C0
    lda $2B                            ; @2230 A5 2B
    sta $C009                          ; @2232 8D 09 C0
    lda $33                            ; @2235 A5 33
    sta $C00A                          ; @2237 8D 0A C0
    lda $27                            ; @223A A5 27
    sta $C00B                          ; @223C 8D 0B C0
    lda $2F                            ; @223F A5 2F
    sta $C00C                          ; @2241 8D 0C C0
    lda $C002                          ; @2244 AD 02 C0
    bpl L2265                          ; @2247 10 1C
    sec                                ; @2249 38
    lda $C00B                          ; @224A AD 0B C0
    sbc $C004                          ; @224D ED 04 C0
    sta $C00B                          ; @2250 8D 0B C0
    lda $C00C                          ; @2253 AD 0C C0
    sbc $C005                          ; @2256 ED 05 C0
    sta $C00C                          ; @2259 8D 0C C0
    lda $C00D                          ; @225C AD 0D C0
    sbc $C006                          ; @225F ED 06 C0
    sta $C00D                          ; @2262 8D 0D C0
L2265:
    lda $C006                          ; @2265 AD 06 C0
    bpl L2286                          ; @2268 10 1C
    sec                                ; @226A 38
    lda $C00B                          ; @226B AD 0B C0
    sbc $C000                          ; @226E ED 00 C0
    sta $C00B                          ; @2271 8D 0B C0
    lda $C00C                          ; @2274 AD 0C C0
    sbc $C001                          ; @2277 ED 01 C0
    sta $C00C                          ; @227A 8D 0C C0
    lda $C00D                          ; @227D AD 0D C0
    sbc $C002                          ; @2280 ED 02 C0
    sta $C00D                          ; @2283 8D 0D C0
L2286:
    clc                                ; @2286 18
    rts                                ; @2287 60
; ---- executable island $3BF0 ----
* = $3BF0
L3BF0:
    jmp L2200                          ; @3BF0 4C 00 22
