; div_u16_u16_u16_16 — exact executable source mirror for v5_hybrid_lowzp
; Legacy API: MATH_UDIV16 at $3140
; GENERATED by tools/publish_standalone_sources.py. Do not hand-edit.
; Shipped image: v5_hybrid_lowzp/resident/math_v5_hybrid_lowzp_game_math.prg
; Canonical integrated/relocatable source: relocatable_source/v1_balanced/math_relocatable.asm + tools/build_hybrid.py
; This file contains every executable instruction statically reachable from the public entry after MATH_INIT.
; Shared immutable lookup/data tables and REU payload data are intentionally not duplicated here.
; The address/byte annotations make this a mechanically auditable source view of the shipped executable.
; Reachable instructions: 626.
!cpu 6510

; ---- executable island $3140 ----
* = $3140
div_u16_u16_u16_16:
MATH_UDIV16:
    jmp LB800                          ; @3140 4C 00 B8
; ---- executable island $B800 ----
* = $B800
LB800:
    !byte $A7, $11    ; LAX zp         ; @B800 AF 11 C0
    cmp $C015                          ; @B803 CD 15 C0
    bcs LB83A                          ; @B806 B0 32
LB808:
    lda #$00                           ; @B808 A9 00
    sta $C018                          ; @B80A 8D 18 C0
    sta $C019                          ; @B80D 8D 19 C0
    lda $C010                          ; @B810 AD 10 C0
    sta $C01C                          ; @B813 8D 1C C0
    stx $C01D                          ; @B816 8E 1D C0
    rts                                ; @B819 60
LB81A:
    lda $C010                          ; @B81A AD 10 C0
    sbc $C014                          ; @B81D ED 14 C0
    bcc LB808                          ; @B820 90 E6
    cpx #$01                           ; @B822 E0 01
    bcc LB837                          ; @B824 90 11
    sta $C01C                          ; @B826 8D 1C C0
    !byte $0B, $00    ; ANC #imm       ; @B829 0B 00
    sta $C01D                          ; @B82B 8D 1D C0
    sta $C019                          ; @B82E 8D 19 C0
    lda #$01                           ; @B831 A9 01
    sta $C018                          ; @B833 8D 18 C0
    rts                                ; @B836 60
LB837:
    jmp LBD64                          ; @B837 4C 64 BD
LB83A:
    beq LB81A                          ; @B83A F0 DE
    lda $C010                          ; @B83C AD 10 C0
    sbc $C014                          ; @B83F ED 14 C0
    sta $C01C                          ; @B842 8D 1C C0
    txa                                ; @B845 8A
    sbc $C015                          ; @B846 ED 15 C0
    cmp $C015                          ; @B849 CD 15 C0
    bcc LB851                          ; @B84C 90 03
    jmp LB8E9                          ; @B84E 4C E9 B8
LB851:
    sta $C01D                          ; @B851 8D 1D C0
    lda #$00                           ; @B854 A9 00
    sta $C019                          ; @B856 8D 19 C0
    lda #$01                           ; @B859 A9 01
    sta $C018                          ; @B85B 8D 18 C0
    rts                                ; @B85E 60
LB85F:
    cmp $BDBA,x                        ; @B85F DD BA BD
    bcc LB867                          ; @B862 90 03
    jmp LBC02                          ; @B864 4C 02 BC
LB867:
    sec                                ; @B867 38
    bcc LB86D                          ; @B868 90 03
    jmp LB8F5                          ; @B86A 4C F5 B8
LB86D:
    lda $C01C                          ; @B86D AD 1C C0
    sbc $C014                          ; @B870 ED 14 C0
    bcs LB87F                          ; @B873 B0 0A
    txa                                ; @B875 8A
LB876:
    sta $C01D                          ; @B876 8D 1D C0
    lda #$02                           ; @B879 A9 02
    sta $C018                          ; @B87B 8D 18 C0
    rts                                ; @B87E 60
LB87F:
    sta $C01C                          ; @B87F 8D 1C C0
    !byte $0B, $00    ; ANC #imm       ; @B882 0B 00
    bcs LB889                          ; @B884 B0 03
    jmp LB892                          ; @B886 4C 92 B8
LB889:
    lda $C01C                          ; @B889 AD 1C C0
    sbc $C014                          ; @B88C ED 14 C0
    bcs LB89B                          ; @B88F B0 0A
    txa                                ; @B891 8A
LB892:
    sta $C01D                          ; @B892 8D 1D C0
    lda #$03                           ; @B895 A9 03
    sta $C018                          ; @B897 8D 18 C0
    rts                                ; @B89A 60
LB89B:
    sta $C01C                          ; @B89B 8D 1C C0
    !byte $0B, $00    ; ANC #imm       ; @B89E 0B 00
    bcs LB8A5                          ; @B8A0 B0 03
    jmp LB8AE                          ; @B8A2 4C AE B8
LB8A5:
    lda $C01C                          ; @B8A5 AD 1C C0
    sbc $C014                          ; @B8A8 ED 14 C0
    bcs LB8B7                          ; @B8AB B0 0A
    txa                                ; @B8AD 8A
LB8AE:
    sta $C01D                          ; @B8AE 8D 1D C0
    lda #$04                           ; @B8B1 A9 04
    sta $C018                          ; @B8B3 8D 18 C0
    rts                                ; @B8B6 60
LB8B7:
    sta $C01C                          ; @B8B7 8D 1C C0
    !byte $0B, $00    ; ANC #imm       ; @B8BA 0B 00
    jmp LBA1F                          ; @B8BC 4C 1F BA
LB8BF:
    tax                                ; @B8BF AA
    lda $C01C                          ; @B8C0 AD 1C C0
    sbc $C014                          ; @B8C3 ED 14 C0
    bcs LB8D6                          ; @B8C6 B0 0E
    stx $C01D                          ; @B8C8 8E 1D C0
    lda #$00                           ; @B8CB A9 00
    sta $C019                          ; @B8CD 8D 19 C0
    lda #$01                           ; @B8D0 A9 01
    sta $C018                          ; @B8D2 8D 18 C0
    rts                                ; @B8D5 60
LB8D6:
    dex                                ; @B8D6 CA
    bpl LB8DC                          ; @B8D7 10 03
    jmp LBD64                          ; @B8D9 4C 64 BD
LB8DC:
    sta $C01C                          ; @B8DC 8D 1C C0
    !byte $0B, $00    ; ANC #imm       ; @B8DF 0B 00
    sta $C019                          ; @B8E1 8D 19 C0
    bcs LB8E9                          ; @B8E4 B0 03
    jmp LB876                          ; @B8E6 4C 76 B8
LB8E9:
    beq LB8BF                          ; @B8E9 F0 D4
    ldx $C015                          ; @B8EB AE 15 C0
    cpx #$0F                           ; @B8EE E0 0F
    bcs LB8F5                          ; @B8F0 B0 03
    jmp LB85F                          ; @B8F2 4C 5F B8
LB8F5:
    ldy #$00                           ; @B8F5 A0 00
    sty $C019                          ; @B8F7 8C 19 C0
    tay                                ; @B8FA A8
    lda $C01C                          ; @B8FB AD 1C C0
    sbc $C014                          ; @B8FE ED 14 C0
    sta $C01C                          ; @B901 8D 1C C0
    tya                                ; @B904 98
    sbc $C015                          ; @B905 ED 15 C0
    cmp $C015                          ; @B908 CD 15 C0
    bcs LB910                          ; @B90B B0 03
    jmp LB876                          ; @B90D 4C 76 B8
LB910:
    bne LB915                          ; @B910 D0 03
    jmp LB86D                          ; @B912 4C 6D B8
LB915:
    tay                                ; @B915 A8
    lda $C01C                          ; @B916 AD 1C C0
    sbc $C014                          ; @B919 ED 14 C0
    sta $C01C                          ; @B91C 8D 1C C0
    tya                                ; @B91F 98
    sbc $C015                          ; @B920 ED 15 C0
    cmp $C015                          ; @B923 CD 15 C0
    bcs LB92B                          ; @B926 B0 03
    jmp LB892                          ; @B928 4C 92 B8
LB92B:
    bne LB930                          ; @B92B D0 03
    jmp LB889                          ; @B92D 4C 89 B8
LB930:
    tay                                ; @B930 A8
    lda $C01C                          ; @B931 AD 1C C0
    sbc $C014                          ; @B934 ED 14 C0
    sta $C01C                          ; @B937 8D 1C C0
    tya                                ; @B93A 98
    sbc $C015                          ; @B93B ED 15 C0
    cmp $C015                          ; @B93E CD 15 C0
    bcs LB946                          ; @B941 B0 03
    jmp LB8AE                          ; @B943 4C AE B8
LB946:
    bne LB94B                          ; @B946 D0 03
    jmp LB8A5                          ; @B948 4C A5 B8
LB94B:
    tay                                ; @B94B A8
    lda $C01C                          ; @B94C AD 1C C0
    sbc $C014                          ; @B94F ED 14 C0
    sta $C01C                          ; @B952 8D 1C C0
    tya                                ; @B955 98
    sbc $C015                          ; @B956 ED 15 C0
    cmp $C015                          ; @B959 CD 15 C0
    bcs LB961                          ; @B95C B0 03
    jmp LBA1F                          ; @B95E 4C 1F BA
LB961:
    bne LB966                          ; @B961 D0 03
    jmp LBA16                          ; @B963 4C 16 BA
LB966:
    tay                                ; @B966 A8
    lda $C01C                          ; @B967 AD 1C C0
    sbc $C014                          ; @B96A ED 14 C0
    sta $C01C                          ; @B96D 8D 1C C0
    tya                                ; @B970 98
    sbc $C015                          ; @B971 ED 15 C0
    cmp $C015                          ; @B974 CD 15 C0
    bcs LB97C                          ; @B977 B0 03
    jmp LBA31                          ; @B979 4C 31 BA
LB97C:
    bne LB981                          ; @B97C D0 03
    jmp LBA28                          ; @B97E 4C 28 BA
LB981:
    tay                                ; @B981 A8
    lda $C01C                          ; @B982 AD 1C C0
    sbc $C014                          ; @B985 ED 14 C0
    sta $C01C                          ; @B988 8D 1C C0
    tya                                ; @B98B 98
    sbc $C015                          ; @B98C ED 15 C0
    cmp $C015                          ; @B98F CD 15 C0
    bcs LB997                          ; @B992 B0 03
    jmp LBA43                          ; @B994 4C 43 BA
LB997:
    bne LB99C                          ; @B997 D0 03
    jmp LBA3A                          ; @B999 4C 3A BA
LB99C:
    tay                                ; @B99C A8
    lda $C01C                          ; @B99D AD 1C C0
    sbc $C014                          ; @B9A0 ED 14 C0
    sta $C01C                          ; @B9A3 8D 1C C0
    tya                                ; @B9A6 98
    sbc $C015                          ; @B9A7 ED 15 C0
    cmp $C015                          ; @B9AA CD 15 C0
    bcs LB9B2                          ; @B9AD B0 03
    jmp LBA55                          ; @B9AF 4C 55 BA
LB9B2:
    bne LB9B7                          ; @B9B2 D0 03
    jmp LBA4C                          ; @B9B4 4C 4C BA
LB9B7:
    tay                                ; @B9B7 A8
    lda $C01C                          ; @B9B8 AD 1C C0
    sbc $C014                          ; @B9BB ED 14 C0
    sta $C01C                          ; @B9BE 8D 1C C0
    tya                                ; @B9C1 98
    sbc $C015                          ; @B9C2 ED 15 C0
    cmp $C015                          ; @B9C5 CD 15 C0
    bcs LB9CD                          ; @B9C8 B0 03
    jmp LBA67                          ; @B9CA 4C 67 BA
LB9CD:
    bne LB9D2                          ; @B9CD D0 03
    jmp LBA5E                          ; @B9CF 4C 5E BA
LB9D2:
    tay                                ; @B9D2 A8
    lda $C01C                          ; @B9D3 AD 1C C0
    sbc $C014                          ; @B9D6 ED 14 C0
    sta $C01C                          ; @B9D9 8D 1C C0
    tya                                ; @B9DC 98
    sbc $C015                          ; @B9DD ED 15 C0
    cmp $C015                          ; @B9E0 CD 15 C0
    bcs LB9E8                          ; @B9E3 B0 03
    jmp LBA79                          ; @B9E5 4C 79 BA
LB9E8:
    bne LB9ED                          ; @B9E8 D0 03
    jmp LBA70                          ; @B9EA 4C 70 BA
LB9ED:
    tay                                ; @B9ED A8
    lda $C01C                          ; @B9EE AD 1C C0
    sbc $C014                          ; @B9F1 ED 14 C0
    sta $C01C                          ; @B9F4 8D 1C C0
    tya                                ; @B9F7 98
    sbc $C015                          ; @B9F8 ED 15 C0
    cmp $C015                          ; @B9FB CD 15 C0
    bcs LBA03                          ; @B9FE B0 03
    jmp LBA8B                          ; @BA00 4C 8B BA
LBA03:
    beq LBA82                          ; @BA03 F0 7D
    tay                                ; @BA05 A8
    lda $C01C                          ; @BA06 AD 1C C0
    sbc $C014                          ; @BA09 ED 14 C0
    sta $C01C                          ; @BA0C 8D 1C C0
    tya                                ; @BA0F 98
    sbc $C015                          ; @BA10 ED 15 C0
    jmp LBAC5                          ; @BA13 4C C5 BA
LBA16:
    lda $C01C                          ; @BA16 AD 1C C0
    sbc $C014                          ; @BA19 ED 14 C0
    bcs LBA94                          ; @BA1C B0 76
    txa                                ; @BA1E 8A
LBA1F:
    sta $C01D                          ; @BA1F 8D 1D C0
    lda #$05                           ; @BA22 A9 05
    sta $C018                          ; @BA24 8D 18 C0
    rts                                ; @BA27 60
LBA28:
    lda $C01C                          ; @BA28 AD 1C C0
    sbc $C014                          ; @BA2B ED 14 C0
    bcs LBA9B                          ; @BA2E B0 6B
    txa                                ; @BA30 8A
LBA31:
    sta $C01D                          ; @BA31 8D 1D C0
    lda #$06                           ; @BA34 A9 06
    sta $C018                          ; @BA36 8D 18 C0
    rts                                ; @BA39 60
LBA3A:
    lda $C01C                          ; @BA3A AD 1C C0
    sbc $C014                          ; @BA3D ED 14 C0
    bcs LBAA2                          ; @BA40 B0 60
    txa                                ; @BA42 8A
LBA43:
    sta $C01D                          ; @BA43 8D 1D C0
    lda #$07                           ; @BA46 A9 07
    sta $C018                          ; @BA48 8D 18 C0
    rts                                ; @BA4B 60
LBA4C:
    lda $C01C                          ; @BA4C AD 1C C0
    sbc $C014                          ; @BA4F ED 14 C0
    bcs LBAA9                          ; @BA52 B0 55
    txa                                ; @BA54 8A
LBA55:
    sta $C01D                          ; @BA55 8D 1D C0
    lda #$08                           ; @BA58 A9 08
    sta $C018                          ; @BA5A 8D 18 C0
    rts                                ; @BA5D 60
LBA5E:
    lda $C01C                          ; @BA5E AD 1C C0
    sbc $C014                          ; @BA61 ED 14 C0
    bcs LBAB0                          ; @BA64 B0 4A
    txa                                ; @BA66 8A
LBA67:
    sta $C01D                          ; @BA67 8D 1D C0
    lda #$09                           ; @BA6A A9 09
    sta $C018                          ; @BA6C 8D 18 C0
    rts                                ; @BA6F 60
LBA70:
    lda $C01C                          ; @BA70 AD 1C C0
    sbc $C014                          ; @BA73 ED 14 C0
    bcs LBAB7                          ; @BA76 B0 3F
    txa                                ; @BA78 8A
LBA79:
    sta $C01D                          ; @BA79 8D 1D C0
    lda #$0A                           ; @BA7C A9 0A
    sta $C018                          ; @BA7E 8D 18 C0
    rts                                ; @BA81 60
LBA82:
    lda $C01C                          ; @BA82 AD 1C C0
    sbc $C014                          ; @BA85 ED 14 C0
    bcs LBABE                          ; @BA88 B0 34
    txa                                ; @BA8A 8A
LBA8B:
    sta $C01D                          ; @BA8B 8D 1D C0
    lda #$0B                           ; @BA8E A9 0B
    sta $C018                          ; @BA90 8D 18 C0
    rts                                ; @BA93 60
LBA94:
    sta $C01C                          ; @BA94 8D 1C C0
    !byte $0B, $00    ; ANC #imm       ; @BA97 0B 00
    bcc LBA31                          ; @BA99 90 96
LBA9B:
    sta $C01C                          ; @BA9B 8D 1C C0
    !byte $0B, $00    ; ANC #imm       ; @BA9E 0B 00
    bcc LBA43                          ; @BAA0 90 A1
LBAA2:
    sta $C01C                          ; @BAA2 8D 1C C0
    !byte $0B, $00    ; ANC #imm       ; @BAA5 0B 00
    bcc LBA55                          ; @BAA7 90 AC
LBAA9:
    sta $C01C                          ; @BAA9 8D 1C C0
    !byte $0B, $00    ; ANC #imm       ; @BAAC 0B 00
    bcc LBA67                          ; @BAAE 90 B7
LBAB0:
    sta $C01C                          ; @BAB0 8D 1C C0
    !byte $0B, $00    ; ANC #imm       ; @BAB3 0B 00
    bcc LBA79                          ; @BAB5 90 C2
LBAB7:
    sta $C01C                          ; @BAB7 8D 1C C0
    !byte $0B, $00    ; ANC #imm       ; @BABA 0B 00
    bcc LBA8B                          ; @BABC 90 CD
LBABE:
    sta $C01C                          ; @BABE 8D 1C C0
    !byte $0B, $00    ; ANC #imm       ; @BAC1 0B 00
    bcc LBB37                          ; @BAC3 90 72
LBAC5:
    cmp $C015                          ; @BAC5 CD 15 C0
    bcc LBB37                          ; @BAC8 90 6D
    beq LBB2E                          ; @BACA F0 62
    tay                                ; @BACC A8
    lda $C01C                          ; @BACD AD 1C C0
    sbc $C014                          ; @BAD0 ED 14 C0
    sta $C01C                          ; @BAD3 8D 1C C0
    tya                                ; @BAD6 98
    sbc $C015                          ; @BAD7 ED 15 C0
    cmp $C015                          ; @BADA CD 15 C0
    bcc LBB50                          ; @BADD 90 71
    beq LBB47                          ; @BADF F0 66
    tay                                ; @BAE1 A8
    lda $C01C                          ; @BAE2 AD 1C C0
    sbc $C014                          ; @BAE5 ED 14 C0
    sta $C01C                          ; @BAE8 8D 1C C0
    tya                                ; @BAEB 98
    sbc $C015                          ; @BAEC ED 15 C0
    cmp $C015                          ; @BAEF CD 15 C0
    bcc LBB69                          ; @BAF2 90 75
    beq LBB60                          ; @BAF4 F0 6A
    tay                                ; @BAF6 A8
    lda $C01C                          ; @BAF7 AD 1C C0
    sbc $C014                          ; @BAFA ED 14 C0
    sta $C01C                          ; @BAFD 8D 1C C0
    tya                                ; @BB00 98
    sbc $C015                          ; @BB01 ED 15 C0
    cmp $C015                          ; @BB04 CD 15 C0
    bcc LBB82                          ; @BB07 90 79
    beq LBB79                          ; @BB09 F0 6E
    tay                                ; @BB0B A8
    lda $C01C                          ; @BB0C AD 1C C0
    sbc $C014                          ; @BB0F ED 14 C0
    sta $C01C                          ; @BB12 8D 1C C0
    tya                                ; @BB15 98
    sbc $C015                          ; @BB16 ED 15 C0
    cmp $C015                          ; @BB19 CD 15 C0
    bcc LBB9B                          ; @BB1C 90 7D
    beq LBB92                          ; @BB1E F0 72
    tay                                ; @BB20 A8
    lda $C01C                          ; @BB21 AD 1C C0
    sbc $C014                          ; @BB24 ED 14 C0
    sta $C01C                          ; @BB27 8D 1C C0
    tya                                ; @BB2A 98
    sbc $C015                          ; @BB2B ED 15 C0
LBB2E:
    lda $C01C                          ; @BB2E AD 1C C0
    sbc $C014                          ; @BB31 ED 14 C0
    bcs LBB40                          ; @BB34 B0 0A
    txa                                ; @BB36 8A
LBB37:
    sta $C01D                          ; @BB37 8D 1D C0
    lda #$0C                           ; @BB3A A9 0C
    sta $C018                          ; @BB3C 8D 18 C0
    rts                                ; @BB3F 60
LBB40:
    sta $C01C                          ; @BB40 8D 1C C0
    !byte $0B, $00    ; ANC #imm       ; @BB43 0B 00
    bcc LBB50                          ; @BB45 90 09
LBB47:
    lda $C01C                          ; @BB47 AD 1C C0
    sbc $C014                          ; @BB4A ED 14 C0
    bcs LBB59                          ; @BB4D B0 0A
    txa                                ; @BB4F 8A
LBB50:
    sta $C01D                          ; @BB50 8D 1D C0
    lda #$0D                           ; @BB53 A9 0D
    sta $C018                          ; @BB55 8D 18 C0
    rts                                ; @BB58 60
LBB59:
    sta $C01C                          ; @BB59 8D 1C C0
    !byte $0B, $00    ; ANC #imm       ; @BB5C 0B 00
    bcc LBB69                          ; @BB5E 90 09
LBB60:
    lda $C01C                          ; @BB60 AD 1C C0
    sbc $C014                          ; @BB63 ED 14 C0
    bcs LBB72                          ; @BB66 B0 0A
    txa                                ; @BB68 8A
LBB69:
    sta $C01D                          ; @BB69 8D 1D C0
    lda #$0E                           ; @BB6C A9 0E
    sta $C018                          ; @BB6E 8D 18 C0
    rts                                ; @BB71 60
LBB72:
    sta $C01C                          ; @BB72 8D 1C C0
    !byte $0B, $00    ; ANC #imm       ; @BB75 0B 00
    bcc LBB82                          ; @BB77 90 09
LBB79:
    lda $C01C                          ; @BB79 AD 1C C0
    sbc $C014                          ; @BB7C ED 14 C0
    bcs LBB8B                          ; @BB7F B0 0A
    txa                                ; @BB81 8A
LBB82:
    sta $C01D                          ; @BB82 8D 1D C0
    lda #$0F                           ; @BB85 A9 0F
    sta $C018                          ; @BB87 8D 18 C0
    rts                                ; @BB8A 60
LBB8B:
    sta $C01C                          ; @BB8B 8D 1C C0
    !byte $0B, $00    ; ANC #imm       ; @BB8E 0B 00
    bcc LBB9B                          ; @BB90 90 09
LBB92:
    lda $C01C                          ; @BB92 AD 1C C0
    sbc $C014                          ; @BB95 ED 14 C0
    bcs LBBA4                          ; @BB98 B0 0A
    txa                                ; @BB9A 8A
LBB9B:
    sta $C01D                          ; @BB9B 8D 1D C0
    lda #$10                           ; @BB9E A9 10
    sta $C018                          ; @BBA0 8D 18 C0
    rts                                ; @BBA3 60
LBBA4:
    sta $C01C                          ; @BBA4 8D 1C C0
    !byte $0B, $00    ; ANC #imm       ; @BBA7 0B 00
    sta $C01D                          ; @BBA9 8D 1D C0
    lda #$11                           ; @BBAC A9 11
    sta $C018                          ; @BBAE 8D 18 C0
    rts                                ; @BBB1 60
LBBB2:
    jmp LBD69                          ; @BBB2 4C 69 BD
LBBB5:
    jmp LBD64                          ; @BBB5 4C 64 BD
LBBB8:
    cpx #$01                           ; @BBB8 E0 01
    bcc LBBB5                          ; @BBBA 90 F9
    beq LBBB2                          ; @BBBC F0 F4
    lda $C010                          ; @BBBE AD 10 C0
    asl a                              ; @BBC1 0A
    sta $C018                          ; @BBC2 8D 18 C0
    lda $C011                          ; @BBC5 AD 11 C0
    rol a                              ; @BBC8 2A
    sta $C01C                          ; @BBC9 8D 1C C0
    lda #$00                           ; @BBCC A9 00
    sta $C019                          ; @BBCE 8D 19 C0
    rol a                              ; @BBD1 2A
    rol $C018                          ; @BBD2 2E 18 C0
    rol $C01C                          ; @BBD5 2E 1C C0
    rol a                              ; @BBD8 2A
    cmp $C015                          ; @BBD9 CD 15 C0
    bcc LBC25                          ; @BBDC 90 47
    beq LBBF0                          ; @BBDE F0 10
    tay                                ; @BBE0 A8
    lda $C01C                          ; @BBE1 AD 1C C0
    sbc $C014                          ; @BBE4 ED 14 C0
    sta $C01C                          ; @BBE7 8D 1C C0
    tya                                ; @BBEA 98
    sbc $C015                          ; @BBEB ED 15 C0
    bcs LBC25                          ; @BBEE B0 35
LBBF0:
    lda $C01C                          ; @BBF0 AD 1C C0
    sbc $C014                          ; @BBF3 ED 14 C0
    bcc LBBFF                          ; @BBF6 90 07
    sta $C01C                          ; @BBF8 8D 1C C0
    lda #$00                           ; @BBFB A9 00
    bcs LBC25                          ; @BBFD B0 26
LBBFF:
    txa                                ; @BBFF 8A
    bcc LBC25                          ; @BC00 90 23
LBC02:
    cpx #$04                           ; @BC02 E0 04
    bcc LBBB8                          ; @BC04 90 B2
    cpx #$08                           ; @BC06 E0 08
    bcs LBC67                          ; @BC08 B0 5D
    lda $C010                          ; @BC0A AD 10 C0
    asl a                              ; @BC0D 0A
    sta $C018                          ; @BC0E 8D 18 C0
    lda $C011                          ; @BC11 AD 11 C0
    rol a                              ; @BC14 2A
    sta $C01C                          ; @BC15 8D 1C C0
    lda #$00                           ; @BC18 A9 00
    sta $C019                          ; @BC1A 8D 19 C0
    rol a                              ; @BC1D 2A
    asl $C018                          ; @BC1E 0E 18 C0
    rol $C01C                          ; @BC21 2E 1C C0
    rol a                              ; @BC24 2A
LBC25:
    rol $C018                          ; @BC25 2E 18 C0
    rol $C01C                          ; @BC28 2E 1C C0
    rol a                              ; @BC2B 2A
    cmp $C015                          ; @BC2C CD 15 C0
    bcc LBC89                          ; @BC2F 90 58
    beq LBC43                          ; @BC31 F0 10
    tay                                ; @BC33 A8
    lda $C01C                          ; @BC34 AD 1C C0
    sbc $C014                          ; @BC37 ED 14 C0
    sta $C01C                          ; @BC3A 8D 1C C0
    tya                                ; @BC3D 98
    sbc $C015                          ; @BC3E ED 15 C0
    bcs LBC89                          ; @BC41 B0 46
LBC43:
    lda $C01C                          ; @BC43 AD 1C C0
    sbc $C014                          ; @BC46 ED 14 C0
    bcc LBC52                          ; @BC49 90 07
    sta $C01C                          ; @BC4B 8D 1C C0
    lda #$00                           ; @BC4E A9 00
    bcs LBC89                          ; @BC50 B0 37
LBC52:
    txa                                ; @BC52 8A
    bcc LBC89                          ; @BC53 90 34
LBC55:
    lda $C01C                          ; @BC55 AD 1C C0
    sbc $C014                          ; @BC58 ED 14 C0
    bcc LBC64                          ; @BC5B 90 07
    sta $C01C                          ; @BC5D 8D 1C C0
    lda #$00                           ; @BC60 A9 00
    bcs LBCA5                          ; @BC62 B0 41
LBC64:
    txa                                ; @BC64 8A
    bcc LBCA5                          ; @BC65 90 3E
LBC67:
    lda $C010                          ; @BC67 AD 10 C0
    asl a                              ; @BC6A 0A
    sta $C018                          ; @BC6B 8D 18 C0
    lda $C011                          ; @BC6E AD 11 C0
    rol a                              ; @BC71 2A
    sta $C01C                          ; @BC72 8D 1C C0
    lda #$00                           ; @BC75 A9 00
    sta $C019                          ; @BC77 8D 19 C0
    rol a                              ; @BC7A 2A
    asl $C018                          ; @BC7B 0E 18 C0
    rol $C01C                          ; @BC7E 2E 1C C0
    rol a                              ; @BC81 2A
    asl $C018                          ; @BC82 0E 18 C0
    rol $C01C                          ; @BC85 2E 1C C0
    rol a                              ; @BC88 2A
LBC89:
    rol $C018                          ; @BC89 2E 18 C0
    rol $C01C                          ; @BC8C 2E 1C C0
    rol a                              ; @BC8F 2A
    cmp $C015                          ; @BC90 CD 15 C0
    bcc LBCA5                          ; @BC93 90 10
    beq LBC55                          ; @BC95 F0 BE
    tay                                ; @BC97 A8
    lda $C01C                          ; @BC98 AD 1C C0
    sbc $C014                          ; @BC9B ED 14 C0
    sta $C01C                          ; @BC9E 8D 1C C0
    tya                                ; @BCA1 98
    sbc $C015                          ; @BCA2 ED 15 C0
LBCA5:
    rol $C018                          ; @BCA5 2E 18 C0
    rol $C01C                          ; @BCA8 2E 1C C0
    rol a                              ; @BCAB 2A
    cmp $C015                          ; @BCAC CD 15 C0
    bcc LBCC1                          ; @BCAF 90 10
    beq LBD1C                          ; @BCB1 F0 69
    tay                                ; @BCB3 A8
    lda $C01C                          ; @BCB4 AD 1C C0
    sbc $C014                          ; @BCB7 ED 14 C0
    sta $C01C                          ; @BCBA 8D 1C C0
    tya                                ; @BCBD 98
    sbc $C015                          ; @BCBE ED 15 C0
LBCC1:
    rol $C018                          ; @BCC1 2E 18 C0
    rol $C01C                          ; @BCC4 2E 1C C0
    rol a                              ; @BCC7 2A
    cmp $C015                          ; @BCC8 CD 15 C0
    bcc LBCDD                          ; @BCCB 90 10
    beq LBD2E                          ; @BCCD F0 5F
    tay                                ; @BCCF A8
    lda $C01C                          ; @BCD0 AD 1C C0
    sbc $C014                          ; @BCD3 ED 14 C0
    sta $C01C                          ; @BCD6 8D 1C C0
    tya                                ; @BCD9 98
    sbc $C015                          ; @BCDA ED 15 C0
LBCDD:
    rol $C018                          ; @BCDD 2E 18 C0
    rol $C01C                          ; @BCE0 2E 1C C0
    rol a                              ; @BCE3 2A
    cmp $C015                          ; @BCE4 CD 15 C0
    bcc LBCF9                          ; @BCE7 90 10
    beq LBD40                          ; @BCE9 F0 55
    tay                                ; @BCEB A8
    lda $C01C                          ; @BCEC AD 1C C0
    sbc $C014                          ; @BCEF ED 14 C0
    sta $C01C                          ; @BCF2 8D 1C C0
    tya                                ; @BCF5 98
    sbc $C015                          ; @BCF6 ED 15 C0
LBCF9:
    rol $C018                          ; @BCF9 2E 18 C0
    rol $C01C                          ; @BCFC 2E 1C C0
    rol a                              ; @BCFF 2A
    cmp $C015                          ; @BD00 CD 15 C0
    bcc LBD15                          ; @BD03 90 10
    beq LBD52                          ; @BD05 F0 4B
    tay                                ; @BD07 A8
    lda $C01C                          ; @BD08 AD 1C C0
    sbc $C014                          ; @BD0B ED 14 C0
    sta $C01C                          ; @BD0E 8D 1C C0
    tya                                ; @BD11 98
    sbc $C015                          ; @BD12 ED 15 C0
LBD15:
    rol $C018                          ; @BD15 2E 18 C0
    sta $C01D                          ; @BD18 8D 1D C0
    rts                                ; @BD1B 60
LBD1C:
    lda $C01C                          ; @BD1C AD 1C C0
    sbc $C014                          ; @BD1F ED 14 C0
    bcc LBD2B                          ; @BD22 90 07
    sta $C01C                          ; @BD24 8D 1C C0
    lda #$00                           ; @BD27 A9 00
    bcs LBCC1                          ; @BD29 B0 96
LBD2B:
    txa                                ; @BD2B 8A
    bcc LBCC1                          ; @BD2C 90 93
LBD2E:
    lda $C01C                          ; @BD2E AD 1C C0
    sbc $C014                          ; @BD31 ED 14 C0
    bcc LBD3D                          ; @BD34 90 07
    sta $C01C                          ; @BD36 8D 1C C0
    lda #$00                           ; @BD39 A9 00
    bcs LBCDD                          ; @BD3B B0 A0
LBD3D:
    txa                                ; @BD3D 8A
    bcc LBCDD                          ; @BD3E 90 9D
LBD40:
    lda $C01C                          ; @BD40 AD 1C C0
    sbc $C014                          ; @BD43 ED 14 C0
    bcc LBD4F                          ; @BD46 90 07
    sta $C01C                          ; @BD48 8D 1C C0
    lda #$00                           ; @BD4B A9 00
    bcs LBCF9                          ; @BD4D B0 AA
LBD4F:
    txa                                ; @BD4F 8A
    bcc LBCF9                          ; @BD50 90 A7
LBD52:
    lda $C01C                          ; @BD52 AD 1C C0
    sbc $C014                          ; @BD55 ED 14 C0
    bcc LBD61                          ; @BD58 90 07
    sta $C01C                          ; @BD5A 8D 1C C0
    lda #$00                           ; @BD5D A9 00
    bcs LBD15                          ; @BD5F B0 B4
LBD61:
    txa                                ; @BD61 8A
    bcc LBD15                          ; @BD62 90 B1
LBD64:
    lda $C014                          ; @BD64 AD 14 C0
    beq LBDAC                          ; @BD67 F0 43
LBD69:
    lda $C010                          ; @BD69 AD 10 C0
    sta $C018                          ; @BD6C 8D 18 C0
    lda $C011                          ; @BD6F AD 11 C0
    sta $C019                          ; @BD72 8D 19 C0
    lda #$00                           ; @BD75 A9 00
    lsr a                              ; @BD77 4A
    sta $C01C                          ; @BD78 8D 1C C0
    sta $C01D                          ; @BD7B 8D 1D C0
    ldy #$10                           ; @BD7E A0 10
LBD80:
    rol $C018                          ; @BD80 2E 18 C0
    rol $C019                          ; @BD83 2E 19 C0
    rol $C01C                          ; @BD86 2E 1C C0
    rol $C01D                          ; @BD89 2E 1D C0
    sec                                ; @BD8C 38
    lda $C01C                          ; @BD8D AD 1C C0
    sbc $C014                          ; @BD90 ED 14 C0
    tax                                ; @BD93 AA
    lda $C01D                          ; @BD94 AD 1D C0
    sbc $C015                          ; @BD97 ED 15 C0
    bcc LBDA2                          ; @BD9A 90 06
    sta $C01D                          ; @BD9C 8D 1D C0
    stx $C01C                          ; @BD9F 8E 1C C0
LBDA2:
    dey                                ; @BDA2 88
    bne LBD80                          ; @BDA3 D0 DB
    rol $C018                          ; @BDA5 2E 18 C0
    rol $C019                          ; @BDA8 2E 19 C0
    rts                                ; @BDAB 60
LBDAC:
    sta $C018                          ; @BDAC 8D 18 C0
    sta $C019                          ; @BDAF 8D 19 C0
    sta $C01C                          ; @BDB2 8D 1C C0
    sta $C01D                          ; @BDB5 8D 1D C0
    sec                                ; @BDB8 38
    rts                                ; @BDB9 60
