; mul_u8_u8_u16 — exact executable source mirror for v5_hybrid_lowzp
; Legacy API: MATH_UMUL8 at $3000
; GENERATED by tools/publish_standalone_sources.py. Do not hand-edit.
; Shipped image: v5_hybrid_lowzp/resident/math_v5_hybrid_lowzp_game_math.prg
; Canonical integrated/relocatable source: relocatable_source/v1_balanced/math_relocatable.asm + tools/build_hybrid.py
; This file contains every executable instruction statically reachable from the public entry after MATH_INIT.
; Shared immutable lookup/data tables and REU payload data are intentionally not duplicated here.
; The address/byte annotations make this a mechanically auditable source view of the shipped executable.
; Reachable instructions: 27.
!cpu 6510

; ---- executable island $3000 ----
* = $3000
mul_u8_u8_u16:
MATH_UMUL8:
    lda #$80                           ; @3000 A9 80
    sta $11                            ; @3002 85 11
    lda #$82                           ; @3004 A9 82
    sta $13                            ; @3006 85 13
    ldx $C000                          ; @3008 AE 00 C0
    ldy $C004                          ; @300B AC 04 C0
    jsr L4700                          ; @300E 20 00 47
    sta $C009                          ; @3011 8D 09 C0
    lda $14                            ; @3014 A5 14
    sta $C008                          ; @3016 8D 08 C0
    clc                                ; @3019 18
    rts                                ; @301A 60
; ---- executable island $4700 ----
* = $4700
L4700:
    sec                                ; @4700 38
    stx $10                            ; @4701 86 10
    stx $12                            ; @4703 86 12
    tya                                ; @4705 98
    sbc $10                            ; @4706 E5 10
    bcs L470E                          ; @4708 B0 04
    sbc #$00                           ; @470A E9 00
    eor #$FF                           ; @470C 49 FF
L470E:
    tax                                ; @470E AA
    lda ($10),y                        ; @470F B1 10
    sbc $8000,x                        ; @4711 FD 00 80
    sta $14                            ; @4714 85 14
    lda ($12),y                        ; @4716 B1 12
    sbc $8200,x                        ; @4718 FD 00 82
    rts                                ; @471B 60
