; seek_u8_u8_init — exact executable source mirror for v5_hybrid_lowzp
; Legacy API: MATH_SEEK8_INIT at $5E3C
; GENERATED by tools/publish_standalone_sources.py. Do not hand-edit.
; Shipped image: v5_hybrid_lowzp/resident/math_v5_hybrid_lowzp_game_math.prg
; Canonical integrated/relocatable source: relocatable_source/v1_balanced/math_relocatable.asm + tools/build_hybrid.py
; This file contains every executable instruction statically reachable from the public entry after MATH_INIT.
; Shared immutable lookup/data tables and REU payload data are intentionally not duplicated here.
; The address/byte annotations make this a mechanically auditable source view of the shipped executable.
; Reachable instructions: 197.
!cpu 6510

; ---- executable island $3464 ----
* = $3464
L3464:
    lda #$00                           ; @3464 A9 00
    sta $1910,x                        ; @3466 9D 10 19
    lda #$01                           ; @3469 A9 01
    sta $1930,x                        ; @346B 9D 30 19
    sec                                ; @346E 38
    rts                                ; @346F 60
; ---- executable island $34B4 ----
* = $34B4
L34B4:
    lda #$FF                           ; @34B4 A9 FF
    sta $1908,x                        ; @34B6 9D 08 19
    ldy #$00                           ; @34B9 A0 00
    lda $C004                          ; @34BB AD 04 C0
    sta $1900,x                        ; @34BE 9D 00 19
    sec                                ; @34C1 38
    sbc $18F0,x                        ; @34C2 FD F0 18
    bcs L34CC                          ; @34C5 B0 05
    eor #$FF                           ; @34C7 49 FF
    adc #$01                           ; @34C9 69 01
    dey                                ; @34CB 88
L34CC:
    sta $C041                          ; @34CC 8D 41 C0
    sty $C046                          ; @34CF 8C 46 C0
    ldy #$00                           ; @34D2 A0 00
    lda $C000                          ; @34D4 AD 00 C0
    sta $18F8,x                        ; @34D7 9D F8 18
    sec                                ; @34DA 38
    sbc $18E8,x                        ; @34DB FD E8 18
    bcs L34E5                          ; @34DE B0 05
    eor #$FF                           ; @34E0 49 FF
    adc #$01                           ; @34E2 69 01
    dey                                ; @34E4 88
L34E5:
    sty $C045                          ; @34E5 8C 45 C0
    cmp $C041                          ; @34E8 CD 41 C0
    bcs L3500                          ; @34EB B0 13
    ldy $C041                          ; @34ED AC 41 C0
    sta $C041                          ; @34F0 8D 41 C0
    lda $C045                          ; @34F3 AD 45 C0
    ora #$01                           ; @34F6 09 01
    sta $C049                          ; @34F8 8D 49 C0
    tya                                ; @34FB 98
    ldy #$80                           ; @34FC A0 80
    bne L350C                          ; @34FE D0 0C
L3500:
    tay                                ; @3500 A8
    lda $C046                          ; @3501 AD 46 C0
    ora #$01                           ; @3504 09 01
    sta $C049                          ; @3506 8D 49 C0
    tya                                ; @3509 98
    ldy #$00                           ; @350A A0 00
L350C:
    sty $C047                          ; @350C 8C 47 C0
    sta $C040                          ; @350F 8D 40 C0
    sta $1920,x                        ; @3512 9D 20 19
    lsr a                              ; @3515 4A
    sta $1918,x                        ; @3516 9D 18 19
    lda $C040                          ; @3519 AD 40 C0
    sec                                ; @351C 38
    sbc #$01                           ; @351D E9 01
    sta $1910,x                        ; @351F 9D 10 19
    bcc L3589                          ; @3522 90 65
    lda $C011                          ; @3524 AD 11 C0
    bmi L358C                          ; @3527 30 63
    sta $1930,x                        ; @3529 9D 30 19
    lda $C010                          ; @352C AD 10 C0
    sta $1928,x                        ; @352F 9D 28 19
L3532:
    lda #$00                           ; @3532 A9 00
    sta $C048                          ; @3534 8D 48 C0
    ldy $1930,x                        ; @3537 BC 30 19
    beq L3550                          ; @353A F0 14
L353C:
    clc                                ; @353C 18
    adc $C041                          ; @353D 6D 41 C0
    bcs L3547                          ; @3540 B0 05
    cmp $C040                          ; @3542 CD 40 C0
    bcc L354D                          ; @3545 90 06
L3547:
    sbc $C040                          ; @3547 ED 40 C0
    inc $C048                          ; @354A EE 48 C0
L354D:
    dey                                ; @354D 88
    bne L353C                          ; @354E D0 EC
L3550:
    sta $1938,x                        ; @3550 9D 38 19
    sta $C052                          ; @3553 8D 52 C0
    txa                                ; @3556 8A
    tay                                ; @3557 A8
    lda $1930,x                        ; @3558 BD 30 19
    jsr L385B                          ; @355B 20 5B 38
    lda $1928,x                        ; @355E BD 28 19
    beq L3587                          ; @3561 F0 24
    lda $C052                          ; @3563 AD 52 C0
    clc                                ; @3566 18
    adc $C041                          ; @3567 6D 41 C0
    bcs L3571                          ; @356A B0 05
    cmp $C040                          ; @356C CD 40 C0
    bcc L3577                          ; @356F 90 06
L3571:
    sbc $C040                          ; @3571 ED 40 C0
    inc $C048                          ; @3574 EE 48 C0
L3577:
    sta $1940,x                        ; @3577 9D 40 19
    txa                                ; @357A 8A
    ora #$08                           ; @357B 09 08
    tay                                ; @357D A8
    lda $1930,x                        ; @357E BD 30 19
    sec                                ; @3581 38
    adc #$00                           ; @3582 69 00
    jsr L385B                          ; @3584 20 5B 38
L3587:
    clc                                ; @3587 18
    rts                                ; @3588 60
L3589:
    jmp L3464                          ; @3589 4C 64 34
L358C:
    jsr L3977                          ; @358C 20 77 39
    sta $1930,x                        ; @358F 9D 30 19
    tya                                ; @3592 98
    sta $1928,x                        ; @3593 9D 28 19
    jmp L3532                          ; @3596 4C 32 35
; ---- executable island $385B ----
* = $385B
L385B:
    bit $C047                          ; @385B 2C 47 C0
    bmi L388F                          ; @385E 30 2F
    eor $C045                          ; @3860 4D 45 C0
    clc                                ; @3863 18
    sbc $C045                          ; @3864 ED 45 C0
    sta $1948,y                        ; @3867 99 48 19
    sta $1958,y                        ; @386A 99 58 19
    ora #$7F                           ; @386D 09 7F
    bmi L3873                          ; @386F 30 02
    lda #$00                           ; @3871 A9 00
L3873:
    sta $C04A                          ; @3873 8D 4A C0
    lda $C048                          ; @3876 AD 48 C0
    eor $C046                          ; @3879 4D 46 C0
    sec                                ; @387C 38
    sbc $C046                          ; @387D ED 46 C0
    clc                                ; @3880 18
    adc $C04A                          ; @3881 6D 4A C0
    sta $1968,y                        ; @3884 99 68 19
    clc                                ; @3887 18
    adc $C049                          ; @3888 6D 49 C0
    sta $1978,y                        ; @388B 99 78 19
    rts                                ; @388E 60
L388F:
    eor $C046                          ; @388F 4D 46 C0
    sec                                ; @3892 38
    sbc $C046                          ; @3893 ED 46 C0
    sta $C04B                          ; @3896 8D 4B C0
    lda $C048                          ; @3899 AD 48 C0
    eor $C045                          ; @389C 4D 45 C0
    clc                                ; @389F 18
    sbc $C045                          ; @38A0 ED 45 C0
    sta $1948,y                        ; @38A3 99 48 19
    sta $C04C                          ; @38A6 8D 4C C0
    ora #$7F                           ; @38A9 09 7F
    bmi L38AF                          ; @38AB 30 02
    lda #$00                           ; @38AD A9 00
L38AF:
    clc                                ; @38AF 18
    adc $C04B                          ; @38B0 6D 4B C0
    sta $1968,y                        ; @38B3 99 68 19
    lda $C04C                          ; @38B6 AD 4C C0
    clc                                ; @38B9 18
    adc $C049                          ; @38BA 6D 49 C0
    sta $1958,y                        ; @38BD 99 58 19
    ora #$7F                           ; @38C0 09 7F
    bmi L38C6                          ; @38C2 30 02
    lda #$00                           ; @38C4 A9 00
L38C6:
    clc                                ; @38C6 18
    adc $C04B                          ; @38C7 6D 4B C0
    sta $1978,y                        ; @38CA 99 78 19
    rts                                ; @38CD 60
; ---- executable island $3977 ----
* = $3977
L3977:
    lda $C011                          ; @3977 AD 11 C0
    and #$7F                           ; @397A 29 7F
    sta $C044                          ; @397C 8D 44 C0
    lda #$08                           ; @397F A9 08
    sta $C042                          ; @3981 8D 42 C0
    lda $C041                          ; @3984 AD 41 C0
L3987:
    asl a                              ; @3987 0A
    bcs L398F                          ; @3988 B0 05
    cmp $C040                          ; @398A CD 40 C0
    bcc L3993                          ; @398D 90 04
L398F:
    sbc $C040                          ; @398F ED 40 C0
    sec                                ; @3992 38
L3993:
    rol $C042                          ; @3993 2E 42 C0
    bcc L3987                          ; @3996 90 EF
    ldy $C042                          ; @3998 AC 42 C0
    lda #$00                           ; @399B A9 00
    sta $C043                          ; @399D 8D 43 C0
    lda $39D6,y                        ; @39A0 B9 D6 39
    sec                                ; @39A3 38
    ror a                              ; @39A4 6A
    sta $C042                          ; @39A5 8D 42 C0
    lda #$00                           ; @39A8 A9 00
L39AA:
    bcc L39BB                          ; @39AA 90 0F
    clc                                ; @39AC 18
    adc $C010                          ; @39AD 6D 10 C0
    tay                                ; @39B0 A8
    lda $C043                          ; @39B1 AD 43 C0
    adc $C044                          ; @39B4 6D 44 C0
    sta $C043                          ; @39B7 8D 43 C0
    tya                                ; @39BA 98
L39BB:
    ror $C043                          ; @39BB 6E 43 C0
    ror a                              ; @39BE 6A
    lsr $C042                          ; @39BF 4E 42 C0
    bne L39AA                          ; @39C2 D0 E6
    sta $C042                          ; @39C4 8D 42 C0
    lda $C010                          ; @39C7 AD 10 C0
    sec                                ; @39CA 38
    sbc $C042                          ; @39CB ED 42 C0
    tay                                ; @39CE A8
    lda $C044                          ; @39CF AD 44 C0
    sbc $C043                          ; @39D2 ED 43 C0
    rts                                ; @39D5 60
; ---- executable island $5E3C ----
* = $5E3C
seek_u8_u8_init:
MATH_SEEK8_INIT:
    jmp L34B4                          ; @5E3C 4C B4 34
