; seek_u8_u8_step1 — exact executable source mirror for v5_hybrid_lowzp
; Legacy API: MATH_SEEK8_STEP1 at $5E45
; GENERATED by tools/publish_standalone_sources.py. Do not hand-edit.
; Shipped image: v5_hybrid_lowzp/resident/math_v5_hybrid_lowzp_game_math.prg
; Canonical integrated/relocatable source: relocatable_source/v1_balanced/math_relocatable.asm + tools/build_hybrid.py
; This file contains every executable instruction statically reachable from the public entry after MATH_INIT.
; Shared immutable lookup/data tables and REU payload data are intentionally not duplicated here.
; The address/byte annotations make this a mechanically auditable source view of the shipped executable.
; Reachable instructions: 36.
!cpu 6510

; ---- executable island $3418 ----
* = $3418
L3418:
    lda $1918,x                        ; @3418 BD 18 19
    sbc $1938,x                        ; @341B FD 38 19
    bcc L3437                          ; @341E 90 17
    sta $1918,x                        ; @3420 9D 18 19
    lda $18E8,x                        ; @3423 BD E8 18
    adc $1948,x                        ; @3426 7D 48 19
    sta $18E8,x                        ; @3429 9D E8 18
    lda $18F0,x                        ; @342C BD F0 18
    adc $1968,x                        ; @342F 7D 68 19
    sta $18F0,x                        ; @3432 9D F0 18
    clc                                ; @3435 18
    rts                                ; @3436 60
L3437:
    adc $1920,x                        ; @3437 7D 20 19
    sta $1918,x                        ; @343A 9D 18 19
    lda $18E8,x                        ; @343D BD E8 18
    adc $1958,x                        ; @3440 7D 58 19
    sta $18E8,x                        ; @3443 9D E8 18
    lda $18F0,x                        ; @3446 BD F0 18
    adc $1978,x                        ; @3449 7D 78 19
    sta $18F0,x                        ; @344C 9D F0 18
    clc                                ; @344F 18
    rts                                ; @3450 60
L3451:
    lda #$FF                           ; @3451 A9 FF
    !byte $DF, $10, $19    ; DCP absx  ; @3453 DF 10 19
    bne L3418                          ; @3456 D0 C0
    lda $18F8,x                        ; @3458 BD F8 18
    sta $18E8,x                        ; @345B 9D E8 18
    lda $1900,x                        ; @345E BD 00 19
    sta $18F0,x                        ; @3461 9D F0 18
    lda #$00                           ; @3464 A9 00
    sta $1910,x                        ; @3466 9D 10 19
    lda #$01                           ; @3469 A9 01
    sta $1930,x                        ; @346B 9D 30 19
    sec                                ; @346E 38
    rts                                ; @346F 60
; ---- executable island $5E45 ----
* = $5E45
seek_u8_u8_step1:
MATH_SEEK8_STEP1:
    jmp L3451                          ; @5E45 4C 51 34
