; Native integrated SMUL24 for v4_reu_16m
; Public stable entry is a JMP stub; implementation origin $2200.
; The unsigned arithmetic producer body is copied byte-for-byte from this profile's
; selected UMUL24 implementation (or direct REU producer), and its terminal return
; is replaced by the signed two's-complement upper-half continuation below.
; This source note deliberately documents the transformation: the final binary is
; resident/native_signed/multiply/smul24_native.bin and is generated by tools/build_native_signed_release.py.
; No call to MATH_UMUL24 occurs in the signed path.

; Signed correction identity (modulo 2^48):
;   P_signed = P_unsigned - (x<0 ? y<<24 : 0) - (y<0 ? x<<24 : 0)

; Correction tail appended to the selected producer:
        lda math_x23
        bpl .x_done
        sec
        lda math_z24
        sbc math_y0
        sta math_z24
        lda math_z25
        sbc math_y1
        sta math_z25
        lda math_z26
        sbc math_y2
        sta math_z26
        lda math_z27
        sbc math_y3
        sta math_z27
        lda math_z28
        sbc math_y4
        sta math_z28
        lda math_z29
        sbc math_y5
        sta math_z29
        lda math_z30
        sbc math_y6
        sta math_z30
        lda math_z31
        sbc math_y7
        sta math_z31
        lda math_z32
        sbc math_y8
        sta math_z32
        lda math_z33
        sbc math_y9
        sta math_z33
        lda math_z34
        sbc math_y10
        sta math_z34
        lda math_z35
        sbc math_y11
        sta math_z35
        lda math_z36
        sbc math_y12
        sta math_z36
        lda math_z37
        sbc math_y13
        sta math_z37
        lda math_z38
        sbc math_y14
        sta math_z38
        lda math_z39
        sbc math_y15
        sta math_z39
        lda math_z40
        sbc math_y16
        sta math_z40
        lda math_z41
        sbc math_y17
        sta math_z41
        lda math_z42
        sbc math_y18
        sta math_z42
        lda math_z43
        sbc math_y19
        sta math_z43
        lda math_z44
        sbc math_y20
        sta math_z44
        lda math_z45
        sbc math_y21
        sta math_z45
        lda math_z46
        sbc math_y22
        sta math_z46
        lda math_z47
        sbc math_y23
        sta math_z47
.x_done:
        lda math_y23
        bpl .done
        sec
        lda math_z24
        sbc math_x0
        sta math_z24
        lda math_z25
        sbc math_x1
        sta math_z25
        lda math_z26
        sbc math_x2
        sta math_z26
        lda math_z27
        sbc math_x3
        sta math_z27
        lda math_z28
        sbc math_x4
        sta math_z28
        lda math_z29
        sbc math_x5
        sta math_z29
        lda math_z30
        sbc math_x6
        sta math_z30
        lda math_z31
        sbc math_x7
        sta math_z31
        lda math_z32
        sbc math_x8
        sta math_z32
        lda math_z33
        sbc math_x9
        sta math_z33
        lda math_z34
        sbc math_x10
        sta math_z34
        lda math_z35
        sbc math_x11
        sta math_z35
        lda math_z36
        sbc math_x12
        sta math_z36
        lda math_z37
        sbc math_x13
        sta math_z37
        lda math_z38
        sbc math_x14
        sta math_z38
        lda math_z39
        sbc math_x15
        sta math_z39
        lda math_z40
        sbc math_x16
        sta math_z40
        lda math_z41
        sbc math_x17
        sta math_z41
        lda math_z42
        sbc math_x18
        sta math_z42
        lda math_z43
        sbc math_x19
        sta math_z43
        lda math_z44
        sbc math_x20
        sta math_z44
        lda math_z45
        sbc math_x21
        sta math_z45
        lda math_z46
        sbc math_x22
        sta math_z46
        lda math_z47
        sbc math_x23
        sta math_z47
.done:
        clc
        rts
