; Native integrated SMUL8 for v3_reu_512k
; Public stable entry is a JMP stub; implementation origin $2000.
; The unsigned arithmetic producer body is copied byte-for-byte from this profile's
; selected UMUL8 implementation (or direct REU producer), and its terminal return
; is replaced by the signed two's-complement upper-half continuation below.
; This source note deliberately documents the transformation: the final binary is
; resident/native_signed/multiply/smul8_native.bin and is generated by tools/build_native_signed_release.py.
; No call to MATH_UMUL8 occurs in the signed path.

; Signed correction identity (modulo 2^16):
;   P_signed = P_unsigned - (x<0 ? y<<8 : 0) - (y<0 ? x<<8 : 0)

; Correction tail appended to the selected producer:
        lda math_x7
        bpl .x_done
        sec
        lda math_z8
        sbc math_y0
        sta math_z8
        lda math_z9
        sbc math_y1
        sta math_z9
        lda math_z10
        sbc math_y2
        sta math_z10
        lda math_z11
        sbc math_y3
        sta math_z11
        lda math_z12
        sbc math_y4
        sta math_z12
        lda math_z13
        sbc math_y5
        sta math_z13
        lda math_z14
        sbc math_y6
        sta math_z14
        lda math_z15
        sbc math_y7
        sta math_z15
.x_done:
        lda math_y7
        bpl .done
        sec
        lda math_z8
        sbc math_x0
        sta math_z8
        lda math_z9
        sbc math_x1
        sta math_z9
        lda math_z10
        sbc math_x2
        sta math_z10
        lda math_z11
        sbc math_x3
        sta math_z11
        lda math_z12
        sbc math_x4
        sta math_z12
        lda math_z13
        sbc math_x5
        sta math_z13
        lda math_z14
        sbc math_x6
        sta math_z14
        lda math_z15
        sbc math_x7
        sta math_z15
.done:
        clc
        rts
