; atan2_s8_s8_u8 — exact executable source mirror for v2_pareto_fast
; Legacy API: MATH_ATAN2_8 at $5E2A
; GENERATED by tools/publish_standalone_sources.py. Do not hand-edit.
; Shipped image: v2_pareto_fast/resident/math_v2_pareto_fast_game_math.prg
; Canonical integrated/relocatable source: relocatable_source/v2_pareto_fast/math_relocatable.asm
; This file contains every executable instruction statically reachable from the public entry after MATH_INIT.
; Shared immutable lookup/data tables and REU payload data are intentionally not duplicated here.
; The address/byte annotations make this a mechanically auditable source view of the shipped executable.
; Reachable instructions: 40.
!cpu 6510

; ---- executable island $5E2A ----
* = $5E2A
atan2_s8_s8_u8:
MATH_ATAN2_8:
    jmp LC782                          ; @5E2A 4C 82 C7
; ---- executable island $C782 ----
* = $C782
LC782:
    clc                                ; @C782 18
    ldx $C000                          ; @C783 AE 00 C0
    beq LC7CA                          ; @C786 F0 42
    bmi LC7A8                          ; @C788 30 1E
    lda $9600,x                        ; @C78A BD 00 96
    ldx $C004                          ; @C78D AE 04 C0
    bmi LC79D                          ; @C790 30 0B
    adc $9700,x                        ; @C792 7D 00 97
    tax                                ; @C795 AA
    lda $6E00,x                        ; @C796 BD 00 6E
    sta $C008                          ; @C799 8D 08 C0
    rts                                ; @C79C 60
LC79D:
    adc $9700,x                        ; @C79D 7D 00 97
    tax                                ; @C7A0 AA
    lda $6F00,x                        ; @C7A1 BD 00 6F
    sta $C008                          ; @C7A4 8D 08 C0
    rts                                ; @C7A7 60
LC7A8:
    lda $9600,x                        ; @C7A8 BD 00 96
    ldx $C004                          ; @C7AB AE 04 C0
    bmi LC7BD                          ; @C7AE 30 0D
    adc $9700,x                        ; @C7B0 7D 00 97
    tax                                ; @C7B3 AA
    lda $6F00,x                        ; @C7B4 BD 00 6F
    eor #$80                           ; @C7B7 49 80
    sta $C008                          ; @C7B9 8D 08 C0
    rts                                ; @C7BC 60
LC7BD:
    adc $9700,x                        ; @C7BD 7D 00 97
    tax                                ; @C7C0 AA
    lda $6E00,x                        ; @C7C1 BD 00 6E
    eor #$80                           ; @C7C4 49 80
    sta $C008                          ; @C7C6 8D 08 C0
    rts                                ; @C7C9 60
LC7CA:
    lda $C004                          ; @C7CA AD 04 C0
    beq LC7D3                          ; @C7CD F0 04
    asl a                              ; @C7CF 0A
    lda #$80                           ; @C7D0 A9 80
    ror a                              ; @C7D2 6A
LC7D3:
    sta $C008                          ; @C7D3 8D 08 C0
    rts                                ; @C7D6 60
