; seek_u16_u8_step — exact executable source mirror for v2_pareto_fast
; Legacy API: MATH_SEEK16_STEP at $5E4B
; GENERATED by tools/publish_standalone_sources.py. Do not hand-edit.
; Shipped image: v2_pareto_fast/resident/math_v2_pareto_fast_game_math.prg
; Canonical integrated/relocatable source: relocatable_source/v2_pareto_fast/math_relocatable.asm
; This file contains every executable instruction statically reachable from the public entry after MATH_INIT.
; Shared immutable lookup/data tables and REU payload data are intentionally not duplicated here.
; The address/byte annotations make this a mechanically auditable source view of the shipped executable.
; Reachable instructions: 109.
!cpu 6510

; ---- executable island $5E4B ----
* = $5E4B
seek_u16_u8_step:
MATH_SEEK16_STEP:
    jmp L5E8A                          ; @5E4B 4C 8A 5E
; ---- executable island $5E60 ----
* = $5E60
L5E60:
    lda $9100,x                        ; @5E60 BD 00 91
    sta $90E8,x                        ; @5E63 9D E8 90
    lda $9108,x                        ; @5E66 BD 08 91
    sta $90F0,x                        ; @5E69 9D F0 90
    lda $9110,x                        ; @5E6C BD 10 91
    sta $90F8,x                        ; @5E6F 9D F8 90
    lda #$00                           ; @5E72 A9 00
    sta $9120,x                        ; @5E74 9D 20 91
    sta $9128,x                        ; @5E77 9D 28 91
    lda #$01                           ; @5E7A A9 01
    sta $9158,x                        ; @5E7C 9D 58 91
    sec                                ; @5E7F 38
    rts                                ; @5E80 60
L5E81:
    dec $9128,x                        ; @5E81 DE 28 91
    bmi L5E60                          ; @5E84 30 DA
    sec                                ; @5E86 38
    jmp L5EA2                          ; @5E87 4C A2 5E
L5E8A:
    lda $9118,x                        ; @5E8A BD 18 91
    sec                                ; @5E8D 38
    sbc $9150,x                        ; @5E8E FD 50 91
    sta $9118,x                        ; @5E91 9D 18 91
    bcc L5F01                          ; @5E94 90 6B
    sec                                ; @5E96 38
    lda $9120,x                        ; @5E97 BD 20 91
    sbc $9158,x                        ; @5E9A FD 58 91
    sta $9120,x                        ; @5E9D 9D 20 91
    bcc L5E81                          ; @5EA0 90 DF
L5EA2:
    lda $9130,x                        ; @5EA2 BD 30 91
    sbc $9160,x                        ; @5EA5 FD 60 91
    sta $9130,x                        ; @5EA8 9D 30 91
    lda $9138,x                        ; @5EAB BD 38 91
    sbc $9170,x                        ; @5EAE FD 70 91
    bcc L5ED3                          ; @5EB1 90 20
    sta $9138,x                        ; @5EB3 9D 38 91
    lda $90E8,x                        ; @5EB6 BD E8 90
    adc $9180,x                        ; @5EB9 7D 80 91
    sta $90E8,x                        ; @5EBC 9D E8 90
    lda $90F0,x                        ; @5EBF BD F0 90
    adc $91A0,x                        ; @5EC2 7D A0 91
    sta $90F0,x                        ; @5EC5 9D F0 90
    lda $90F8,x                        ; @5EC8 BD F8 90
    adc $91C0,x                        ; @5ECB 7D C0 91
    sta $90F8,x                        ; @5ECE 9D F8 90
    clc                                ; @5ED1 18
    rts                                ; @5ED2 60
L5ED3:
    tay                                ; @5ED3 A8
    lda $9130,x                        ; @5ED4 BD 30 91
    adc $9140,x                        ; @5ED7 7D 40 91
    sta $9130,x                        ; @5EDA 9D 30 91
    tya                                ; @5EDD 98
    adc $9148,x                        ; @5EDE 7D 48 91
    sta $9138,x                        ; @5EE1 9D 38 91
    lda $90E8,x                        ; @5EE4 BD E8 90
    adc $9190,x                        ; @5EE7 7D 90 91
    sta $90E8,x                        ; @5EEA 9D E8 90
    lda $90F0,x                        ; @5EED BD F0 90
    adc $91B0,x                        ; @5EF0 7D B0 91
    sta $90F0,x                        ; @5EF3 9D F0 90
    lda $90F8,x                        ; @5EF6 BD F8 90
    adc $91D0,x                        ; @5EF9 7D D0 91
    sta $90F8,x                        ; @5EFC 9D F8 90
    clc                                ; @5EFF 18
    rts                                ; @5F00 60
L5F01:
    lda $9120,x                        ; @5F01 BD 20 91
    sbc $9158,x                        ; @5F04 FD 58 91
    sta $9120,x                        ; @5F07 9D 20 91
    bcc L5F6B                          ; @5F0A 90 5F
L5F0C:
    lda $9130,x                        ; @5F0C BD 30 91
    sbc $9168,x                        ; @5F0F FD 68 91
    sta $9130,x                        ; @5F12 9D 30 91
    lda $9138,x                        ; @5F15 BD 38 91
    sbc $9178,x                        ; @5F18 FD 78 91
    bcc L5F3D                          ; @5F1B 90 20
    sta $9138,x                        ; @5F1D 9D 38 91
    lda $90E8,x                        ; @5F20 BD E8 90
    adc $9188,x                        ; @5F23 7D 88 91
    sta $90E8,x                        ; @5F26 9D E8 90
    lda $90F0,x                        ; @5F29 BD F0 90
    adc $91A8,x                        ; @5F2C 7D A8 91
    sta $90F0,x                        ; @5F2F 9D F0 90
    lda $90F8,x                        ; @5F32 BD F8 90
    adc $91C8,x                        ; @5F35 7D C8 91
    sta $90F8,x                        ; @5F38 9D F8 90
    clc                                ; @5F3B 18
    rts                                ; @5F3C 60
L5F3D:
    tay                                ; @5F3D A8
    lda $9130,x                        ; @5F3E BD 30 91
    adc $9140,x                        ; @5F41 7D 40 91
    sta $9130,x                        ; @5F44 9D 30 91
    tya                                ; @5F47 98
    adc $9148,x                        ; @5F48 7D 48 91
    sta $9138,x                        ; @5F4B 9D 38 91
    lda $90E8,x                        ; @5F4E BD E8 90
    adc $9198,x                        ; @5F51 7D 98 91
    sta $90E8,x                        ; @5F54 9D E8 90
    lda $90F0,x                        ; @5F57 BD F0 90
    adc $91B8,x                        ; @5F5A 7D B8 91
    sta $90F0,x                        ; @5F5D 9D F0 90
    lda $90F8,x                        ; @5F60 BD F8 90
    adc $91D8,x                        ; @5F63 7D D8 91
    sta $90F8,x                        ; @5F66 9D F8 90
    clc                                ; @5F69 18
    rts                                ; @5F6A 60
L5F6B:
    dec $9128,x                        ; @5F6B DE 28 91
    bpl L5F73                          ; @5F6E 10 03
    jmp L5E60                          ; @5F70 4C 60 5E
L5F73:
    sec                                ; @5F73 38
    jmp L5F0C                          ; @5F74 4C 0C 5F
