; seek_u8_u8_step1 — exact executable source mirror for v2_pareto_fast
; Legacy API: MATH_SEEK8_STEP1 at $5E45
; GENERATED by tools/publish_standalone_sources.py. Do not hand-edit.
; Shipped image: v2_pareto_fast/resident/math_v2_pareto_fast_game_math.prg
; Canonical integrated/relocatable source: relocatable_source/v2_pareto_fast/math_relocatable.asm
; This file contains every executable instruction statically reachable from the public entry after MATH_INIT.
; Shared immutable lookup/data tables and REU payload data are intentionally not duplicated here.
; The address/byte annotations make this a mechanically auditable source view of the shipped executable.
; Reachable instructions: 36.
!cpu 6510

; ---- executable island $3E18 ----
* = $3E18
L3E18:
    lda $3AC0,x                        ; @3E18 BD C0 3A
    sbc $3AE0,x                        ; @3E1B FD E0 3A
    bcc L3E37                          ; @3E1E 90 17
    sta $3AC0,x                        ; @3E20 9D C0 3A
    lda $3A90,x                        ; @3E23 BD 90 3A
    adc $3AF0,x                        ; @3E26 7D F0 3A
    sta $3A90,x                        ; @3E29 9D 90 3A
    lda $3A98,x                        ; @3E2C BD 98 3A
    adc $3B10,x                        ; @3E2F 7D 10 3B
    sta $3A98,x                        ; @3E32 9D 98 3A
    clc                                ; @3E35 18
    rts                                ; @3E36 60
L3E37:
    adc $3AC8,x                        ; @3E37 7D C8 3A
    sta $3AC0,x                        ; @3E3A 9D C0 3A
    lda $3A90,x                        ; @3E3D BD 90 3A
    adc $3B00,x                        ; @3E40 7D 00 3B
    sta $3A90,x                        ; @3E43 9D 90 3A
    lda $3A98,x                        ; @3E46 BD 98 3A
    adc $3B20,x                        ; @3E49 7D 20 3B
    sta $3A98,x                        ; @3E4C 9D 98 3A
    clc                                ; @3E4F 18
    rts                                ; @3E50 60
L3E51:
    lda #$FF                           ; @3E51 A9 FF
    !byte $DF, $B8, $3A    ; DCP absx  ; @3E53 DF B8 3A
    bne L3E18                          ; @3E56 D0 C0
    lda $3AA0,x                        ; @3E58 BD A0 3A
    sta $3A90,x                        ; @3E5B 9D 90 3A
    lda $3AA8,x                        ; @3E5E BD A8 3A
    sta $3A98,x                        ; @3E61 9D 98 3A
    lda #$00                           ; @3E64 A9 00
    sta $3AB8,x                        ; @3E66 9D B8 3A
    lda #$01                           ; @3E69 A9 01
    sta $3AD8,x                        ; @3E6B 9D D8 3A
    sec                                ; @3E6E 38
    rts                                ; @3E6F 60
; ---- executable island $5E45 ----
* = $5E45
seek_u8_u8_step1:
MATH_SEEK8_STEP1:
    jmp L3E51                          ; @5E45 4C 51 3E
