; sincos_u8_s8_s8 — exact executable source mirror for v2_pareto_fast
; Legacy API: MATH_SINCOS8 at $5E27
; GENERATED by tools/publish_standalone_sources.py. Do not hand-edit.
; Shipped image: v2_pareto_fast/resident/math_v2_pareto_fast_game_math.prg
; Canonical integrated/relocatable source: relocatable_source/v2_pareto_fast/math_relocatable.asm
; This file contains every executable instruction statically reachable from the public entry after MATH_INIT.
; Shared immutable lookup/data tables and REU payload data are intentionally not duplicated here.
; The address/byte annotations make this a mechanically auditable source view of the shipped executable.
; Reachable instructions: 8.
!cpu 6510

; ---- executable island $5E27 ----
* = $5E27
sincos_u8_s8_s8:
MATH_SINCOS8:
    jmp LC771                          ; @5E27 4C 71 C7
; ---- executable island $C771 ----
* = $C771
LC771:
    ldx $C000                          ; @C771 AE 00 C0
    lda $9400,x                        ; @C774 BD 00 94
    sta $C008                          ; @C777 8D 08 C0
    lda $9500,x                        ; @C77A BD 00 95
    sta $C009                          ; @C77D 8D 09 C0
    clc                                ; @C780 18
    rts                                ; @C781 60
