#!/usr/bin/env python3
"""Emit the SEEK8/SEEK16 kernel sources from tools/seek_kernel.py.

Writes the two standalone sources under routines/movement/ and one native
include per fixed profile. --check fails if any committed file differs.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'tools'))
import seek_kernel as K  # noqa: E402

# Free islands (region-relative, verified free on the reference and alternate
# maps by tracing every memory access of MATH_INIT plus the full validation
# suite; see validation/movement/SEEK_PLACEMENT.json). The JMP slots always
# take REG_GAME_API+$003C..+$0053.
LAYOUTS = {
    'v1_balanced': dict(
        seek8_step='REG_API+$0400', seek8_init='REG_API+$04B4', seek16_step='REG_API+$0600',
        seek16_init='REG_API+$0723', seek8_planes='REG_API+$085B', seek16_helpers='REG_API+$08CE',
        seek_shared='REG_API+$0977', seek8_state='REG_LOW+$08E8', seek16_state='REG_LOW+$0988'),
    'v2_pareto_fast': dict(
        seek8_step='REG_API+$0E00', seek16_step='REG_GAME_API+$0054', seek8_init='REG_LOW+$0B00',
        seek16_init='REG_LOW+$08E2', seek8_planes='REG_API+$0F6C', seek16_helpers='REG_API+$0EE3',
        seek_shared='REG_API+$0D23', seek8_state='REG_API+$0A90', seek16_state='REG_TABLE+$30E8'),
    'v3_reu_512k': dict(
        seek16_step='REG_KERNEL', seek8_step='REG_KERNEL+$0124', seek8_init='REG_API+$0711',
        seek16_init='REG_API+$0600', seek8_planes='REG_GAME_API+$00DD', seek16_helpers='REG_GAME_API+$0054',
        seek_shared='REG_API+$0D23', seek8_state='REG_TABLE+$3308', seek16_state='REG_TABLE+$30E8'),
}
LAYOUTS['v4_reu_16m'] = dict(LAYOUTS['v3_reu_512k'])
SCRATCH = {
    'v1_balanced': ('V1_SCRATCH', 'Scratch is V1_SCRATCH RAM (the V1 game scratch); no ZP is used.'),
    'v2_pareto_fast': ('ZP_MAIN+$51', 'Scratch is ZP_MAIN+$51.. (the V2-V4 game scratch ZP).'),
    'v3_reu_512k': ('ZP_MAIN+$51', 'Scratch is ZP_MAIN+$51.. (the V2-V4 game scratch ZP).'),
    'v4_reu_16m': ('ZP_MAIN+$51', 'Scratch is ZP_MAIN+$51.. (the V2-V4 game scratch ZP).'),
}


PROFILE_TITLE = {'v1_balanced': 'V1 Balanced', 'v2_pareto_fast': 'V2 Pareto-Fast', 'v3_reu_512k': 'V3 REU 512K',
                 'v4_reu_16m': 'V4 REU 16M', 'v5_hybrid_lowzp': 'V5 Hybrid Low-ZP'}


def readme(profile: str, layout: dict, scratch: tuple) -> str:
    """Adjacent README: exact reference-map placement and resources."""
    from mini6502 import Assembler
    base = 'v1_balanced' if profile == 'v5_hybrid_lowzp' else profile
    cfg = (ROOT / 'relocatable_source' / base / 'math_config_reference.inc').read_text()
    lib = K.library(base, LAYOUTS[base], *SCRATCH[base])
    mem, labels, const = Assembler().assemble(cfg + lib)
    order = ['seek8_step', 'seek8_init', 'seek8_planes', 'seek16_step', 'seek16_init', 'seek16_helpers', 'seek_shared']
    first = {'seek8_step': 'seek8_step', 'seek8_init': 'seek8_init', 'seek8_planes': 's8_planes',
             'seek16_step': 'seek16_step1', 'seek16_init': 'seek16_init', 'seek16_helpers': 's16_addmin',
             'seek_shared': 'seek_euclid_speed'}
    rows = []
    code_total = 0
    for blk in order:
        start = labels[first[blk]]
        end = start
        while end + 1 in mem and not any(labels[first[b]] == end + 1 for b in order):
            end += 1
        code_total += end - start + 1
        rows.append(f'| {blk} | `{layout[blk]}` | ${start:04X}-${end:04X} | {end - start + 1} |')
    s8, s16 = const['SEEK8_STATE'], const['SEEK16_STATE']
    rows.append(f"| SEEK8 object state | `{layout['seek8_state']}` | ${s8:04X}-${s8 + K.S8_BYTES - 1:04X} | {K.S8_BYTES} |")
    rows.append(f"| SEEK16 object state | `{layout['seek16_state']}` | ${s16:04X}-${s16 + K.S16_BYTES - 1:04X} | {K.S16_BYTES} |")
    t = const['SEEK_T']
    note = ('V5 inherits the V1 image, so this backend and its placement are byte-identical to V1.\n\n'
            if profile == 'v5_hybrid_lowzp' else '')
    return f"""# {PROFILE_TITLE[profile]}: seek movement kernels

`seek_dda.asm` installs `MATH_SEEK8_*` and `MATH_SEEK16_*` (API entries 47-54) in this profile.
It is generated by `tools/generate_seek_sources.py` from `tools/seek_kernel.py`; the same
kernels are published standalone as `routines/movement/seek_u8_u8_dda.asm` and
`seek_u16_u8_dda.asm`. See `docs/SEEK_DDA.md` for the calling convention and measurements.

{note}## Placement (reference map)

All islands are region-relative, so they move with the configured map. Each was proven free on
the reference and alternate maps by tracing every memory access of `MATH_INIT`, the full
common-API suite and (V3/V4) the Turbo lifecycle, including REU DMA
(`tools/validate_seek_placement.py`, `validation/movement/SEEK_PLACEMENT.json`). The per-frame
SEEK8 steppers sit inside one page, so no hot branch pays a page-crossing cycle.

| Block | Origin | Reference address | Bytes |
|---|---|---|---:|
| public JMP slots | `REG_GAME_API+$003C` | $5E3C-$5E53 | 24 |
{chr(10).join(rows)}

Code: {code_total} bytes plus 24 bytes of JMP slots. Object state: {K.S8_BYTES + K.S16_BYTES} bytes
(8 slots each). No lookup table other than the 32-byte Euclidean correction inside `seek_shared`.

## Scratch and resources

- Init scratch: {K.SCRATCH_BYTES} bytes at `{scratch[0]}` (${t:04X} on the reference map). {scratch[1]}
- The per-frame steppers use no scratch and no zero page; the kernels add no ZP to the profile.
- No REU use and no `MATH_INIT` dependency; the steppers need no initialisation beyond `*_INIT`.
- `MATH_SEEK*_STEP1` uses the stable NMOS `DCP abs,X` opcode.
- Not reentrant with other library calls (shared init scratch), as elsewhere in the library.
"""


def outputs() -> dict[Path, str]:
    out = {
        ROOT / 'routines/movement/seek_u8_u8_dda.asm': K.standalone(8),
        ROOT / 'routines/movement/seek_u16_u8_dda.asm': K.standalone(16),
    }
    for p, layout in LAYOUTS.items():
        expr, note = SCRATCH[p]
        text = K.library(p, layout, expr, note)
        out[ROOT / p / 'resident/movement/native/seek_dda.asm'] = text
        out[ROOT / p / 'resident/movement/native/README.md'] = readme(p, layout, (expr, note))
        if p == 'v1_balanced':
            out[ROOT / 'v5_hybrid_lowzp/resident/movement/native/README.md'] = \
                readme('v5_hybrid_lowzp', layout, (expr, note))
            # V5 is built from V1 and publishes the byte-identical backend.
            out[ROOT / 'v5_hybrid_lowzp/resident/movement/native/seek_dda.asm'] = \
                text.replace('for v1_balanced.', 'for v5_hybrid_lowzp (identical to V1).')
    return out


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument('--check', action='store_true')
    a = ap.parse_args()
    bad = []
    for path, text in outputs().items():
        if a.check:
            if not path.exists() or path.read_text(encoding='utf-8') != text:
                bad.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding='utf-8')
    if bad:
        raise SystemExit('SEEK SOURCES OUT OF DATE: ' + ', '.join(bad))
    print('SEEK SOURCES ' + ('CURRENT' if a.check else 'WRITTEN') + f': {len(outputs())} files')


if __name__ == '__main__':
    main()
