#!/usr/bin/env python3
"""Publish exact, human-readable source mirrors for every native signed API.

These files are audit/source-publication views of the executable graph present in
resident images *after MATH_INIT*. They do not replace the canonical integrated
build inputs under relocatable_source/. Each instruction is annotated with its
exact address and bytes so tools/validate_published_signed_sources.py can prove
that the published view matches the shipped executable.
"""
from __future__ import annotations
from pathlib import Path
import csv, json, re, sys
ROOT=Path(__file__).resolve().parents[1]
sys.path.insert(0,str(ROOT/'tools'))
from mini6502 import CPU, REV, SIZE

PROFILES=['v1_balanced','v2_pareto_fast','v3_reu_512k','v4_reu_16m','v5_hybrid_lowzp']
REU={
 'v3_reu_512k':ROOT/'v3_reu_512k/reu/c64_math_v3_512k_game_math.reu',
 'v4_reu_16m':ROOT/'v4_reu_16m/reu/c64_math_v4_16m_game_math.reu',
}
MUL={
 'MATH_SMUL8':'smul8_native.asm',
 'MATH_SMUL16':'smul16_native.asm',
 'MATH_SMUL24':'smul24_native.asm',
 'MATH_SMUL32':'smul32_native.asm',
 'MATH_SMUL32_READY':'smul32_ready_native.asm',
 'MATH_SMUL16_SHR8':'smul16_shr8_native.asm',
 'MATH_SMUL32_SHR16':'smul32_shr16_native.asm',
}
DIV={
 'MATH_SDIV8':'sdiv8_native.asm',
 'MATH_SDIV16':'sdiv16_native.asm',
 'MATH_SDIV24':'sdiv24_native.asm',
 'MATH_SDIV32_16':'sdiv32_16_native.asm',
 'MATH_SDIV32_32':'sdiv32_32_native.asm',
 'MATH_SDIV16_SHL8':'sdiv16_shl8_native.asm',
}
PAIR={
 'MATH_SMUL8':'MATH_UMUL8','MATH_SMUL16':'MATH_UMUL16','MATH_SMUL24':'MATH_UMUL24','MATH_SMUL32':'MATH_UMUL32',
 'MATH_SMUL32_READY':'MATH_UMUL32_READY','MATH_SMUL16_SHR8':'MATH_UMUL16_SHR8','MATH_SMUL32_SHR16':'MATH_UMUL32_SHR16',
 'MATH_SDIV8':'MATH_UDIV8','MATH_SDIV16':'MATH_UDIV16','MATH_SDIV24':'MATH_UDIV24','MATH_SDIV32_16':'MATH_UDIV32_16',
 'MATH_SDIV32_32':'MATH_UDIV32_32','MATH_SDIV16_SHL8':'MATH_UDIV16_SHL8',
}

def api(profile):
 out={}
 for line in (ROOT/profile/'resident/math_api.inc').read_text().splitlines():
  m=re.match(r'\s*(MATH_[A-Z0-9_]+)\s*=\s*\$([0-9A-Fa-f]+)',line)
  if m: out[m.group(1)]=int(m.group(2),16)
 return out

def initialized(profile):
 p=next((ROOT/profile/'resident').glob('math_*_game_math.prg'))
 b=p.read_bytes(); load=b[0]|b[1]<<8
 mem=bytearray(65536); mem[load:load+len(b)-2]=b[2:]
 r=bytearray(REU[profile].read_bytes()) if profile in REU else None
 vals=api(profile); c=CPU(mem,reu=r); c.d=0; c.call(vals['MATH_INIT'],2_000_000)
 return c.mem,vals

def trace(mem,start):
 todo=[start]; seen=set()
 while todo:
  pc=todo.pop()&0xffff
  if pc in seen: continue
  oc=mem[pc]
  if oc not in REV: raise RuntimeError(f'bad opcode ${oc:02X} at ${pc:04X}')
  seen.add(pc); op,mode=REV[oc]; nxt=(pc+SIZE[mode])&0xffff
  if op in ('rts','rti','brk'): continue
  if mode=='rel':
   d=mem[pc+1]; d=d-256 if d>=128 else d; target=(nxt+d)&0xffff
   # Direct UDIV8 ends its alignment loop with INX/BNE.  X cannot wrap in
   # the bounded alignment search, so the physical fallthrough after these
   # two branch sites is unreachable and belongs to unrelated resident data.
   if pc in (0x4124,0x41AC): todo.append(target)
   else: todo.extend((nxt,target))
  elif op=='jmp':
   if mode!='abs': raise RuntimeError(f'indirect JMP at ${pc:04X}')
   todo.append(mem[pc+1]|mem[pc+2]<<8)
  elif op=='jsr': todo.extend((mem[pc+1]|mem[pc+2]<<8,nxt))
  else: todo.append(nxt)
 return seen

def operand(mem,pc,op,mode,code):
 if mode=='imp': return ''
 if mode=='acc': return ' a'
 if mode=='imm': return f' #${mem[pc+1]:02X}'
 if mode=='rel':
  d=mem[pc+1]; d=d-256 if d>=128 else d; t=(pc+2+d)&0xffff
  return f' L{t:04X}'
 if mode in ('zp','zpx','zpy','indx','indy'):
  a=mem[pc+1]; base=f'${a:02X}'
  return {'zp':f' {base}','zpx':f' {base},x','zpy':f' {base},y','indx':f' ({base},x)','indy':f' ({base}),y'}[mode]
 a=mem[pc+1]|mem[pc+2]<<8
 target=f'L{a:04X}' if a in code and op in ('jmp','jsr') else f'${a:04X}'
 return {'abs':f' {target}','absx':f' {target},x','absy':f' {target},y','ind':f' ({target})'}[mode]

def render(profile,name,mem,vals):
 code=trace(mem,vals[name]); unsigned=trace(mem,vals[PAIR[name]])
 overlap=code & unsigned
 if overlap: raise AssertionError(f'{profile} {name}: signed/unsigned executable overlap {sorted(overlap)[:4]}')
 pcs=sorted(code)
 branch_targets=set()
 for pc in pcs:
  op,mode=REV[mem[pc]]
  if mode=='rel':
   d=mem[pc+1]; d=d-256 if d>=128 else d; branch_targets.add((pc+2+d)&0xffff)
  if op in ('jmp','jsr') and mode=='abs':
   t=mem[pc+1]|mem[pc+2]<<8
   if t in code: branch_targets.add(t)
 branch_targets.add(vals[name])
 lines=[
  f'; {name} — exact native-signed executable source mirror for {profile}',
  '; GENERATED by tools/publish_native_signed_sources.py. Do not hand-edit.',
  f'; Canonical integrated build source remains ' + ('relocatable_source/v1_balanced/math_relocatable.asm + tools/build_hybrid.py' if profile=='v5_hybrid_lowzp' else f'relocatable_source/{profile}/math_relocatable.asm'),
  '; This mirror contains every executable instruction reachable from this signed API after MATH_INIT.',
  '; Immutable lookup/data tables are intentionally not duplicated here.',
  f'; Corresponding unsigned API: {PAIR[name]}. Executable overlap: 0 instructions.',
  f'; Public entry: ${vals[name]:04X}. Reachable signed instructions: {len(code)}.',
  '; Each instruction has an @ADDR byte annotation used by the publication validator.',
  '!cpu 6510',''
 ]
 prev_end=None
 for pc in pcs:
  op,mode=REV[mem[pc]]; sz=SIZE[mode]
  if prev_end != pc:
   lines += [f'; ---- executable island ${pc:04X} ----',f'* = ${pc:04X}']
  if pc in branch_targets: lines.append(f'L{pc:04X}:')
  bs=' '.join(f'{mem[pc+i]:02X}' for i in range(sz))
  if op=='lax': text=f'    !byte $A7, ${mem[pc+1]:02X}    ; LAX zp'
  elif op=='anc': text=f'    !byte $0B, ${mem[pc+1]:02X}    ; ANC #imm'
  else: text=f'    {op}{operand(mem,pc,op,mode,code)}'
  lines.append(f'{text:<38} ; @{pc:04X} {bs}')
  prev_end=pc+sz
 lines.append('')
 return '\n'.join(lines),len(code)

def readme(profile,kind,names):
 rel='relocatable_source/v1_balanced/math_relocatable.asm + tools/build_hybrid.py' if profile=='v5_hybrid_lowzp' else f'relocatable_source/{profile}/math_relocatable.asm'
 noun='multiplication' if kind=='multiply' else 'division'
 rows=[]
 for name,fn in names.items(): rows.append(f'| `{name}` | `{fn}` |')
 extra='\nFor V2–V4, `smul16_practical_116zp.a` remains the hand-authored executable-ZP SMUL16 source and its relocation JSON remains alongside these mirrors.\n' if kind=='multiply' and profile in ('v2_pareto_fast','v3_reu_512k','v4_reu_16m') else ''
 if kind=='division': extra+='\n`SMOD*` entries are aliases of the corresponding native signed divider and therefore do not need separate executable kernels.\n'
 return f'''# Native signed {noun}: published executable sources\n\nThese files expose the **actual native signed executable paths shipped by `{profile}`**. They are exact generated source mirrors of the resident image after `MATH_INIT`, not placeholders. Every instruction is annotated with its resident address and bytes and is checked by `tools/validate_published_signed_sources.py`.\n\nThe canonical integrated build source remains `{rel}`. These mirrors exist so a GitHub reader can inspect each signed implementation directly without hunting through the monolithic generated source. Shared immutable lookup/data tables are not duplicated; corresponding unsigned executable instructions are never entered.\n\n| Public API | Published source |\n|---|---|\n{chr(10).join(rows)}\n{extra}\nSee `../../SIGNED_LINK_MAP.json` for placements/provenance and `validation/review/SIGNED_LAYOUT_VALIDATION.json` for the zero-overlap proof.\n'''

def main():
 report={'status':'PASS','profiles':{}}
 for p in PROFILES:
  mem,vals=initialized(p); pr={}
  for kind,names in [('multiply',MUL),('division',DIV)]:
   d=ROOT/p/'resident/signed'/kind/'native'; d.mkdir(parents=True,exist_ok=True)
   d.joinpath('README.md').write_text(readme(p,kind,names))
   kr={}
   for name,fn in names.items():
    text,n=render(p,name,mem,vals); d.joinpath(fn).write_text(text); kr[name]={'file':fn,'instructions':n}
   pr[kind]=kr
  report['profiles'][p]=pr
 out=ROOT/'validation/review/PUBLISHED_SIGNED_SOURCES.json'; out.write_text(json.dumps(report,indent=2)+'\n')
 print('PUBLISHED',sum(len(MUL)+len(DIV) for _ in PROFILES),'native signed source mirrors')

if __name__=='__main__': main()
